### ISSUE TITLE
Latest v0.22 victoria-metrics-k8s-stack is unable to uninstall

### ISSUE THREAD

**Issue by matrix-root** [VictoriaMetrics/helm-charts#1012]
Operator's uninstall cleanup hook tries to delete vmalertmanager

However, it going stuck during delete. Describe of vmalertmanager shows such event:
```
Warning  ReconcilationError  <unknown>  victoria-metrics-operator  cannot patch finalizers for object="/v1, Kind=ServiceAccount" with name="vmalertmanager-victoria-metrics": se
rviceaccounts "vmalertmanager-victoria-metrics" is forbidden: User "system:serviceaccount:monitoring:victoria-metrics-operator" cannot patch resource "serviceaccounts" in API gro
up "" in the namespace "monitoring"
```

**Comment by matrix-root** [comment]
Btw, see this issue since 0.21

Expected that 0.22 could solve this issue. If nobody don't know how to fix - I could try to prepare MR by myself

**Comment by Haleygo** [comment]
Thanks for reporting!
New operator and k8s-stack charts will be released after https://github.com/VictoriaMetrics/helm-charts/pull/1013.

**Comment by Haleygo** [comment]
[victoria-metrics-operator-0.31.2](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-operator-0.31.2) and [victoria-metrics-k8s-stack-0.22.1](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.22.1) must fix this issue, close as completed, feel free to reopen if there is further question.

**Comment by matrix-root** [comment]
Thanks! Works fine now
