### ISSUE TITLE
Deprecated etcd alert "etcdHighNumberOfFailedGRPCRequests"

### ISSUE THREAD

**Issue by ansezv** [VictoriaMetrics/helm-charts#1027]
**What happened?**
Deprecated alert that considers canceled requests to be erroneous. This request has been corrected by the developer.
[Etcd issues](https://github.com/etcd-io/etcd/pull/13127)

**Environment (with versions)?**
Kubernetes 1.24.17
Etcd 3.5.6
Helm-chart victoria-metrics-k8s-stack-0.21.3

**Comment by Haleygo** [comment]
Fixed in https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.23.0.
