### ISSUE TITLE
Using vmagent as datasource in Grafana

### ISSUE THREAD

**Issue by SpoortiPalakshaiah** [VictoriaMetrics/helm-charts#105]
Hello,

I'm using Victoriametrics in k8s. I've deployed Victoriametrics using operator. I'm using vmagent as drop-in replacement for Prometheus.

What should be datasource used in Grafana to add vmagent?

**Comment by f41gh7** [comment]
vmagent  scrapes targets and pushes metrics to the remote_write server VMSingle or VMCluster, usually. So you have to deploy it first and specify its service url as grafana datasource.
