### ISSUE TITLE
Should prometheus operator CRDs be added as a subchart to stack deployment

### ISSUE THREAD

**Issue by SQLJames** [VictoriaMetrics/helm-charts#1059]
In essence, cloudnative-pg operator monitoring attempts to automatically push out the prometheus operator CRD directly when configuring monitoring for a cluster, discussed [here](https://cloudnative-pg.io/documentation/1.17/monitoring/#monitoring-instances).  However, since this is not Prometheus you will instead just get this information log which is quite noisy.
```
{"level":"info","ts":"2024-06-11T19:03:18Z","msg":"PodMonitor CRD not present. Cannot create the PodMonitor object","controller":"cluster","controllerGroup":"postgresql.cnpg.io","controllerKind":"Cluster","Cluster":{"name":"awx","namespace":"postgres"},"namespace":"postgres","name":"awx","reconcileID":"c950eef9-34f8-473f-b02f-3d632d5b6219"}
```

What I ended up doing was deploying the prometheus operator CRDs alongside the chart using this [chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds). To quiet this message down and then just setup an additional podscrape configuration for VMAgent to gather the data.

Now, what I haven't tested yet was seeing if that metrics port was still there prior to setting "enablePodMonitor : true". 

But my thought was that since there is a conversion tool that allows users to convert the CRDS over, we should have an option to install these CRDs with the chart, as a nice to have. By default, it would be disabled incase there are already installed CRDs in the cluster.

**Comment by Haleygo** [comment]
Hello!
The `prometheus-operator-crds` has been added as dependency of victoria-metrics-k8s-stack since [victoria-metrics-k8s-stack-0.23.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.23.0), you can enable it with `prometheus-operator-crds.enabled`.

**Comment by SQLJames** [comment]
Ha, that's awesome I was using 22.X, I updated and it works well :)
