### ISSUE TITLE
Custom Port name are failing for VMSelect and VMInsert

### ISSUE THREAD

**Issue by hanumanhuda** [VictoriaMetrics/helm-charts#1060]
Feature Request: https://github.com/VictoriaMetrics/helm-charts/issues/972
Feature PR: https://github.com/VictoriaMetrics/helm-charts/pull/975
VM cluster version: https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.11.16

Error Message
```
Liveness probe errored: strconv.Atoi: parsing "http": invalid syntax
Readiness probe errored: strconv.Atoi: parsing "http": invalid syntax
```

Root cause
vmselect and vminsert deployments are having http port name for readiness and liveness probe instead they should be using the custom port name.
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/vmselect-deployment.yaml#L98

**Comment by Haleygo** [comment]
Fixed in [victoria-metrics-cluster-0.11.19](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.11.19), close as completed.
