### ISSUE TITLE
volumeClaimTemplates does not have the full spec, causing Out of Sync in ArgoCD

### ISSUE THREAD

**Issue by chrisjohnson00** [VictoriaMetrics/helm-charts#1092]
We install VM Single Instance with ArgoCD using your helm chart.  It seems that the K8s API "fixes" the volumeClaimTemplates created by the helm chart, which then causes ArgoCD to say the chart is "Out of Sync".

Argo complaining:
![image](https://github.com/VictoriaMetrics/helm-charts/assets/1231933/a4c2d988-10a8-4a57-8949-2257b5f94c8c)

You can see the STS has it in it's YAML definition in the cluster:
![image](https://github.com/VictoriaMetrics/helm-charts/assets/1231933/7c5ba016-f7b5-4081-a8de-c116d798f80b)

https://kubernetes.io/docs/reference/kubernetes-api/config-and-storage-resources/persistent-volume-claim-v1/#PersistentVolumeClaim is the spec, which does include the missing elements.

**Comment by Haleygo** [comment]
The fix is included in https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-single-0.9.23 and https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.24.0.

**Comment by chrisjohnson00** [comment]
![image](https://github.com/VictoriaMetrics/helm-charts/assets/1231933/ed306798-3a19-4640-b701-3fbafe4fe002)

Argo is happy, and so am I.  Thanks for the quick turn around!
