### ISSUE TITLE
victoriametrics/vmstorage v1.54.1-cluster policy / runAsNonRoot

### ISSUE THREAD

**Issue by rakeshsingrikonda** [VictoriaMetrics/helm-charts#110]
Hey,

it seems that vmstorage can`t run in clusters with PSP enabled.

applied these changes to values.yaml

podSecurityContext:
  runAsUser: 1000 
  runAsNonRoot: true
containerWorkingDir: "/tmp"

getting below error:

{"ts":"2021-02-18T18:39:04.605Z","level":"fatal","caller":"VictoriaMetrics/app/vmstorage/main.go:61","msg":"cannot open a storage at /storage with -retentionPeriod=1: cannot create lock file \"/storage/flock.lock\": open /storage/flock.lock: permission denied"}

**Comment by f41gh7** [comment]
Hello, can you try to use securityContext instead of podSecurityContext 
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/values.yaml#L372

Does it help?

**Comment by Amper** [comment]
Closed due to lack of activity
