### ISSUE TITLE
Add "extraSecrets" to victoria-metrics-single to allow ingress basic auth

### ISSUE THREAD

**Issue by micw** [VictoriaMetrics/helm-charts#111]
Hello,

I have set up a victoriametrics server + grafana + an ingress for the metrics sent by external agents. Everything works great, The only issue was that I had to create an extra helm chart to create a secret for basic auth on the metrics ingress.

I have seen that the chart can already extended by "extraContainers" and such. Would you mind to add an "extraSecrets" that allows to deploy a basic auth secret along with the server?

Kind regards,
Michael.

**Comment by corporate-gadfly** [comment]
From a newbie perspective, isn't that what vmauth could provide? I could be totally off-base.
