### ISSUE TITLE
Incorrect relabel_config keep_if_equal for service endpoints.

### ISSUE THREAD

**Issue by cwsatpolymath** [VictoriaMetrics/helm-charts#112]
Chart version `0.7.6` for victoria-metrics-agent has the following `relabel_config` for the `kubernetes-pods`, `kubernetes-service-endpoints`, and `kubernetes-service-endpoints-slow` jobs:

```
      - action: keep_if_equal
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_port
        - __meta_kubernetes_pod_container_port_number
```

This is correct for the `kubernetes-pods` job, but for the service endpoint jobs it will not scrape endpoints for services for which the pods do not have the prometheus scrape annotation.  To correct this it should be changed as follows for the service endpoints:

```
      - action: keep_if_equal
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_port
        - __meta_kubernetes_pod_container_port_number
```

**Comment by tgruenert** [comment]
see https://github.com/VictoriaMetrics/helm-charts/pull/146
could it be closed?

**Comment by hagen1778** [comment]
Closed as inactive
