### ISSUE TITLE
looks like "https://victoriametrics.github.io/helm-charts/" is not a valid chart 

### ISSUE THREAD

**Issue by NahumLitvin** [VictoriaMetrics/helm-charts#1126]
`helm repo add victoriametrics https://victoriametrics.github.io/helm-charts/`
Error: looks like "https://victoriametrics.github.io/helm-charts/" is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal array into Go struct field ChartVersion.entries.annotations of type string

**Comment by AndrewChubatiuk** [comment]
made updates, do you still have issues?

**Comment by lmolas** [comment]
Everything back to normal on my side.
Flux is not complaining anymore.

**Comment by AndrewChubatiuk** [comment]
hey @NahumLitvin @joshbsemperis
do you guys still have issues?
