### ISSUE TITLE
[victoria-metrics-k8s-stack] wrong cleanup image when uninstall 0.23.3 and 0.23.4 

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#1129]
```Failed to pull image "bitnami/kubectl:v1.18.0": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/kubectl:v1.18.0": failed to resolve reference "docker.io/bitnami/kubectl:v1.18.0": docker.io/bitnami/kubectl:v1.18.0: not found```

should be:
docker.io/bitnami/kubectl:1.18.0

(no v).

**Comment by AndrewChubatiuk** [comment]
hey @brokenjacobs 
value v1.18.0 can appear if it's defined in `cleanupImage.tag`.

**Comment by brokenjacobs** [comment]
> hey @brokenjacobs value v1.18.0 can appear if it's defined in `cleanupImage.tag`.

It is not. nothing is defined in my values for cleanupImage

**Comment by AndrewChubatiuk** [comment]
version of previous cleanup image was v1.18.0
how do you deploy a helm chart?

**Comment by brokenjacobs** [comment]
I use flux to deploy. I just pulled the calculated values stored in the cluster configMap and sure enough:
```
  cleanupImage:
    pullPolicy: IfNotPresent
    repository: bitnami/kubectl
    tag: v1.18.0
```
Can I put:
```
cleanupImage.tag: {{ printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor }}
```

In my values to make sure it overwrites? Will the template be honored?

**Comment by brokenjacobs** [comment]
FYI: Forcing this to set:
```
cleanupImage:tag: ""
```
Uses the old value stored in the release.

**Comment by Haleygo** [comment]
Hello @brokenjacobs ,
Are you installing victoria-metrics-k8s-stack-0.23.3 or victoria-metrics-k8s-stack-0.23.4 here? 
I believe it's related to chart version mismatch in those two versions. We updated the cleanupImage in victoria-metrics-k8s-stack chart values, but didn't update the dependency, so operator subchart stays in `v0.32.0` which uses the old tag value. And they combined to `bitnami/kubectl:v1.18.0`.
The workaround would be upgrade your release to [victoria-metrics-k8s-stack-0.23.5](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.23.5) or higher, then uninstall.
And it shouldn't happen in victoria-metrics-k8s-stack-0.23.5 or higher version.
