### ISSUE TITLE
default values for vm/victoria-metrics-alert not work

### ISSUE THREAD

**Issue by paragor** [VictoriaMetrics/helm-charts#113]
**actual**:

```
> helm repo add vm https://victoriametrics.github.io/helm-charts/
...
> helm repo update
...
> helm show values vm/victoria-metrics-alert > alert.values.yaml
> helm install vmalert --dry-run vm/victoria-metrics-alert -f alert.values.yaml 
Error: template: victoria-metrics-alert/templates/server-deployment.yaml:2:49: executing "victoria-metrics-alert/templates/server-deployment.yaml" at <len .Values.server.config.alerts.groups>: error calling len: len of untyped nil
```

**expected**:
install anything

**Comment by f41gh7** [comment]
Hello, vmalert has required parameters, that must be pre-defined by user. Error message was fixed at latest version.

  You need to specify at least group  rules: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-alert/values.yaml#L178 and datasource.url  https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-alert/values.yaml#L55

 docs for vmalert https://victoriametrics.github.io/vmalert.html
