### ISSUE TITLE
Operator: uninstall hook does not work

### ISSUE THREAD

**Issue by matrix-root** [VictoriaMetrics/helm-charts#1143]
I'm using latest Talos with K8s 1.30.2 and latest Flux 2.3 and having issues with row below
https://github.com/VictoriaMetrics/helm-charts/blob/08c7991f1b0ec5858acfdb89c1e1816ec68fc7a8/charts/victoria-metrics-operator/templates/uninstall_hook.yaml#L27

So, by default helm renders `bitnami/kubectl:v1.18.0` here - and basically **this image just does not exist**. And for my setup (which is common and I'm sure used by lots of guys) uninstall hook does not work with default values

Of course, I could hardcode image tag with values - but maybe we could investigate this issue. Maybe removing `v`-prefix from default tag could solve this

Btw, this issue produces helm release in stuck uninstalling state. Usually it's nightmare to rollback this properly

**Comment by Haleygo** [comment]
Please see comment in https://github.com/VictoriaMetrics/helm-charts/issues/1129#issuecomment-2220967140, close as duplicated.
