### ISSUE TITLE
Possibility to use victoria-metrics-agent Helm chart without scrape.yml config map

### ISSUE THREAD

**Issue by CarpathianUA** [VictoriaMetrics/helm-charts#116]
Hey,

It would be great to have a possibility to provision `vmagent` without scrape configuration to use it as a buffering proxy between Prometheus (remote_write) and Victoria Metrics. 

As I can see, for now, ConfigMap with scrape.yml configuration is a mandatory component, since Deployment's `containers` definition in a [podTemplate](https://github.com/VictoriaMetrics/helm-charts/blob/b0b4b1eff0b432717972e5e237c1a1a968a11dcb/charts/victoria-metrics-agent/templates/deployment.yaml#L45) have a 
```
...
          args:
            - -promscrape.config=/config/scrape.yml
...
```
hardcoded.

Thank you for your time!

**Comment by f41gh7** [comment]
added, example command-line: ` helm upgrade -i agent vm/victoria-metrics-agent  --set 'remoteWriteUrls[0]=http://some-host' --set 'config='`
