### ISSUE TITLE
Overriding rules will apply to all rules in group and type

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1214]
So if you add an annotation to an exact rule, it will apply to all rules in the group and even type (recording/alert).

Seems that `mergeOverwrite` in Helm will mutate the underlying Go maps. So all arguments needs a `deepCopy`:

https://github.com/VictoriaMetrics/helm-charts/blob/4040c7e6f9a134972535fb1fdf9c973a2dfb53be/charts/victoria-metrics-k8s-stack/templates/rules/rule.yaml#L88

**Comment by AndrewChubatiuk** [comment]
hey @dctrwatson. this issue was fixed in release [v0.25](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.25.0)
