### ISSUE TITLE
[victoria-metrics-agent] doesn't create VMAgent resource

### ISSUE THREAD

**Issue by Ostapenko-Maksym** [VictoriaMetrics/helm-charts#1220]
Greetings!
I try to set up a number of VM charts using separate helm charts instead of using k8s-stack. Issue I came up with is that by using `victoria-metrics-agent` helm chart it doesn't create VMAgent resource and thus there is no way to use VM Operator API. To be more precise I noticed that VM operator created VMServiceScrape resources as part of Prometheus migration but VMAgent is not able to use `spec.selectAllByDefault` parameter to use those scrapes. And nowhere in documentation I found a way to use this parameter outside of VMAgent resource.
Could you please clarify if there is any way to either create VMAgent resource using `victoria-metrics-agent` chart or if there is any other way to use `spec` parameters using this chat

**Comment by zekker6** [comment]
Hello @Ostapenko-Maksym 
Charts other than `k8s-stack` do not use operator and CRDs for the deployment, these charts use plain kubernetes objects. It is not possible to use these charts to integrate with operator CRDs. 
If the idea is to create separate charts to replace `k8s-stack` I would suggest to deploy operator via it's [own chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator) and deploy CRDs either by using helm or just by applying plain CRD objects.

**Comment by AndrewChubatiuk** [comment]
closing this as answered
