### ISSUE TITLE
[victoria-metrics-k8s-stack] VMAlert Notifires Does Not Care About VMAlertManager `routePrefix`

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#1263]
Hi! in the vm-k8s-stack we are using the `routePrefix` in the VMAlertManager but there is a problem with the VMAlert. It does not watch for the `routePrefix` and so it can not send its alerts to the VMAlertManger. We are currently add the notifires url manually.

**Comment by AndrewChubatiuk** [comment]
it was fixed in https://github.com/VictoriaMetrics/helm-charts/pull/1246
need to wait till it's released

**Comment by alihoda** [comment]
> it was fixed in #1246 need to wait till it's released

Nice catch. Thanks
