### ISSUE TITLE
victoria-metrics-single helm chart 0.10.0 statefulset seems broken

### ISSUE THREAD

**Issue by wasilak** [VictoriaMetrics/helm-charts#1280]
Hi! 

Seems like starting with refactoring (https://github.com/VictoriaMetrics/helm-charts/commit/3b872689ff2ccf6a934a13d2bef10e25ccf35352) done in helm chart v`0.10.0` storageclass in statefulset is broken by this line:
https://github.com/VictoriaMetrics/helm-charts/blob/3b872689ff2ccf6a934a13d2bef10e25ccf35352/charts/victoria-metrics-single/templates/server-statefulset.yaml#L259

Error I'm getting using helm template (also in ArgoCD):

```
Error: template: victoria-metrics-single/templates/server-statefulset.yaml:259:29: executing "victoria-metrics-single/templates/server-statefulset.yaml" at <"">: can't give argument to non-function ""
helm.go:84: [debug] template: victoria-metrics-single/templates/server-statefulset.yaml:259:29: executing "victoria-metrics-single/templates/server-statefulset.yaml" at <"">: can't give argument to non-function ""
```

Downgrading to `0.9.26` solved it for me for now.

Thanks!

**Comment by AndrewChubatiuk** [comment]
hey @wasilak 
thanks for submitting this issue, already created a PR with a fix, which will be available as soon as it's merged

**Comment by wasilak** [comment]
Amazing! thank you! 🎉
