### ISSUE TITLE
vmoperator container v0.47.0 crashes

### ISSUE THREAD

**Issue by Demmyart** [VictoriaMetrics/helm-charts#1288]
Hello everyone,

I'm encountering an issue while deploying VictoriaMetrics using the victoria-metrics-k8s-stack Helm chart. The deployment fails with the following error message in the operator pod:

`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "manager": executable file not found in $PATH: unknown`

Details:

VictoriaMetrics Operator Version: `v0.47.0`
VictoriaMetrics Helm Chart Version: `0.25.2`

Has anyone faced this issue before? Could this be related to the specific versions I'm using, or is there something I'm missing in the configuration?

Any help or pointers would be greatly appreciated!

Thanks!

**Comment by AndrewChubatiuk** [comment]
hey @Demmyart 
what values are you passing to operator?

**Comment by Demmyart** [comment]
Hi, I just solved this by completely deleting the deployment and recreating it. Restarting with a rolling update was causing the issue for me. 
Thanks for your attention!
