### ISSUE TITLE
[victoria-metrics-k8s-stack] Grafana Failed to Load `nodeexporter` Dashboards

### ISSUE THREAD

**Issue by alihoda** [VictoriaMetrics/helm-charts#1312]
Hey. I have a problem with deploying Grafana in the vm-k8s-stack helm chart. I have deployed Grafana with the default value of the vm-k8s-stack chart but in the Pod log I have this error message:
```
logger=provisioning.dashboard type=file name=default t=2024-08-24T13:18:56.781221877Z level=error msg="failed to load dashboard from " file=/var/lib/grafana/dashboards/default/nodeexporter.json error=EOF
```
It seems that there should be a file for that dashboard but I can not find any. Also have tried to go with this values:

```
grafana:
  dashboardProviders: {}
  dashboards: {}
```

but nothing changed!! In the Grafana helm chart there is a comment for `sidecar` that *"Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards"* but in the vm-k8s-stack both of them is used!! Is there any reason for using dashboardProviders?

**Comment by AndrewChubatiuk** [comment]
hey @alihoda 
starting [0.25.11](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.25.11)
k8s stack doesn't use `grafana.dashboards` and `grafana.dashboardProviders` by default
