### ISSUE TITLE
Error when trying to deploy victoria-metrics-cluster, beginning with Version 0.12.1

### ISSUE THREAD

**Issue by marrau** [VictoriaMetrics/helm-charts#1359]
Getting an Error when trying to deploy victoria-metrics-cluster, beginning with Version 0.12.1.

Expectation: Runs smoothly

Observed Behaviour: Breaks with the following Error.

```
STDERR:
  Error: template: victoria-metrics-cluster/templates/vmselect-statefulset.yaml:52:16: executing 
  "victoria-metrics-cluster/templates/vmselect-statefulset.yaml" at 
  <include "victoria-metrics.vmselect.vmselect-pod-fqdn" .>: 
       error calling include: template: victoria-metrics-cluster/templates/_helpers.tpl:195:16: executing 
            "victoria-metrics.vmselect.vmselect-pod-fqdn" at 
             <.Values.vmselect.extraArgs.httpListenAddr>: can't evaluate field Values in type int
 ```

**Comment by marrau** [comment]
Checked in on those Files, and i think this place here needs to sit above the range-Call.
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/_helpers.tpl#L194-197

Else "." is going to be the iterated Number, which would match the seen Error-Description.

**Comment by AndrewChubatiuk** [comment]
hey @marrau 
thanks for submitting an issue
created pr with a fix
