### ISSUE TITLE
Error: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml

### ISSUE THREAD

**Issue by ratafonso** [VictoriaMetrics/helm-charts#1398]
Hello guys,

I'm receiving a error message when I'm trying to install the helm chart victoria-metrics-k8s-stack version 0.25.10. Can you help with more information and how to proceed for resolve this issue? Is it something from bugfix?

Following the error message:

Error: Error: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml:27:20: executing "victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml" at <include "vm.image" (dict "helm" . "app" $app)>: error calling include: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/charts/victoria-metrics-common/templates/_image.tpl:7:17: executing "vm.image" at <tpl (printf "%!s(MISSING):%!s(MISSING)" .app.image.repository (.app.image.tag | default $Chart.AppVersion)) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: bitnami/kubectl:1.28: "BasePath" is not a value

This is my helm-values.yaml file content:

victoria-metrics-operator:
  enabled: true
vmsingle:
  enabled: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 65Gi
alertmanager:
  enabled: false
  monzoTemplate:
      enabled: true
vmalert:
  enabled: true
grafana:
  enabled: false
prometheus-node-exporter:
  enabled: true
kube-state-metrics:
  enabled: true
kubelet:
  enabled: true
kubeApiServer:
  enabled: true
kubeControllerManager:
  enabled: true
kubeDns:
  enabled: false
coreDns:
  enabled: true
kubeEtcd:
  enabled: true
kubeScheduler:
  enabled: true
kubeProxy:
  enabled: false
crds:
  enabled: true
prometheus-operator-crds:
  enabled: true

**Comment by AndrewChubatiuk** [comment]
hey
Which helm version are you using?

**Comment by evgenii-avdiukhin** [comment]
Facing the same issue here, my helm version is "v3.11.0"

**Comment by evgenii-avdiukhin** [comment]
> please try 3.14+

that does the trick, thank you so much

**Comment by ratafonso** [comment]
> hey Which helm version are you using?

Chart Version 0.25.10
App Version v1.102.1

**Comment by ratafonso** [comment]
Sorry, I'm using Helm v3.13. I updated my helm to v3.15.3 and it's work.

Thank you so much guys.
