### ISSUE TITLE
[victoria-metrics-operator] Add ability to disable creation of all cluster roles

### ISSUE THREAD

**Issue by slimes28** [VictoriaMetrics/helm-charts#1400]
Currently, it is impossible to disable the creation of all cluster roles if enabling the creation of crds.
There was such option before this change: https://github.com/VictoriaMetrics/helm-charts/commit/90a767476a109e401d0cc4d2115f25c8ad4045f7#diff-d5ac73415a70ef365a1a8782315903b0915184033e9f86e8abb7a7e0b5ca1612

**Comment by AndrewChubatiuk** [comment]
hey @slimes28 
previous logic for optional watchNamespaces creation was not valid enough, it created cluster role if any value is defined for `watchNamespace`, but operator expects a comma-separated list for WATCH_NAMESPACE value, which requires having cluster role anyway
I've added PR, which avoids clusterRole creation only for a case, when `watchNamespaces` contains only a namespace, where operator is deployed

**Comment by AndrewChubatiuk** [comment]
sorry, misunderstood your message, there was a bug in aggregated cluster roles conditions, which I've fixed in the same PR as well

**Comment by AndrewChubatiuk** [comment]
fix is available in [v0.34.7](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-operator-0.34.7)
