### ISSUE TITLE
[victoria-metrics-k8s-stack] upgrade from 0.24.3 to 0.25.11 fails

### ISSUE THREAD

**Issue by oleksandrh-everc** [VictoriaMetrics/helm-charts#1413]
upgrade of the stack fails to update `victoria-metrics-operator` 
```
Error: UPGRADE FAILED: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml:33:20: executing "victoria-metrics-k8s-stack/charts/victoria-metrics-operator/templates/uninstall_hook.yaml" at <include "vm.image" (dict "helm" . "app" $app)>: error calling include: template: victoria-metrics-k8s-stack/charts/victoria-metrics-operator/charts/victoria-metrics-common/templates/_image.tpl:7:17: executing "vm.image" at <tpl (printf "%s:%s" .app.image.repository (.app.image.tag | default $Chart.AppVersion)) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: bitnami/kubectl:1.30: "BasePath" is not a value
```
---
Observations:

0.24 had the  `victoria-metrics-operator` dependency of version `0.33.*` without any additional dependencies 
and
0.25 has the  `victoria-metrics-operator` dependency of version `0.34.*` which introduces a new dep `victoria-metrics-common` https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-operator-0.34.0/charts/victoria-metrics-operator/Chart.yaml#L34

**Comment by AndrewChubatiuk** [comment]
hey @oleksandrh-everc 
helm 3.14+ required

**Comment by oleksandrh-everc** [comment]
thanks @AndrewChubatiuk 
I've missed that part in https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.25.0
