### ISSUE TITLE
Dashboards not rendering correctly

### ISSUE THREAD

**Issue by P-n-I** [VictoriaMetrics/helm-charts#1414]
We install via Argo and install the Grafana v8.4.* chart direct (rather than as part of the vm-stack) we currently have Grafana v11.1.5 (2e2ef4e402)

I've noticed on upgrade to v0.25.11 that the VM dashboards are no longer rendering correctly, example:

![image](https://github.com/user-attachments/assets/87da8bf2-0f40-4dd4-9b3a-d5d0740fcae1)
![image](https://github.com/user-attachments/assets/4d93be85-d34f-4afb-a876-12aa5f094a7c)

**Comment by AndrewChubatiuk** [comment]
fix is available in 0.25.12

**Comment by P-n-I** [comment]
Thanks, again! will confirm shortly.
