### ISSUE TITLE
VMSingle server-statefulset vm.probe error

### ISSUE THREAD

**Issue by ricristian** [VictoriaMetrics/helm-charts#1436]
Hello, 

I've tried to replicated each step from https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single  but unfortunately the helm installation fails  ( I've tried also with 0.10.0 same error )

helm version
version.BuildInfo{Version:"v3.12.3", GitCommit:"3a31588ad33fe3b89af5a2a54ee1d25bfe6eaa5e", GitTreeState:"clean", GoVersion:"go1.20.7"}

os: macOS Sonoma 14.6.1

` helm show values vm/victoria-metrics-single > values.yaml

󰀵 ~   19:47    
 helm show values vm/victoria-metrics-single > values.yaml

󰀵 ~   19:47  took 1s  
 helm install vmsingle vm/victoria-metrics-single -f values.yaml -n monitoring --debug --dry-run
install.go:200: [debug] Original chart version: ""
install.go:217: [debug] CHART PATH: /Users/ricristian/Library/Caches/helm/repository/victoria-metrics-single-0.11.1.tgz

Error: INSTALLATION FAILED: template: victoria-metrics-single/templates/server-statefulset.yaml:127:30: executing "victoria-metrics-single/templates/server-statefulset.yaml" at <include "vm.probe" (dict "app" $app "type" "readiness")>: error calling include: template: victoria-metrics-single/charts/victoria-metrics-common/templates/_pod.tpl:66:6: executing "vm.probe" at <tpl (toYaml $probe) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: failureThreshold: 3
httpGet:
  path: /health
  port: http
  scheme: HTTP
initialDelaySeconds: 5
periodSeconds: 15
timeoutSeconds: 5: "BasePath" is not a value
helm.go:84: [debug] template: victoria-metrics-single/templates/server-statefulset.yaml:127:30: executing "victoria-metrics-single/templates/server-statefulset.yaml" at <include "vm.probe" (dict "app" $app "type" "readiness")>: error calling include: template: victoria-metrics-single/charts/victoria-metrics-common/templates/_pod.tpl:66:6: executing "vm.probe" at <tpl (toYaml $probe) .>: error calling tpl: cannot retrieve Template.Basepath from values inside tpl function: failureThreshold: 3
httpGet:
  path: /health
  port: http
  scheme: HTTP
initialDelaySeconds: 5
periodSeconds: 15
timeoutSeconds: 5: "BasePath" is not a value
INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:147
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.6.1/command.go:916
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.6.1/command.go:968
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:250
runtime.goexit
        runtime/asm_arm64.s:1172`

**Comment by AndrewChubatiuk** [comment]
helm 3.14+ is required
