### ISSUE TITLE
Option to remove deprecated extensions API from rbac?

### ISSUE THREAD

**Issue by uhthomas** [VictoriaMetrics/helm-charts#1438]
Our Kubernetes clusters are quite strict, and use modern APIs. The extensions API was replaced by the networking API a long time ago, and so our roles do not allow anything access to the deprecated and unused API. This API is included in RBAC roles, it would be nice if this could be disabled.

https://github.com/VictoriaMetrics/helm-charts/blob/cc042ce60d8d01b779edcf810fe45c0fdb477fcb/charts/victoria-metrics-agent/templates/clusterrole.yaml#L28

**Comment by AndrewChubatiuk** [comment]
charts require k8s 1.25+ so I removed deprecated apis completely

**Comment by uhthomas** [comment]
Perfect, thanks :)
