### ISSUE TITLE
[victoria-metrics-k8s-stack] Use global.cluster.dnsDomain in all URL generation

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1455]
Since the default ndots config is 5 for pods, it would reduce load on kube-dns if all k8s service hostnames had the cluster's dnsDomain appended to them.

EG: `vmalertmanager-vm-stack-0.vmalertmanager-vm-stack.monitoring.svc.cluster.local.`

While I don't think most VM components resolve DNS often, it's nice not to have them performing 6 or more DNS queries when they do.

**Comment by AndrewChubatiuk** [comment]
hey @dctrwatson
`global.cluster.dnsDomain` option is available starting release v0.28.1
