### ISSUE TITLE
[victoria-metrics-k8s-stack] node-exporter has incorrect job label

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1458]
node-exporter no longer has correct `jobLabel` after: https://github.com/prometheus-community/helm-charts/pull/4737

**Comment by AndrewChubatiuk** [comment]
as I see from rendered templates, jobLabel was added to pod labels correctly, but it looks like that with VMServiceScrape enabled for node-exporter `jobLabel` should be configured for node-exporter service instead

**Comment by dctrwatson** [comment]
> as I see from rendered templates, jobLabel was added to pod labels correctly, but it looks like that with VMServiceScrape enabled for node-exporter `jobLabel` should be configured for node-exporter service instead

Yup, equivalent to before that PR would be `commonLabels` now. But since it's really only needed for the service, I'm not if that was still the intent.

**Comment by AndrewChubatiuk** [comment]
fix was included into 0.25.16 release of k8s-stack
