### ISSUE TITLE
[victoria-metrics-anomaly] Invalid option loggerFormat for vmanomaly

### ISSUE THREAD

**Issue by TheDJVG** [VictoriaMetrics/helm-charts#1476]
Latest release of VMAnomaly does not have a `--loggerFormat` option but it's set in the default `values.yaml`:
https://github.com/VictoriaMetrics/helm-charts/blob/f5a8450c3454e19065b63899a58fd009e018b280/charts/victoria-metrics-anomaly/values.yaml#L42-L43

This generates a startup error:
```bash
# docker run --rm victoriametrics/vmanomaly --loggerFormat=json /config
usage: vmanomaly.pyc [-h] [--log_level {INFO,ERROR,WARNING,FATAL,DEBUG}]
                     [--watch] [--license STRING | --license-file PATH]
                     [--license-verify-offline]
                     config [config ...]
vmanomaly.pyc: error: unrecognized arguments: --loggerFormat=json
```

**Comment by AndrewChubatiuk** [comment]
fix is available in https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-anomaly-1.4.5
