### ISSUE TITLE
[victoria-metrics-k8s-stack] 0.25.16 upgrade fails

### ISSUE THREAD

**Issue by dhess** [VictoriaMetrics/helm-charts#1509]
I've followed the instructions for upgrading 0.25.15 to 0.25.16, but I'm still getting an error:

1. Running victoria-metrics-k8s-stack v0.25.15, I set `victoria-metrics-operator.admissionWebhooks.enabled: false` in `values.yaml` and apply. Argo CD successfully deletes the `victoria-metrics-victoria-metrics-operator-admission` webhooks.
2. Upgrade the chart to v0.25.16 and apply.
3. Argo CD cannot sync: `one or more objects failed to apply, reason: Service "victoria-metrics-victoria-metrics-operator" is invalid: spec.ports[2].name: Duplicate value: "webhook". Retrying attempt #5 at 12:52PM.`

This error repeats over and over, and Argo CD can't complete the upgrade.

**Comment by AndrewChubatiuk** [comment]
suppose it's related to https://github.com/argoproj/argo-cd/issues/17717
try to delete operator service and sync application again

**Comment by AndrewChubatiuk** [comment]
closing this as it's argocd issue

**Comment by dhess** [comment]
OK, thanks, that did the trick.
