### ISSUE TITLE
improve doc for k8s cluster.

### ISSUE THREAD

**Issue by vladimir4862** [VictoriaMetrics/helm-charts#151]
this line from README.md in victoria-metrics-k8s-stack doesn't work, If you run this on new cluster (without victoria CRDs)

```
Test the installation with command:

helm install [RELEASE_NAME] vm/victoria-metrics-k8s-stack -f values.yaml -n NAMESPACE --debug --dry-run
```
output 

`Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "VMAgent" in version "operator.victoriametrics.com/v1beta1", unable to recognize "": no matches for kind "VMAlert" in version "operator.victoriametrics.com/v1beta1.....",`

so maybe need add some additional steps in "Prerequisites"

**Comment by f41gh7** [comment]
Looks like bug. Which helm version are you using?

**Comment by vladimir4862** [comment]
Hello. 
`version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}`

**Comment by f41gh7** [comment]
It was surprising for me, but according to documentation of helm, it cannot render charts with `--dry-run`, if it contains crd. So, you have to install chart first.

 https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

**Comment by b-a-t** [comment]
Being newbie for all EKS/k8s/helm shebang I hit the same error following the instructions and got frustrated and stuck for quite a while, until risked to go farther despite the failure with `--dry-run`.

So please, add a note that for the initial run while CRDs are not created `--dry-run` have to be skipped.
