### ISSUE TITLE
bug: victoria-logs-single fails to start on Openshift

### ISSUE THREAD

**Issue by wiika** [VictoriaMetrics/helm-charts#1548]
**Chart name and version**
chart: victoria-logs-single
version: v0.6.4

**Describe the bug**
victoria-logs-single fails to start on Openshift ARO v4.13.40 (Kubernetes v1.26.14+731fb36), we see this in events:

create Pod victorialogs-victoria-logs-single-server-0 in StatefulSet victorialogs-victoria-logs-single-server failed error: pods "victorialogs-victoria-logs-single-server-0" is forbidden: unable to validate against any security context constraint: [..., provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{2000}: 2000 is not an allowed group, provider restricted-v2: .containers[0].runAsUser: Invalid value: 1000: must be in the ranges: [1000940000, 1000949999], ...] 
(some providers removed)

Probably serviceAccount, securityContext or similar is missing. 
victoria-metrics-single starts fine in same cluster.

**Custom values**
<none>

**Comment by AndrewChubatiuk** [comment]
hey @wiika 
currently helm charts do not support openshift, only vm operator has openshift packages. you can either install operator and use VLogs CR or as it's mentioned in an error you've posted you can override `podSecurityPolicy.fsGroup` and `podSecurityPolicy.runAsUser` in a chart

**Comment by AndrewChubatiuk** [comment]
alternatively you can set
```
global:
  compatibility:
    openshift:
      adaptSecurityContext: force
```
it should remove security context params, which are not supported by openshift

**Comment by wiika** [comment]
Hi @AndrewChubatiuk,

I tried the global parameter but that did not help. This is also mentioned in the readme for VictoraLogs helm chart at github so I find it a little strange that it is not supported. The same parameter works for the VictoriaMetrics helm chart.

Thanks anyway.

**Comment by AndrewChubatiuk** [comment]
thanks for reporting this, I've just found a bug in templates, will be fixed in the next release

**Comment by AndrewChubatiuk** [comment]
latest victoria-logs-single chart contains a fix for openshift

**Comment by wiika** [comment]
Tested now and it works :)

Thanks again!
