### ISSUE TITLE
feature:  ability to easily exclude vmstorage nodes from vminsert when using basic helm chart without VM operator

### ISSUE THREAD

**Issue by hartfordfive** [VictoriaMetrics/helm-charts#1549]
### Chart name and version, where you feel a lack of requested feature
chart: victoria-metrics-cluster
version: v0.11.8

### Is your feature request related to a problem? Please describe.
It appears there is no explicit method of exclude specific vmstorage nodes from vminsert when attempting to balance storage usage of new nodes (as the recommendation states [here](https://docs.victoriametrics.com/cluster-victoriametrics/?highlight=url%20format#cluster-resizing-and-scalability)) via helm chart configuration values when not using the operator resources?   From my initial investigation, I believe I’ve found that you can set `suppressStorageFQDNsRender: true` and then pass the list of storage nodes manually via the extraArgs config  (as described [here](https://github.com/VictoriaMetrics/helm-charts/issues/58)) but unfortunately this becomes very messy when you have many storage nodes  with only a small subset to exclude.

### Describe the solution you'd like
A simple built-in open in the helm chart to exclude specific vmstorage nodes from the configured list in vminsert when using the basic chart which does not user the operator.

**Comment by AndrewChubatiuk** [comment]
latest released chart contains `vminsert.excludeStorageIDs` slice which accepts storage integer ids, which are expected to be excluded from vminsert's list
