### ISSUE TITLE
[Cluster] .Values.rbac is not used

### ISSUE THREAD

**Issue by aqeelat** [VictoriaMetrics/helm-charts#1554]
I think usage of these lines was removed in #1225. They can be safely removed.
https://github.com/VictoriaMetrics/helm-charts/blob/9474517b6a4646147ce976ab5412867728ebe882/charts/victoria-metrics-cluster/values.yaml#L26-L54

**Comment by AndrewChubatiuk** [comment]
Thanks for an issue, updated a code base
