### ISSUE TITLE
feature: Ability to disable Grafana dashboards

### ISSUE THREAD

**Issue by filipbnkd** [VictoriaMetrics/helm-charts#1564]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: 0.27.0

**Is your feature request related to a problem? Please describe.**

I would like to configure which Grafana dashboards will be included in the output of helm template.  
I've set `defaultDashboardsEnabled: true` and majority of dashboards is properly created/not created based on the conditions generated by the hack script.  
But, I'm not able to remove `grafana-overview`, `alertmanager-overview` and `victoriametrics-backupmanager` dashboards.  I'm not using Grafana, Alertmanager nor VM Backupmanager in my deployment. 
Mentioned dashboards have `condition` set to `true` in the generated file. 
- https://github.com/VictoriaMetrics/helm-charts/blob/7f5a2c00b14c2c088d7d8d8bcee7a440a5ff11c6/charts/victoria-metrics-k8s-stack/files/dashboards/generated/victoriametrics-backupmanager.yaml#L44
- https://github.com/VictoriaMetrics/helm-charts/blob/7f5a2c00b14c2c088d7d8d8bcee7a440a5ff11c6/charts/victoria-metrics-k8s-stack/files/dashboards/generated/grafana-overview.yaml#L15
- https://github.com/VictoriaMetrics/helm-charts/blob/7f5a2c00b14c2c088d7d8d8bcee7a440a5ff11c6/charts/victoria-metrics-k8s-stack/files/dashboards/generated/alertmanager-overview.yaml#L5

I think combination of `condition` being set to `true` in the generated files and this [condition](https://github.com/VictoriaMetrics/helm-charts/blob/7f5a2c00b14c2c088d7d8d8bcee7a440a5ff11c6/charts/victoria-metrics-k8s-stack/templates/grafana/dashboard.yaml#L27) in the helm template is the issue. 

**Describe the solution you'd like**

Any solution which allows user to control which dashboards are created.
One of the solutions could be to invert order of the condition, and to first check if there is specific override in the `(dig $dashboardName false $.Values.dashboards)`. 
Other solution could be to set proper `condition` instead of setting `condition` to `true`.

**Comment by AndrewChubatiuk** [comment]
available in 0.27.1
