### ISSUE TITLE
Add multiple -remoteWrite.label args

### ISSUE THREAD

**Issue by rakesh-von** [VictoriaMetrics/helm-charts#157]
Hi, 

I would like to add multiple ***-remoteWrite.label*** args like the example below but the present **extraArgs** only takes one arg of ***-remoteWrite.label*** as it is a dictionary type. could you please review my PR which i believe i have fixed it https://github.com/VictoriaMetrics/helm-charts/pull/156?

```
-remoteWrite.label=agent_region=eu-west-1
-remoteWrite.label=agent_cluster=my_prod_cluster
```

**Comment by f41gh7** [comment]
Hello, you can add any number of args to the array flags separated by comma:

```
-remoteWrite.label=agent_region=eu-west-1,agent_cluster=my_prod_cluster
```

**Comment by rakesh-von** [comment]
thanks, closing this issue.
