### ISSUE TITLE
webhook requests should be customizable

### ISSUE THREAD

**Issue by gecube** [VictoriaMetrics/helm-charts#1571]
https://github.com/VictoriaMetrics/helm-charts/blob/563182dbcf312e1fc57f01735c0dcb92691194f3/charts/victoria-metrics-operator/templates/uninstall_hook.yaml#L37

Hi! No option to pass a proper requests/limits via `values.yaml`
In case I need it - need to work around with additional layers of patching via kustomize etc.

**Comment by AndrewChubatiuk** [comment]
release in 0.35.3
