### ISSUE TITLE
I tried to install Victoria metrics k8s stack on k8s, but failed

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/helm-charts#158]
1. Vmsingle cannot bind PVC, indicating that the storageclass is not set. But I didn't find that field at the end of the installation document.

2. Installation of grafana failed, report I nit:CrashLoopBackOff Wrong. I tried to describe and get yaml without detailed error information.

Here is the installation status:
```
monitor       vm-k8s-stack-grafana-56cd8ccfdd-xgbbl                             0/2     Init:CrashLoopBackOff   6          6m20s
monitor       vm-k8s-stack-kube-state-metrics-d9d8f49b6-rhqnk                   0/1     ImagePullBackOff        0          6m20s
monitor       vm-k8s-stack-prometheus-node-exporter-bfjjl                       1/1     Running                 0          6m20s
monitor       vm-k8s-stack-prometheus-node-exporter-c6bl6                       1/1     Running                 0          6m20s
monitor       vm-k8s-stack-prometheus-node-exporter-krr2w                       1/1     Running                 0          6m20s
monitor       vm-k8s-stack-prometheus-node-exporter-m9f7w                       1/1     Running                 0          6m20s
monitor       vm-k8s-stack-victoria-metrics-operator-5447559b8c-rqggl           1/1     Running                 0          6m20s
monitor       vmagent-vm-k8s-stack-victoria-metrics-k8s-stack-d785d5f55-6pp9h   2/2     Running                 0          6m
monitor       vmalert-vm-k8s-stack-victoria-metrics-k8s-stack-676957b6b-skw5c   2/2     Running                 0          6m
monitor       vmsingle-vm-k8s-stack-victoria-metrics-k8s-stack-54cdc8d67rg8jq   0/1     Pending                 0          6m
```

According to the installation document:

ATTENTION !!! Default values are inherited from helm charts declared as a dependency in the Chart.yaml file. If you want to change the default values that are inherited, access the documentation and the values.yaml file for each chart to understand the content and create a customized values.yaml file for your need.

I export and modify the values.yaml in the relevant chat, and then perform the following operations:
```
helm install vm-k8s-stack vm/victoria-metrics-k8s-stack -f k8s-stack-values.yaml -f kube-state-metrics-values.yaml \
 -f node-exporter-values.yaml -f stack-values.yaml -f vmagent-values.yaml -f vmalert-values.yaml -f vmauth-values.yaml \
 -f vmcluster-values.yaml -f vmsingle-values.yaml -n monitor
```

But the problem has not been solved

**Comment by vladimir4862** [comment]
Hi I'm not a member of Victoria team, but just a person passing by...
but maybe you got the manual wrong ?
in my case I didn't add individual files to the startup command, but simply redefined the values in the parent file
like this: 
https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart

**Comment by ktpktr0** [comment]
> Hi I'm not a member of Victoria team, but just a person passing by...
> but maybe you got the manual wrong ?
> in my case I didn't add individual files to the startup command, but simply redefined the values in the parent file
> like this:
> https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart


I've never used this feature, can you give me an example. Thank you

**Comment by vladimir4862** [comment]
Hmmm.. not sure how to explain more, in general you can see example by link.
and maybe this will help you too but not sure:

for example you want to pass admin password for grafana
just put this line
https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L323
after this (under "grafana:" )
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L347

so in general just put any values from velues.yaml from grafana chart under "grafana:" in vm chart.

**Comment by ktpktr0** [comment]
@vladimir4862  Thank you for your example. I understand. In the chart.yaml file, you can use the values.yaml option. That is, add the option of child chart to the child chart part of values.yaml of parent chat (victoria-metrics-k8s-stack).

But I am in the operator of the child chart, I did not find the storageclass option, so vmsingle will report the error that the storageclass is not set

**Comment by vladimir4862** [comment]
@ktpktr0 
I'm terribly sorry if my comments seem useless, I'm just trying to help, but if I honestly can't say that I know this topic very well ;) 
about your specific problem...

> Vmsingle cannot bind PVC, indicating that the storageclass is not set. But I didn't find that field at the end of the installation document.
it works for me from the box... so could you show your config or something that can help to get error? 



so if you want to set storageclass name (i'm not sure if we talk about the same things, correct me if I'm wrong) 
let's try this: 
```
vmsingle:
  spec:
    storage:
      storageClassName: io1
```
https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmsinglespec
https://v1-17.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#persistentvolumeclaimspec-v1-core

And i'm pretty sure grafana doesn't work because there are two default ds. you can check this in grafana logs.

**Comment by ktpktr0** [comment]
@vladimir4862 My previous attempt is as like as two peas, but still storageclass is not set after running.

```
vmsingle:
  enabled: true
  # spec for VMSingle crd
  # https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmsinglespec
  spec:
    retentionPeriod: "14"
    replicaCount: 1
    storage:
      storageClassName: "prometheus-data-db"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
```

**Comment by vladimir4862** [comment]
@ktpktr0 
well... I'm not sure what wrong in your config ) 
it fully works for me. 
sorry that I can't help you here with this error. 

in my case: 
```
kNAME                                                                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS         AGE
vmsingle-vm-k8s                                                     Pending                                                                        prometheus-data-db   16m
```
`  Warning    ProvisioningFailed  103s (x63 over 16m)  persistentvolume-controller  storageclass.storage.k8s.io "prometheus-data-db" not found`
so i think the trouble in your fist message was resolved ;) 

>  indicating that the storageclass is not set. But I didn't find that field at the end of the installation document.

this config is changed storageclass
```
vmsingle:
  spec:
    storage:
      storageClassName: "anything"
```
maybe you need delete old pvc and run helm with single again

**Comment by ktpktr0** [comment]
@vladimir4862 

Thanks for your help, I updated k8s version, vmsingle set up the storage class successfully.

Now it's just grafana's I nit:CrashLoopBackOff , I check the details and sometimes prompt:

```
  Normal   Scheduled    <unknown>                                 Successfully assigned monitor/vm-k8s-stack-grafana-6d7d84d7fb-gv4r7 to k8s-node2
  Warning  FailedMount  4m34s                 kubelet, k8s-node2  MountVolume.SetUp failed for volume "sc-dashboard-provider" : failed to sync configmap cache: timed out waiting for the condition
  Warning  FailedMount  4m34s                 kubelet, k8s-node2  MountVolume.SetUp failed for volume "config" : failed to sync configmap cache: timed out waiting for the condition
  Warning  BackOff      2m3s (x7 over 4m24s)  kubelet, k8s-node2  Back-off restarting failed container
  Normal   Pulled       112s (x5 over 4m32s)  kubelet, k8s-node2  Container image "curlimages/curl:7.73.0" already present on machine
  Normal   Created      112s (x5 over 4m32s)  kubelet, k8s-node2  Created container download-dashboards
  Normal   Started      112s (x5 over 4m31s)  kubelet, k8s-node2  Started container download-dashboards
```

**Comment by vladimir4862** [comment]
@ktpktr0 

hm.. interesting... 
If i was you i'd check this line: 
`failed to sync configmap cache: timed out waiting for the con`
check configmap (are they exist? )
check all containers logs in grafana pod.

**Comment by ktpktr0** [comment]
It's almost never going to happen, and now it's working. The container is not accessible due to my local network https://raw.githubusercontent.com I'm not sure.
