### ISSUE TITLE
feature: Add some dashboards and rules to victoria-logs-single chart

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1590]

**Comment by AndrewChubatiuk** [comment]
hey @maxpain 
regarding dashboards your request sounds reasonable as it can be provided as a configmap, but how are you going to use rules and which format do you expect?

**Comment by AndrewChubatiuk** [comment]
available in 0.7.0

**Comment by maxpain** [comment]
@AndrewChubatiuk, could you please enable `grafana_dashboard: "1"` by default in the ConfigMap with the dashboard JSON file?
