### ISSUE TITLE
feature: Add PodMonitor, rules and grafana dashboards for fluent-bit in victoria-logs-single chart

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1591]

**Comment by AndrewChubatiuk** [comment]
victoria-logs-single chart includes fluent-bit chart, which already contains servicemonitor, which can be enabled using `fluent-bit.serviceMonitor.enabled: true` option and a dashboard, which can be included using `fluent-bit.dashboards.enabled: true`
