### ISSUE TITLE
When deploying to k8s - there are excessise DNS requests.

### ISSUE THREAD

**Issue by gecube** [VictoriaMetrics/helm-charts#1626]
Good day!

The frest installation EKS + latest victoria k8s metrics stack.

In parallel the coroot solution is installed.

I am observing the next

![telegram-cloud-photo-size-2-5242590837488084421-y](https://github.com/user-attachments/assets/a08e27f1-d76b-46ee-80eb-8e85d4db844a)

It is the excessive DNS requests from victoria metrics agent to different non-existing domain names in the cluster like:

- `vmsingle-victoria-metrics-k8s-stack.monitoring-system.svc.svc.cluster.local`
- `vmsingle-victoria-metrics-k8s-stack.monitoring-system.svc.monitoring-system.svc.cluster.local`

I am asking to improve the default settings of agent to point to `vmsingle-victoria-metrics-k8s-stack.monitoring-system.svc.cluster.local.` (with dot on the end) effectively eliminating extra DNS requests. Probably it is the best solution. The only drawback that then we need to put a cluster TLD (`cluster.local`) as a value in helm chart. But it is ok for many operators (FluxCD, altinity operator and others have the same setting).

**Comment by AndrewChubatiuk** [comment]
will be fixed as soon as https://github.com/VictoriaMetrics/helm-charts/issues/1455 is fixed

**Comment by AndrewChubatiuk** [comment]
starting v0.28.1 it's possible to set `global.cluster.dnsDomain: cluster.local.` and this suffix will be added to all addresses

**Comment by AndrewChubatiuk** [comment]
`global.cluster.dnsDomain` is set to `cluster.local.` by default in all charts
