### ISSUE TITLE
bug: Using helm `crds` dir prevents additional crds in the future

### ISSUE THREAD

**Issue by andrewdinunzio** [VictoriaMetrics/helm-charts#1640]
**Chart name and version**
victoria-metrics-operator-0.36.0

**Describe the bug**
This is only applicable for when `crds.plain=true`.

If using helm's `crds` directory, any CRDs included are essentially permanent. You can't add new CRDs or even new versions of CRDs, and you cannot remove any.

I believe the reasoning is that helm has to be able to support rollbacks, and they don't want any possibility of data loss, which could happen if custom resources are created using new/updated CRDs, then a rollback occurs and deletes those CRDs (which transitively deletes those custom resources which used them).

This behavior doesn't happen if the crds are added as templates instead (with the caveat that there is an issue with a stale discovery cache which can cause the first install to fail if you have both CRDs and instances of those CRDs in the same chart). This is why it works when `crds.plain=false`.

```bash
minikube start
cd charts/victoria-metrics-operator
helm dep up
helm upgrade --install victoria-metrics-operator . --set crds.plain=true
# add a new CRD or a new version of an existing CRD
# ...
helm dep up
helm upgrade --install victoria-metrics-operator . --set crds.plain=true
kubectl get crds # notice the new CRD is not applied
```

**Comment by AndrewChubatiuk** [comment]
hey @andrewdinunzio 
this behaviour is expected and required to keep VM CRDs in one place (before static CRDs were in k8s-stack chart and template was in operator chart). By default `crds.plain: false` (`crds.plain: true` in k8s-stack chart) so there should be no issues.

**Comment by andrewdinunzio** [comment]
I see, I can close this issue then. I'm curious what the upgrade strategy looks like for cases where people use `crds.plain=true`. From what I can tell, it would require some manual intervention.

**Comment by AndrewChubatiuk** [comment]
yes, manual upgrade is required in this case. It's mentioned in k8s-stack chart docs, so we'll probably copy them to operator chart as well
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack#upgrade-guide
