### ISSUE TITLE
Helm value to customize PVC name in victoria-logs-single chart

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1646]

**Comment by AndrewChubatiuk** [comment]
hey @maxpain 
you can create your own PVC and use `server.persistentVolume.existingClaim` to override default one

**Comment by maxpain** [comment]
@AndrewChubatiuk but VM Operator, for example, allows customization of any PVC

**Comment by AndrewChubatiuk** [comment]
do you need to override deployment pvc name?
