### ISSUE TITLE
extraArgs without value

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/helm-charts#165]
Hi! Thanks for your chart, it really awesome! 
How arguments without value should be passed to container? for example `-remoteWrite.showURL` for vmagent.
there is no value in this case, but I see no `list` like structure In a chart:
```
          {{- range $key, $value := .Values.extraArgs }}
            - -{{ $key }}={{ $value }}
          {{- end }}
```
[link](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/templates/statefulset.yaml#L52) to the line

**Comment by f41gh7** [comment]
Flags without values are usually boolean.

 So you can use it like:

```
extraArgs:
  remoteWrite.showURL: "true"
```

**Comment by Vladikamira** [comment]
oh, nice! it wasn't obvious for me..
thanks for help, I'm closing issue
