### ISSUE TITLE
bug: fullnameOverride is not used

### ISSUE THREAD

**Issue by grdq** [VictoriaMetrics/helm-charts#1653]
**Chart name and version**
chart: victoria-metrics-cluster
version: v0.14.6

**Describe the bug**

I am upgrading from v0.11.18. One difference I have noticed is for my vmselect, vminsert, and vmstorage pods where in my values I have previously set a fullnameOverride for each one of this:

  vmselect:
    fullnameOverride: vmselect

  vminsert:
    fullnameOverride: vminsert

  vmstorage:
    fullnameOverride: vmstorage  
 
This seems to no longer be respected, and the svc, deployment, sts name seems to follow this format:

{argocd.argoproj.io/instance}-{chart_name}-{vmselect/vminsert/vmstorage}

So if I am deploying this chart via an ArgoCD app called victoria-metrics-prod-eu then the sts, svc, and deployment, and therefore pod has an example name of:

victoria-metrics-prod-eu-victoria-metrics-cluster-vmstorage

instead of using the fullnameOverride like it did on the previous chart version I was using. 

Has logic change in when it uses fullnameOverride in this time? Or is this not an issue you are seeing your end?

**Comment by AndrewChubatiuk** [comment]
hey @grdq 
this issue was addressed in v0.14.7
