### ISSUE TITLE
[victoria-metrics-k8s-stack] Don't drop uid label

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1656]
Hello. https://coroot.com/ uses `uid` label from `kube-state-metrics`.
Would you mind not dropping this label in the `victoria-metrics-k8s-stack` chart?
I know I can overwrite it in helm values, but I don't think this label increases cardinality.

https://github.com/coroot/coroot/issues/177

**Comment by AndrewChubatiuk** [comment]
Hey @maxpain 
this label doesn't make any sense for most of setups, please override default params if you want to keep it
