### ISSUE TITLE
[victoria-logs-single] feature: Use yaml config format instead of classic in fluentbit

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1659]
https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/yaml/configuration-file

**Comment by AndrewChubatiuk** [comment]
depends on https://github.com/fluent/helm-charts/pull/558

**Comment by AndrewChubatiuk** [comment]
alternatively we could switch to vector instead of fluent-bit

**Comment by ABWassim** [comment]
https://github.com/fluent/fluent-bit/pull/9513 feature was merged and planned for 3.2.0, working back on this :)

**Comment by AndrewChubatiuk** [comment]
thanks @ABWassim :)
