### ISSUE TITLE
parameter to choose different scrape file for vmagent

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/helm-charts#167]
Is it possible to add value to choosing a scrape config file for `vmagent`? Or there is another way around
```
          args:
            - -promscrape.config=/config/scrape.yml
            - -remoteWrite.tmpDataPath=/tmpData
```

**Comment by f41gh7** [comment]
Possible workaround for now add needed option to the `extraArgs` configuration:

https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L66

 For scrape config:

```yaml
extraArgs:
  promscrape.config: /some-custom-path
```

 It will produce deployment:

```yaml
args:
            - -promscrape.config=/config/scrape.yml
            - -remoteWrite.tmpDataPath=/tmpData
            - -promscrape.config=/some-custom-path
 ``` 

 And `vmagent` must use the latest arg value.

**Comment by Vladikamira** [comment]
yep, it works! Thanks 🙏
