### ISSUE TITLE
bug: Chart still tries to use SA even when create set to false

### ISSUE THREAD

**Issue by grdq** [VictoriaMetrics/helm-charts#1683]
**Chart name and version**
chart: victoria-metrics-cluster
version: v0.14.7

**Describe the bug**
When upgrading from v0.11.18, my vminsert, vmselect, and vmstorage deployment/statefulsets now seemingly attempt to use a service account of a matching name. In my values I set `serviceAccount:
    create: false` and it previously was never an issue. 
    
Example error:

`create Pod vmstorage-0 in StatefulSet vmstorage failed error: pods "vmstorage-0" is forbidden: error looking up service account victoria-metrics-development/vmstorage: serviceaccount "vmstorage" not found`

Has logic change where even with create set to false it will still try and use a service account? 

Cheers

**Comment by AndrewChubatiuk** [comment]
thanks for an issue. 0.14.8 contains a fix

**Comment by AndrewChubatiuk** [comment]
these charts were fixed too, but not yet released

**Comment by AndrewChubatiuk** [comment]
latest vmsingle and vmagent charts contain this fix
