### ISSUE TITLE
bug: extraLabels not setting deployment metadata labels

### ISSUE THREAD

**Issue by grdq** [VictoriaMetrics/helm-charts#1687]
**Chart name and version**
chart: victoria-metrics-auth
version: v0.7.4

**Describe the bug**
Hi,

I am trying to set a label on the vmauth deployment (under the template:, metadata:, labels: structure) by using extraLabels, it doesn't look to actually be setting this when I look at the deployment. Is it intended that extraLabels will allow me to add labels to [this ](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-auth/templates/deployment.yaml#L21C30-L21C44) section?

Thanks!

**Comment by AndrewChubatiuk** [comment]
in the latest chart pod labels are configurable via `podLabels` parameter
