### ISSUE TITLE
[victoria-logs-single] feature: Add support for additional message fields in json

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1695]
Hello.

Currently, only `_msg` field is supported:

<img width="1057" alt="image" src="https://github.com/user-attachments/assets/4109a128-1a5c-4572-916a-582db8926042">

Many applications use `msg` and `message` fields, so it would be cool to add them as well.

**Comment by AndrewChubatiuk** [comment]
available in 0.7.3
