### ISSUE TITLE
bug: vmsingle scrape configMap not using configured configmap name

### ISSUE THREAD

**Issue by grdq** [VictoriaMetrics/helm-charts#1700]
**Chart name and version**
chart: victoria-metrics-single
version: v0.12.5

**Describe the bug**
When using the scrape configMap feature, I pass the following:

    scrape:
      enabled: true
      configMap: vmsingle-scrape
      
This used to work in v0.9.21, but now it looks like the pod is trying to find a configmap called `vmsingle-scrapeconfig`, instead of the one I have declared (and matches the actual name of the configmap in my namespace).

I tested updating the configmap to now be called` vmsingle-scrapeconfig`, along with updating the configMap value to point to `vmsingle-scrapeconfig` as well and that did allow it to mount, so I can get it to work using a small inconsequential tweak, but it differs from the logic I expected.

Cheers

**Comment by AndrewChubatiuk** [comment]
hey @grdq 
thanks for an issue. 0.12.6 contains a fix
