### ISSUE TITLE
[victoria-logs-single] feature: Put all parsed json fields to "jsonPayload" object

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1708]
Hello.

Currently, it's hard to find parsed JSON fields among lot other labels:

![telegram-cloud-document-2-5290015298978602003](https://github.com/user-attachments/assets/3883d4fd-7b5c-435b-b475-560985fc0557)

I propose to put all the parsed JSON fields to `jsonPayload` object instead, like in Google Cloud Logging:
![telegram-cloud-photo-size-2-5290015299434832854-y](https://github.com/user-attachments/assets/2eaf5183-bd39-4475-8fad-858850c54e03)

**Comment by AndrewChubatiuk** [comment]
starting 0.8.0 all json parsed data is nested under a `log` key
