### ISSUE TITLE
[victoria-logs-single] feature: Add kernel logs collection

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1711]
I think it's a good idea to collect kernel logs by default.

https://docs.fluentbit.io/manual/pipeline/inputs/kernel-logs

**Comment by AndrewChubatiuk** [comment]
starting 0.8.0 we've considered migrating from fluent-bit to vector to allow users to manage all arguments without doing changes in victoria-logs-single chart, also it reduced amount of configuration

**Comment by maxpain** [comment]
@AndrewChubatiuk I propose configuring the log collector to collect kernel logs by default, I think it's a good idea.

**Comment by AndrewChubatiuk** [comment]
main idea of log aggregation agent in victoria-logs-single chart is to provide a starting point for users with a default configuration that just works
