### ISSUE TITLE
[victoria-logs-single] feature: PodMonitor, prometheus rules and Grafana dashboard for Vector

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#1721]
:D

**Comment by AndrewChubatiuk** [comment]
according to [docs](https://github.com/vectordotdev/helm-charts/tree/develop/charts/vector)
`vector.podMonitor.enabled: true` enables podmonitor
rules and dashboard are expected to be a part of victoria-logs-k8s-stack chart
