### ISSUE TITLE
vmagent sharding in victoria-metrics-agent helm chart

### ISSUE THREAD

**Issue by FRosner** [VictoriaMetrics/helm-charts#173]
Hey! Thanks for these amazing helm charts :)

https://docs.victoriametrics.com/vmagent.html#scraping-big-number-of-targets explains that you can configure vmagent to scale horizontally. I tried to figure out if this functionality could be achieved with the current version of https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-agent but I couldn't find any documentation on that.

If it's not possible but you think it can be done, could you provide a few hints on what would have to be changed to make it work?

Thanks!

**Comment by f41gh7** [comment]
Hello, 
  It can be achieved with multiple installations of vmagent`s helm chart. Provide needed sharding config to each chart installation for example:
```bash
helm upgrade -i agent-shard-0 vm/victoria-metrics-agent --set 'extraArgs.promscrape\.cluster\.membersCount=2' --set 'extraArgs.promscrape\.cluster\.memberNum=0' --dry-run
helm upgrade -i agent-shard-1 vm/victoria-metrics-agent --set 'extraArgs.promscrape\.cluster\.membersCount=2' --set 'extraArgs.promscrape\.cluster\.memberNum=1' --dry-run
```

 For advanced automation, you may be interested in `VMAgent` CRD from operator - it supports sharding setup out of box:
https://github.com/VictoriaMetrics/operator/issues/177

**Comment by FRosner** [comment]
Thanks!
