### ISSUE TITLE
How do I work out the user / password for Grafana?

### ISSUE THREAD

**Issue by kaihendry** [VictoriaMetrics/helm-charts#176]
Is there a good forum to ask questions about:

https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack

Like what is the default admin user/password please? aka GF_SECURITY_ADMIN_PASSWORD

Thank you in advance,

**Comment by f41gh7** [comment]
Hello, by default, its randomly generated. It can be retrieved by kubectl get secret. Helper message must be printed after chart install. 
 
 It should be 
```
# helm release name = stack, installed namespace = default.
kubectl get secret --namespace default stack-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo
```
