### ISSUE TITLE
bug: victoria-metrics-agent 0.14.7 - image.Tag overrride not respected in labels

### ISSUE THREAD

**Issue by vhajdukd** [VictoriaMetrics/helm-charts#1766]
**Chart name and version**
chart: victoria-metrics-agent
version: v0.14.7

**Describe the bug**
This only an issue in version tracking via labels, but image.tag effectively overrides the version of the application we are running.
Setting it currently does not override version labels:

`app.kubernetes.io/version: v1.106.0`

**Custom values**
```yaml
image:
  tag: v1.105.0
```

This is a minor.

**Comment by AndrewChubatiuk** [comment]
available in 0.14.9
