### ISSUE TITLE
bug: vmcluster name can no longer be overridden

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1778]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.4

**Describe the bug**
The VMCluster CR is now using the fullname from the Chart instead of what is defined in values.vmcluster.name

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmcluster:
  name: my-custom-name
```

**Comment by AndrewChubatiuk** [comment]
thanks for an issue
fix is expected in a next release
