### ISSUE TITLE
feature: Update operator version in victoria-metrics-k8s-stack 

### ISSUE THREAD

**Issue by tropnikovvl** [VictoriaMetrics/helm-charts#1792]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: 0.28.4

**Is your feature request related to a problem? Please describe.**
It would be great to update the version of the operator in this Helm chart dependency. This update will allow disabling the generation and deployment of the CRD during the stack deployment.

[victoria-metrics-operator-0.38.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-operator-0.38.0)
`added back crds.enabled: false option, which disables CRD creation, but due to limitation of dependencies condition it allows to disable only in combination with crds.plain: false`

**Describe the solution you'd like**
Update operator version in dependency.

**Comment by AndrewChubatiuk** [comment]
hey @tropnikovvl 
cannot update it now as current master already contains a new CRD version
dependency will be upgraded after operator app version upgrade

**Comment by tropnikovvl** [comment]
Hi @AndrewChubatiuk,
Thanks for the info, do you have any ETA?

**Comment by AndrewChubatiuk** [comment]
hopefully during the next week

**Comment by AndrewChubatiuk** [comment]
hey @tropnikovvl 
it's available in 0.29.0
