### ISSUE TITLE
bug: image.tag leads to invalid manifests when using sha pinning

### ISSUE THREAD

**Issue by jonas-switala** [VictoriaMetrics/helm-charts#1801]
**Chart name and version**
chart: victoria-metrics-operator
version: v0.39.0

**Describe the bug**
The fix of  https://github.com/VictoriaMetrics/helm-charts/issues/1766 in v0.39.0 leads to invalid labels in the generated manifest when using sha-pinned container image tags.

There seem to be two problems:
1) the label value exceeds 63 characters
2) the label value may not contain '@'

**Example error message** (in this case from argocd but the problem should also apply to using helm directly):
```
Failed sync attempt to 7edc1fa4a6f0884087fbfb380415137111bc0403: one or more objects failed to apply, reason: error when patching "/dev/shm/320363685": CustomResourceDefinition.apiextensions.k8s.io "vmprobes.operator.victoriametrics.com" is invalid: [metadata.labels: Invalid value: "v0.50.0@sha256:b89187c33de771117a67dfe839119722713ca18ef3db53f843ae662d39e19c29": must be no more than 63 characters, metadata.labels: Invalid value: "v0.50.0@sha256:b89187c33de771117a67dfe839119722713ca18ef3db53f843ae662d39e19c29": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue', or 'my_value', or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')],
```

**Custom values**
```yaml
image:
  # -- Image tag
  tag: v0.50.0@sha256:b89187c33de771117a67dfe839119722713ca18ef3db53f843ae662d39e19c29
```

**suggested fix**
The simplest way to fix this would be to strip the `@sha` part from the tag in version labels.  
Some other charts (example: [cloudnative-pg](https://github.com/cloudnative-pg/charts/blob/2ee4e01597d46fcbb815242a1b438463660b13a8/charts/cloudnative-pg/templates/_helpers.tpl#L40)) use a separate AppVersion variable for this. I wouldn't recommend that approach since it could result in a potential mismatch of versions again.

**Comment by AndrewChubatiuk** [comment]
fixed in 0.39.1
