### ISSUE TITLE
bug: DiskRunsOutOfSpace alert does not work

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1809]
**Chart name and version**
chart: victoria-metrics-k8s-stack
version: v0.28.3

**Describe the bug**
As defined `DiskRunsOutOfSpace` will never fire if following the recommendation for `storage.minFreeDiskSpaceBytes` to be at least 20%

**Custom values**

**Comment by dctrwatson** [comment]
> hey @dctrwatson do you expect alert threshold to be connected to `storage.minFreeDiskSpaceBytes` value?

I think so. That way it would work if you set it to 20% or even 35%.

I'm not sure how you could that in Helm though. We purposely set that flag to be an integer so that we can use `label_value(flag{job=~"vmstorage-.*", name="retentionPeriod"}, "value") * 31d` for a capacity alert.

**Comment by lieberlois** [comment]
I don't have the same issue, but as an idea: I think it would adding the PVC Dashboard from the kube-prometheus-stack to the VictoriaMetrics dashboards by default would help a lot with analyzing such alerts

**Comment by AndrewChubatiuk** [comment]
@dctrwatson 
in 0.30.1 added `NodeBecomesReadonlyIn3Days` alert, which should notify, when storage becomes read-only in 3 days
