### ISSUE TITLE
feature: not all alerts have clusterLabel

### ISSUE THREAD

**Issue by dctrwatson** [VictoriaMetrics/helm-charts#1815]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.28.3

**Is your feature request related to a problem? Please describe.**
We use `global.clusterLabel` for some alert routing rules. Not all alerts emit this label. So the alerts are routed to our fallback instead.

For example:
- `LogErrors`
- `TooHighChurnRate24h`

**Describe the solution you'd like**
All alerts and recording rules that utilize aggregations to emit `global.clusterLabel`

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by AndrewChubatiuk** [comment]
in 0.30.2 cluster labels were added to all alerts, that are maintained by VM team
