### ISSUE TITLE
[victoria-metrics-k8s-stack] feature: Pull VM images from private registry

### ISSUE THREAD

**Issue by yukha-dw** [VictoriaMetrics/helm-charts#1850]
**Chart name and version, where you feel a lack of requested feature**
chart: victoria-metrics-k8s-stack
version: v0.30.2

**Is your feature request related to a problem? Please describe.**
I want to clone victoriametrics images such as `victoriametrics/vmagent` to private registry, but currently there's no option to do so from `victoria-metrics-k8s-stack`

**Describe the solution you'd like**
It'd be great if all VM CRDs support common image properties like `registry`.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by yukha-dw** [comment]
Nevermind, I've just rechecked the template
https://github.com/VictoriaMetrics/helm-charts/blob/f502b626a986c22ab6bf68f1df4b39a67dfcdaf4/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L153

**Comment by AndrewChubatiuk** [comment]
hey @yukha-dw 
operator supports `VM_CONTAINERREGISTRY` environment variable, which allows to override default registry to all managed CRs
https://docs.victoriametrics.com/operator/vars/
in k8s-stack chart you can override it using
```
victoria-metrics-operator:
   env:
      - name: VM_CONTAINERREGISTRY
         value: your-registry.io
```
