### ISSUE TITLE
victoria-metrics-cluster: does not have persistentVolume.existingClaim option

### ISSUE THREAD

**Issue by jgournet** [VictoriaMetrics/helm-charts#187]
Option is missing to use an existing PVC
=> is it possible to add it please ?

also: in volumeClaimTemplates, is it possible to add a "volumeName" so it can use an existing volume ?

**Comment by jgournet** [comment]
Created https://github.com/VictoriaMetrics/helm-charts/pull/188 for this issue

**Comment by f41gh7** [comment]
Thanks, pr was merged, will be released soon.

**Comment by taintedkernel** [comment]
I noticed this needed to be solved in the single-node version as well so I drafted https://github.com/VictoriaMetrics/helm-charts/pull/212
