### ISSUE TITLE
bug: victoria-metrics-common: wrong type assumptions for value `($spec.extraArgs).tls`

### ISSUE THREAD

**Issue by psmolkin** [VictoriaMetrics/helm-charts#1874]
**Chart name and version**
chart: victoria-metrics-common
version: 0.0.34

**Describe the bug**
Relates to https://github.com/VictoriaMetrics/helm-charts/issues/1449
Error caused by a wrong assumption about the type of a variable
`victoria-metrics-common/templates/_service.tpl`:
[line 49](https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-common-0.0.34/charts/victoria-metrics-common/templates/_service.tpl#L49C38-L49C42)
and
[line 79](https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-common-0.0.34/charts/victoria-metrics-common/templates/_service.tpl#L79C38-L79C42)
```tpl
    {{- $isSecure = ($spec.extraArgs).tls | default $isSecure -}} # Changes $isSecure type to String if tls=="true"
    {{- $port = (ternary 443 80 $isSecure) -}} # Error here
```

The `extraArgs` field is type of `object (keys:string, values:string)`:
see [extraArgs](https://docs.victoriametrics.com/operator/api/index.html#vminsert) at `VMClusterSpec.VMInsert`

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
vmcluster:
  enabled: true
  spec:
    vminsert:
      extraArgs:
        tls: "true"
```

**Comment by psmolkin** [comment]
It looks like the same mistake was made here:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-common/templates/_pod.tpl#L78

**Comment by AndrewChubatiuk** [comment]
0.31.2 should contain a fix

**Comment by psmolkin** [comment]
Thank you, it works now
