### ISSUE TITLE
k8s-stack/feature: ability to disable k8s resources alerts

### ISSUE THREAD

**Issue by zekker6** [VictoriaMetrics/helm-charts#1880]
**Chart name and version, where you feel a lack of requested feature**
chart: k8s-stack

**Is your feature request related to a problem? Please describe.**

Currently, it is not possible to disable resource based alerts for k8s as it uses `condition: '{{ true }}'`. 
https://github.com/VictoriaMetrics/helm-charts/blob/b1d8087e104866fc453224fd9bf3125356513d7e/charts/victoria-metrics-k8s-stack/files/rules/generated/k8s.rules.container_cpu_limits.yaml#L5

In my use-case there is a separate k8s platform monitoring present in cluster, vm-k8s-stack is used in order to deploy VM/Grafana and monitoring for the applications running there. It is not monitoring k8s itself.

**Describe the solution you'd like**
I'd like to have an option to disable these rules.

**Describe alternatives you've considered**
The only option currently is to just ignore these rules since there is no matching metrics anyway.

**Comment by AndrewChubatiuk** [comment]
have you tried to set `defaultRules.groups.<camelCaseGroupName>create: false`?

**Comment by zekker6** [comment]
> have you tried to set defaultRules.groups.<camelCaseGroupName>.create: false?

I did try setting this, but this did not work. I've just tested with latest chart version and values from repo, and it seems to be working just fine. So this must be an issue with the configuration itself, not the chart.

Thanks for help, closing this as resolved than.
