### ISSUE TITLE
bug: global.image.registry does not working in victoria-metrics-operator

### ISSUE THREAD

**Issue by sergeypugachov** [VictoriaMetrics/helm-charts#1898]
**Chart name and version**
chart: victoria-metrics-operator
version: latest

**Describe the bug**
According to documentation and #818 global.image.registry should overwrite default registry. But it's not working.

To reproduce:
```
helm template vmoperator vm/victoria-metrics-operator --set global.image.registry=your.registry | grep -i "your.registry"
```
 It will find nothing in rendered yaml.

**Custom values**
Please provide only custom values (excluding default ones):
```yaml
global:
  image:
    registry: your.registry
```

**Comment by AndrewChubatiuk** [comment]
thanks for submitting an issue
fix is expected in the next release

**Comment by AndrewChubatiuk** [comment]
already available in a latest operator
