### ISSUE TITLE
Error installing vm-operator crd's

### ISSUE THREAD

**Issue by cesarmira** [VictoriaMetrics/helm-charts#199]
Hi,

I'm getting this error while trying to install the vm-operator crd: 

`helm install victoria-metrics vm/victoria-metrics-cluster -f values.yaml -n monitoring`
`
Error: unable to build kubernetes objects from release manifest: SchemaError(com.victoriametrics.operator.v1beta1.VMAlertmanagerConfig.spec.route.routes): array should have exactly one sub-item
`

We are running eks 1.17. Any ideas on how to fix it? I've tried installing this crds using flux, helm but with the same result.

Thanks

**Comment by f41gh7** [comment]
It looks like kubernetes issue, investigating it.
 
 Temprorary workaround - use legacy CRD version:

 ```bash
kubectl delete crd vmalertmanagerconfigs.operator.victoriametrics.com
helm upgrade -i operator vm/victoria-metrics-operator --set useLegacyCRD=true
```

**Comment by f41gh7** [comment]
Must be fixed at operators chart `0.2.2`

**Comment by arctan90** [comment]
the same error comes to me, while installing vmoperator by "helm install".
File:  templates/crd.yaml
`
   4290                   routes:
   4291                     description: Child routes.
   4292                     items:
   4293                       x-kubernetes-preserve-unknown-fields: true
   4294                     type: array
   4295                     x-kubernetes-preserve-unknown-fields: true
`
line 4295 introduces this error

**Comment by f41gh7** [comment]
Hello, can you try new version?
```
vm/victoria-metrics-operator                      	0.2.3        	0.18.2
```

**Comment by arctan90** [comment]
it works, thank you so much.

> Hello, can you try new version?
> 
> ```
> vm/victoria-metrics-operator                      	0.2.3        	0.18.2
> ```
