### ISSUE TITLE
regression introduced by #197

### ISSUE THREAD

**Issue by transacid** [VictoriaMetrics/helm-charts#204]
since #197 the node-exporter VMServiceScrape uses a label that is not provided by the [helm chart ](https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/templates/service.yaml#L10) and _has_ to be set via values. unless one sets `app.kubernetes.io/instance` the node-exporter will never get scraped because the label is not set by the chart and `matchLabels` is AND and not OR. previously `release` was used which was set by the chart.

**Comment by f41gh7** [comment]
Must be fixed at the latest chart version

**Comment by transacid** [comment]
cool that works. thank you!
