### ISSUE TITLE
kubeDns not supported?

### ISSUE THREAD

**Issue by alaricljs** [VictoriaMetrics/helm-charts#206]
Seems like you copy/pasted the coreDns values stanza from kube-prometheus-stack.  According to the comment: https://github.com/VictoriaMetrics/helm-charts/blob/fa853d21613b1f479c14a50b5996fd467a6d9e63/charts/victoria-metrics-k8s-stack/values.yaml#L740

There should be a kubeDns section, however it's not there.  Is there a reason to not support kubeDns, or can that get added in?

**Comment by f41gh7** [comment]
Was added at the latest chart version
