### ISSUE TITLE
victoria-metrics-single: add config support for relabelConfig

### ISSUE THREAD

**Issue by belm0** [VictoriaMetrics/helm-charts#207]
the chart values should support a global relabel config for ingested metrics, similar to the `scrape` variable (generating a configMap, etc.)

https://docs.victoriametrics.com/#relabeling

currently we're using `--relabelConfig` and a separately deployed file, but I'd like a coherent deployment including a configMap for relabel config

(Note that the victoria-metrics-agent chart supports relabel configmap, but victoria-metrics-single does not.)

**Comment by AndrewChubatiuk** [comment]
global relabel config setting is available in release [0.11.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-single-0.11.0)
