### ISSUE TITLE
Repository is broken

### ISSUE THREAD

**Issue by NaPs** [VictoriaMetrics/helm-charts#22]
Links to the packages in the index.yaml manifest are broken (eg: https://victoriametrics.github.io/helm-charts/packages/victoria-metrics-single-0.0.6.tgz).

The chart can't be installed using the repository.

Thank you!
Antoine

**Comment by NaPs** [comment]
Note (after looking at the problem): I do not recommend to store the binary packages into the git repository itself.

You can use https://github.com/helm/chart-releaser to create releases on the GH project for each chart version. Each release can store the binary packages for a version. Also, if you want to use GH Actions to run this automatically, you can use this: https://github.com/helm/chart-releaser-action.

Hope it helps, I can provide support if needed.

Antoine

**Comment by valyala** [comment]
> Links to the packages in the index.yaml manifest are broken

oops, this was my fault. Added missing binary packages at 563e96ee693a285c5f35daad11a126b2b2a8580f .

> You can use https://github.com/helm/chart-releaser to create releases on the GH project for each chart version. Each release store the binary packages for a version. Also, if you want to use GH Actions to run this automatically, you can use this: https://github.com/helm/chart-releaser-action.

@tenmozes , could you look into this?

**Comment by NaPs** [comment]
Now working, thank you! :-)
