### ISSUE TITLE
Pod "CrashLoopBackOff" after upgrade to 1.66.2

### ISSUE THREAD

**Issue by pollynesterovich** [VictoriaMetrics/helm-charts#221]
After trying to upgrade vmagent from version 1.63.0 to 1.66.2, the pod crashes constantly "CrashLoopBackOff". There are no errors in the logs, the pod dies due to oom. Optimal memory and processor limits set. There were no such problems before the upgrade. Please tell me what is the reason for the increase in resources for consumption and how to fix it in order to switch to the new version of vmagent?

**Comment by f41gh7** [comment]
Can you temporary increase memory limit until it doesn't crash. Then collect memory profile according to doc https://docs.victoriametrics.com/#profiling

 And attach it to this issue?

 Memory profile for 1.63.0 version will be useful as well.

**Comment by pollynesterovich** [comment]
We tested upgrading to 1.65.0 and everything works fine, but problems with 1.66.0.
[1.63.0.zip](https://github.com/VictoriaMetrics/helm-charts/files/7244270/1.63.0.zip)
[1.66.0.zip](https://github.com/VictoriaMetrics/helm-charts/files/7244271/1.66.0.zip)

**Comment by pollynesterovich** [comment]
Please tell me when the answer will be given, the memory usage when upgrading to 1.66 or 1.67 versions has almost doubled, how can I fix this?

**Comment by AndrewChubatiuk** [comment]
there's no memory profile for 1.63.0. archive contains two cpu profiles.

**Comment by AndrewChubatiuk** [comment]
closing this issue as version 1.66.0 is too old. please open a new one if it's still relevant in recent releases
