### ISSUE TITLE
Possible issue with ServiceMonitor CRD ?

### ISSUE THREAD

**Issue by MikaSoinetsalo** [VictoriaMetrics/helm-charts#23]
I'm getting the following error when using Terraform Helm provider version 1.1.1 (which uses Helm 3.12) 

Using default values except set "serviceMonitor" to "True". Single Server Helm chart version 0.0.6

_Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"_

Problem is solved if I run the same TF again so it looks like it tries to find that ServiceMonitor CRD too soon.

**Comment by tenmozes** [comment]
Hi @MikaSoinetsalo, you need to install prometheus operator first, it brings to k8s ServiceMonitor resource, otherwise you get the error which you've described above

**Comment by tenmozes** [comment]
hi @MikaSoinetsalo you can find vm-operator following this link https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmagent#troubleshooting
