### ISSUE TITLE
HorizontalPodAutoscaler cannot be used on cluster chart

### ISSUE THREAD

**Issue by Azenet** [VictoriaMetrics/helm-charts#238]
Chart: victoria-metrics-cluster

Hi,

The HorizontalPodAutoscaler cannot currently be used because it is using `spec.metrics` which is available in `autoscaling/v2beta1` but the resource is still using `autoscaling/v1`. The resource should be using `autoscaling/v2beta2` if it is possible regarding compatibility, otherwise it should resort to using `autoscaling/v1` with `targetCPUUtilizationPercentage`.

**Comment by tenmozes** [comment]
Hi, sorry for late response the hpa should be fixed in 0.9.12 version of cluster helm chart
