### ISSUE TITLE
Upgrade to latest operator version failed

### ISSUE THREAD

**Issue by sachinm24** [VictoriaMetrics/helm-charts#239]
Helm upgrade fails.
```
helm -n monitoring list
NAME         	NAMESPACE 	REVISION	UPDATED                               	STATUS  	CHART                          	APP VERSION
operator     	monitoring	2       	2021-10-12 08:52:10.52384 -0700 PDT   	failed  	victoria-metrics-operator-0.3.1	0.19.1
```
[upgrade.log](https://github.com/VictoriaMetrics/helm-charts/files/7331510/upgrade.log)

Only forced upgrade worked. I had to delete the operator service as well

**Comment by Haleygo** [comment]
@sachinm24 Hello, looks like it's caused by crd upgrade, some field breaking change maybe.
I'd suggest using the latest one and check changelog in [operator](https://github.com/VictoriaMetrics/operator) to see if upgrade can be perform silently.
