### ISSUE TITLE
Several issues in victoria-metrics-single

### ISSUE THREAD

**Issue by NaPs** [VictoriaMetrics/helm-charts#24]
Found several issues using the new chart version:
- deployment mode exists (server.statefulSet.enabled = false) but there is deployment resource defined
- ClusterIP is defined to None in the service resource defined in statefulSet mode
- Most options aren't available in the service resource defined in statefulSet mode (type, ExternalIPs...)

Will provide PR soon.

**Comment by tenmozes** [comment]
i will add deployment

**Comment by NaPs** [comment]
Yeah, thank you I forgot that in my PR!

**Comment by tenmozes** [comment]
deployment has been added

**Comment by tenmozes** [comment]
close an issue feel free to reopen it
