### ISSUE TITLE
[victoria-metrics-k8s-stack] Incorrect generated VMRule name

### ISSUE THREAD

**Issue by vterdunov** [VictoriaMetrics/helm-charts#241]
Hi. Thanks for the product.
I faced with an issued with generated a VMRule name.

I tried to install helm chart 
Got error:
```
Helm upgrade failed: failed to create resource: VMRule.operator.victoriametrics.com "monitoring-victoria-metrics-k8s-stack-kube-apiserver-histogram." is invalid: metadata.name: Invalid value: "monitoring-victoria-metrics-k8s-stack-kube-apiserver-histogram.": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')            
```

I guess it happened by 
https://github.com/VictoriaMetrics/helm-charts/blob/0c5039d0d38eb5c513c6933541e403bd0197a95e/charts/victoria-metrics-k8s-stack/templates/rules/kube-apiserver-histogram.rules.yaml#L11

"kube-apiserver-histogram.rules" contains dot character. And unfortunately it was last character.

**Comment by PabloL007** [comment]
Just encountered the same issue with the node-exporter.rules template: https://github.com/VictoriaMetrics/helm-charts/blob/d17c2d5dbf8a9db3a3e77ca2b6478874a3ee4da1/charts/victoria-metrics-k8s-stack/templates/rules/node-exporter.rules.yaml#L11

**Comment by k1rk** [comment]
thanks for opening issue @PabloL007 

adressed this in 6a35cb4ab75a2a66f6f39389ea1cf43e1c522e92

**Comment by Haleygo** [comment]
Closed as completed)
