### ISSUE TITLE
Add more description about the parameters

### ISSUE THREAD

**Issue by woodliu** [VictoriaMetrics/helm-charts#255]
Hi, could you add more description about the parameters? There is so few infromation about them, we are not sure how use them...
![image](https://user-images.githubusercontent.com/9976943/140851197-8af8a5ae-1129-4354-bc04-bac19edba9a6.png)

**Comment by AndrewChubatiuk** [comment]
in PR #1245 updated documentation, grouped sections with default configuration together to provide a link to a full full list of allowed arguments
