### ISSUE TITLE
victoria-metrics-auth chart.fullname missing ?

### ISSUE THREAD

**Issue by bjolivot** [VictoriaMetrics/helm-charts#257]
Hello,
I can't use chart victoria-metrics-auth

The error is :
_Wait helm template failed. Error: template: victoria-metrics-auth/templates/service-monitor.yaml:24:10: executing "victoria-metrics-auth/templates/service-monitor.yaml" at <include "chart.matchLabels" .>: error calling include: template: no template "chart.matchLabels" associated with template "gotpl" Use --debug flag to render out invalid YAML : exit status 1_

With minimal values.yml :
`serviceMonitor:
  enabled: true`

It seems to break at line 14 from template  service-monitor.yaml "  name: {{ template "chart.fullname" . }}"
Not sure why

**Comment by f41gh7** [comment]
must fixed at the latest release
