### ISSUE TITLE
readinessProbe in vmagent is not compatible with `http.pathPrefix`

### ISSUE THREAD

**Issue by hacker** [VictoriaMetrics/helm-charts#261]
When used with `http.pathPrefix` readiness probe never succeeds, because

```
requestURI: /health; cannot get canonical path: missing `-pathPrefix="/vmagent/"` in the requested path: "/health"
```

apparently, some direct control over readiness probe or indirect — by handling httpPrefix specifically — would help?

**Comment by JReko** [comment]
+1

**Comment by hagen1778** [comment]
Supposed to be fixed at https://github.com/VictoriaMetrics/helm-charts/commit/730127f5d41664eb7191800c61bef13fe2e4cd45
