### ISSUE TITLE
How is Victoria metrics k8s stack associated with vmagent

### ISSUE THREAD

**Issue by ktpktr0** [VictoriaMetrics/helm-charts#267]
I installed the latest version of chart for Victoria metrics k8s stack, and it works properly. But I checked the vmagent configuration, but there is no remotewrite configuration. How does it work. I also check vmagent's chart, and the default remotewrite is empty.

**Comment by f41gh7** [comment]
remoteWrite url is set with _helpers magic https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L131

  Additional remoteWrite can be added with
```
vmagent:
  spec:
    remoteWrite:
      - url: "https://insert.vmcluster.domain.com/insert/0/prometheus/api/v1/write"```
