### ISSUE TITLE
add externalTrafficPolicy and healthCheckNodePort to spec services

### ISSUE THREAD

**Issue by dimakrapiva** [VictoriaMetrics/helm-charts#270]
Please add externalTrafficPolicy and healthCheckNodePort to spec services for serviceType LoadBalancer
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip

**Comment by f41gh7** [comment]
Was partially added to the vmalert,vmagent, vmsingle and vmauth.

 Other charts can be updated later.
