### ISSUE TITLE
bug with alertmanager-prometheusRule on victoria-metrics-k8s-stack helm chart

### ISSUE THREAD

**Issue by jmenan** [VictoriaMetrics/helm-charts#271]
Hello,

there seems to be an error in the chart helm `victoria-metrics-k8s-stack`: 

In this chart the prometheusrules especially for the alertmanager use in their expressions a filter on the job.

This job filter in the prometheusRules uses this: `job="alertmanager-main"`

But if we deploy an "alertmanager" with the Helm chart, the job has the value: `vmalertmanager-victoria-metrics-k8s-stack` 

So the prometheusRules cannot be evaluated correctly

An [example](https://github.com/prometheus-operator/kube-prometheus/blob/main/manifests/alertmanager-prometheusRule.yaml#L27) of  probematic expression into the "official" alertmanager prometheusrules 
`max_over_time(alertmanager_config_last_reload_successful{job="alertmanager-main",namespace="monitoring"}[5m]) == 0`

**Comment by f41gh7** [comment]
must be fixed at `0.6.8` version
