### ISSUE TITLE
[victoria-metrics-k8s-stack] [Question] Has VMCluster already been added to the k8s stack chart?

### ISSUE THREAD

**Issue by PabloL007** [VictoriaMetrics/helm-charts#272]
I've just noticed that even though VMCluster is still unticked in the [todo.md](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/todo.md) file for the `victoria-metrics-k8s-stack` helm chart, there was a pull request 6 months ago titled "added VMCluster" that seemed to add it (see [here](https://github.com/VictoriaMetrics/helm-charts/pull/178)). Is there any chance the todo is outdated? Or is this an indication that the chart still isn't ready to be used for that?

**Comment by f41gh7** [comment]
updated TODO
