### ISSUE TITLE
Multi Retention Setup

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/helm-charts#273]
Hey,

I was wondering, how can the Multi Retention Setup described here: https://docs.victoriametrics.com/guides/guide-vmcluster-multiple-retention-setup.html be implemented using the helm chart?
I cant deploy different retention periods in the same helm chart deployment, but I can deploy multiple helm charts. The issue is the vmselect that should communicate with all the vmstorages that was deployed in multiple helm charts..

Thanks for the help!

**Comment by Alon-Katz** [comment]
Thanks @f41gh7!

Are there any plans to support providing only the headless service names for vmstorage? Instead of manually providing the list of vmstorage instances.

This will make it much easier to maintain, and will open a lot more possibilities. For example using HPA (with downscale behavior disabled) for vmstorage instances, this way when the HPA will autoscale the vmstorage then the headless service will provide all the new instances and it makes maintaining the vm cluster much easier for heavy production clusters

**Comment by AndrewChubatiuk** [comment]
hey @Alon-Katz
with enterprise license enabled vmstorage SRV records can be passed to vminsert and vmselect, where all nodes will be automatically discovered. This feature is available in victoria-metrics-cluster chart with enterprise license configured and `autoDiscovery: true` starting from release [0.14.1](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.14.1)
