### ISSUE TITLE
unable to recognize "k8s-stack.yaml": no matches for kind

### ISSUE THREAD

**Issue by ravvereddy** [VictoriaMetrics/helm-charts#275]
helm template k8s-stack vm/victoria-metrics-k8s-stack -f https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/values.yaml -n default > k8s-stack.yaml

kubectl create -f k8s-stack.yaml
podsecuritypolicy.policy/k8s-stack-grafana created
podsecuritypolicy.policy/k8s-stack-grafana-test created
podsecuritypolicy.policy/k8s-stack-prometheus-node-exporter created
podsecuritypolicy.policy/k8s-stack-victoria-metrics-operator created
serviceaccount/k8s-stack-grafana created
serviceaccount/k8s-stack-grafana-test created
serviceaccount/k8s-stack-kube-state-metrics created
serviceaccount/k8s-stack-prometheus-node-exporter created
serviceaccount/k8s-stack-victoria-metrics-operator created
serviceaccount/k8s-stack-victoria-metrics-k8s-stack created
serviceaccount/victoria-metrics-k8s-stack-cleanup-hook created
secret/k8s-stack-grafana created
secret/k8s-stack-victoria-metrics-k8s-stack-alertmanager created
configmap/k8s-stack-grafana-config-dashboards created
configmap/k8s-stack-grafana created
configmap/k8s-stack-grafana-dashboards-default created
configmap/k8s-stack-grafana-test created
configmap/k8s-stack-victoria-metrics-k8s-stack-alertmanager-overview created
configmap/k8s-stack-victoria-metrics-k8s-stack-apiserver created
configmap/k8s-stack-victoria-metrics-k8s-stack-cluster-total created
configmap/k8s-stack-victoria-metrics-k8s-stack-controller-manager created
configmap/k8s-stack-victoria-metrics-k8s-stack-etcd created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-coredns created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-cluster created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-namespace created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-node created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-pod created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-workload created
configmap/k8s-stack-victoria-metrics-k8s-stack-k8s-resources-workloads-na created
configmap/k8s-stack-victoria-metrics-k8s-stack-kubelet created
configmap/k8s-stack-victoria-metrics-k8s-stack-namespace-by-pod created
configmap/k8s-stack-victoria-metrics-k8s-stack-namespace-by-workload created
configmap/k8s-stack-victoria-metrics-k8s-stack-node-cluster-rsrc-use created
configmap/k8s-stack-victoria-metrics-k8s-stack-node-rsrc-use createdconfigmap/k8s-stack-victoria-metrics-k8s-stack-nodes created
configmap/k8s-stack-victoria-metrics-k8s-stack-persistentvolumesusage created
configmap/k8s-stack-victoria-metrics-k8s-stack-pod-total created
configmap/k8s-stack-victoria-metrics-k8s-stack-scheduler created
configmap/k8s-stack-victoria-metrics-k8s-stack-statefulset created
configmap/k8s-stack-victoria-metrics-k8s-stack-victoriametrics created
configmap/k8s-stack-victoria-metrics-k8s-stack-vmagent created
configmap/k8s-stack-victoria-metrics-k8s-stack-vmalert created
configmap/k8s-stack-victoria-metrics-k8s-stack-workload-total created
configmap/k8s-stack-victoria-metrics-k8s-stack-grafana-ds created
configmap/k8s-stack-victoria-metrics-k8s-stack-alertmanager-monzo-tpl created
clusterrole.rbac.authorization.k8s.io/k8s-stack-grafana-clusterrole created
clusterrole.rbac.authorization.k8s.io/k8s-stack-kube-state-metrics created
clusterrole.rbac.authorization.k8s.io/psp-k8s-stack-prometheus-node-exporter created
clusterrole.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator created
clusterrole.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator-psp created
clusterrole.rbac.authorization.k8s.io/victoria-metrics-k8s-stack-cleanup-hook created
clusterrolebinding.rbac.authorization.k8s.io/k8s-stack-grafana-clusterrolebinding created
clusterrolebinding.rbac.authorization.k8s.io/k8s-stack-kube-state-metrics created
clusterrolebinding.rbac.authorization.k8s.io/psp-k8s-stack-prometheus-node-exporter created
clusterrolebinding.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator created
clusterrolebinding.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator-psp created
clusterrolebinding.rbac.authorization.k8s.io/victoria-metrics-k8s-stack-cleanup-hook created
role.rbac.authorization.k8s.io/k8s-stack-grafana created
role.rbac.authorization.k8s.io/k8s-stack-grafana-test created
role.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator created
rolebinding.rbac.authorization.k8s.io/k8s-stack-grafana created
rolebinding.rbac.authorization.k8s.io/k8s-stack-grafana-test created
rolebinding.rbac.authorization.k8s.io/k8s-stack-victoria-metrics-operator created
service/k8s-stack-grafana created
service/k8s-stack-kube-state-metrics created
service/k8s-stack-prometheus-node-exporter created
service/k8s-stack-victoria-metrics-operator created
service/k8s-stack-victoria-metrics-k8s-stack-coredns created
service/k8s-stack-victoria-metrics-k8s-stack-kube-controller-manager created
service/k8s-stack-victoria-metrics-k8s-stack-kube-etcd created
service/k8s-stack-victoria-metrics-k8s-stack-kube-scheduler created
daemonset.apps/k8s-stack-prometheus-node-exporter created
deployment.apps/k8s-stack-grafana created
deployment.apps/k8s-stack-kube-state-metrics created
deployment.apps/k8s-stack-victoria-metrics-operator created
pod/k8s-stack-grafana-test created
job.batch/victoria-metrics-k8s-stack-cleanup-hook created
unable to recognize "k8s-stack.yaml": no matches for kind "VMAgent" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMAlert" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMAlertmanager" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMNodeScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMRule" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMServiceScrape" in version "operator.victoriametrics.com/v1beta1"
unable to recognize "k8s-stack.yaml": no matches for kind "VMSingle" in version "operator.victoriametrics.com/v1beta1"

**Comment by f41gh7** [comment]
In case of manual install with helm template, you have to install CRD first kubectl apply -f https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/crds/crd.yaml

 crd install happen with hook, which not included into helm template command.
