### ISSUE TITLE
[victoria-metrics-k8s-stack] kubernetes-system-kube-proxy rules are created independently of the value of the kubeProxy.enabled and defaultRules.rules.kubernetesSystem attributes

### ISSUE THREAD

**Issue by PabloL007** [VictoriaMetrics/helm-charts#278]
I just noticed that even through I have `kubeProxy.enabled` and `defaultRules.rules.kubernetesSystem` set to false I still get the `KubeProxyDown` alert, looking at the template for the `kubernetes-system-kube-proxy` rules I noticed that the condition is just checking to see if you've enabled creation of the default rules but nothing else:

https://github.com/VictoriaMetrics/helm-charts/blob/7320c2c0f2009e6cd93f9486b4fc2618ea3ffe43/charts/victoria-metrics-k8s-stack/templates/rules/kubernetes-system-kube-proxy.yaml#L6

I think that given that those two flags exist and that this alert will fire continuously if you haven't configured scraping from kube-proxy, the templating condition should check the value of at least one of them.

**Comment by f41gh7** [comment]
must be fixed at `0.6.8` version
