### ISSUE TITLE
Alertmanager status level=error component=nflog msg="Running maintenance failed" permission denied

### ISSUE THREAD

**Issue by weibo-zhao** [VictoriaMetrics/helm-charts#280]
I am using [charts/victoria-metrics-alert](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts) to configure the alertmanager, but I found the following errors in the alertmanager pod logs:
```
level=info ts=2022-02-09T08:56:36.032Z caller=silence.go:379 component=silences msg="Running maintenance failed" err="open /alertmanager/silences.7153164ab75d6846: permission denied"
level=error ts=2022-02-09T08:56:36.032Z caller=nflog.go:365 component=nflog msg="Running maintenance failed" err="open /alertmanager/nflog.5d365deceefa53d9: permission denied"
```
Inside the pod, it also shows the permission denied error
```
/data $ touch example
touch: example: Permission denied
/data $ id
uid=65534(nobody) gid=65534(nogroup)
```
even if I have defined the fsGroup in the values.yaml like following:
```
alertmanager:
  enabled: true
  persistentVolume:
    enabled: true
  securityContext:
    fsGroup: 2000
```
It is interesting to find that the [`securityContext:`](https://github.com/VictoriaMetrics/helm-charts/blob/2df31d6e718bf156401a771b001ce72dafbcb714/charts/victoria-metrics-alert/values.yaml#L152-L159) in the [values.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-alert/values.yaml) is only used for the server but not for the alertmanager.
I found in the [alertmanager-deployment.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/2df31d6e718bf156401a771b001ce72dafbcb714/charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml#L40-L41) that it only uses `.Values.alertmanager.podSecurityContext` for the containers. I think there should be another securityContext under this [spec](https://github.com/VictoriaMetrics/helm-charts/blob/2df31d6e718bf156401a771b001ce72dafbcb714/charts/victoria-metrics-alert/templates/alertmanager-deployment.yaml#L31) to specify `{{- toYaml .Values.SecurityContext | nindent 8 }}`. The idea is from [prometheus alertmanager chart](https://github.com/prometheus-community/helm-charts/blob/f8b10248c58261227834aa049249e3c2af6d8e85/charts/alertmanager/templates/statefulset.yaml#L53-L54). 

I am not sure whether it is a chart bug or my understanding problem. Could you please give me some ideas on how to remove this permission error? 

In addition, a similar issue might be found [here](https://github.com/helm/charts/pull/15666).

Thanks a lot for your help!
Weibo

**Comment by f41gh7** [comment]
Thanks for pull request was merged and released.
