### ISSUE TITLE
[victoria-metrics-single] upgrade to 0.8.18 fails with "executing victoria-metrics-single/templates/server-service.yaml at <.Values.service.healthCheckNodePort>: nil pointer evaluating interface {}.healthCheckNodePort"

### ISSUE THREAD

**Issue by Jeinhaus** [VictoriaMetrics/helm-charts#287]
When upgrading the `victoria-metrics-single` chart to `0.8.18` the following error is reported:

```
Helm upgrade failed: template: victoria-metrics-single/templates/server-service.yaml:82:18: executing "victoria-metrics-single/templates/server-service.yaml" at <.Values.service.healthCheckNodePort>: nil pointer evaluating interface {}.healthCheckNodePort
```

I believe this is due to a missing  `server` key  [here in the server-service.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/27872131f84386cf43bd0f2a6ae22d710fb897fb/charts/victoria-metrics-single/templates/server-service.yaml#L82).

**Comment by korservick** [comment]
Need to patch this in victoria-metrics-agent/templates/service.yaml, victoria-metrics-auth/templates/service.yaml, victoria-metrics-alert/templates/server-service.yaml either?

**Comment by f41gh7** [comment]
It should be fine, only vmsingle chart has different path for service at values.yaml for some reason...

**Comment by korservick** [comment]
Error: UPGRADE FAILED: template: victoria-metrics-alert/templates/server-service.yaml:41:18: executing "victoria-metrics-alert/templates/server-service.yaml" at <.Values.service.healthCheckNodePort>: nil pointer evaluating interface {}.healthCheckNodePort

**Comment by Jeinhaus** [comment]
Has this been released yet? See https://github.com/VictoriaMetrics/helm-charts/pull/288#issuecomment-1046610688

**Comment by f41gh7** [comment]
It's another issue with vmalert. I've fixed it at the latest release. Sry, copy-paste.

**Comment by Jeinhaus** [comment]
Mh, but the version in the [Chart.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/45f5562a16cb68f203ba7474d9a44d604b45d979/charts/victoria-metrics-single/Chart.yaml#L5) is still 0.8.18. Should I have bumped this?
