### ISSUE TITLE
Ability to add vmrules from vmalert.spec

### ISSUE THREAD

**Issue by bon3o** [VictoriaMetrics/helm-charts#289]
In case we use k8s-stack deployed by argocd it would be great to be able to add VMRules by specifying them in spec in values.yaml just as we do with targets through spec.inlineScrapeConfig. It will let us make the sync process to be more transparent.

**Comment by weibo-zhao** [comment]
Total agree, I also want to add additional vmrules in k8s-stack chart, but I didn't find where to add. Did you successfully add them?@bon3o

**Comment by Haleygo** [comment]
close this as completed.
