### ISSUE TITLE
How to change Slack title url

### ISSUE THREAD

**Issue by drsheff** [VictoriaMetrics/helm-charts#301]
Hi, everyone. I can't find value to change url link in title. I've got url like - http://vmalertmanager-vm-operator-victoria-metrics-k8s-stack-0:9093/#/alerts?receiver=slack-monitoring

How I can change that?

**Comment by Haleygo** [comment]
Hello, can you elaborate what url is this?
Seems like it's generated by alertmanager.

**Comment by dezeroku** [comment]
I've encounted a similar issue, although it seems related more to the `vmalert`.

In the PagerDuty incidents that were created by the `victoria-metrics-k8s-stack` the last line points to the source of the alert, e.g.
```
Source: http://vmalert-vm-victoria-metrics-k8s-stack-5b6d6964b9-p84xt:8080/vmalert/alert?group_id=6238890889951999981&alert_id=13875164060741052938
```

In my case what helped is pointing `vmalert` to the correct external domain explicitly:
```
vmalert:
  spec:
    extraArgs:
      external.url: https://my-domain.com
```

I also had the `spec.image.externalURL` set for `alertmanager` itself, but this wasn't enough on its own.
In this case though I think that setting just the above would fix the issue, effectively telling alertmanager what URL it's running under.

**Comment by k7k0** [comment]
@dezeroku there is a typo in your `alertmanager` config, the right attribute to change is `spec.externalUrl`

**Comment by dezeroku** [comment]
That was some time ago, but I've eventually landed on `alertmanager.spec.externalURL` (note the `URL` being uppercase) and it seems to work. I'm using the `victoria-metrics-k8s-stack` chart, basically same way as [here](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L351).

But yeah, the `.image` part in the middle is definitely wrong.

**Comment by AndrewChubatiuk** [comment]
closing issue as solved
