### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by hex2a** [VictoriaMetrics/helm-charts#31]
please add support for authentication

it looks like those flags could be set via `server.extraArgs` but support for kubernetes secrets would be preferred.
https://github.com/VictoriaMetrics/VictoriaMetrics/wiki/Single-server-VictoriaMetrics#security

in case this should be handled exclusively on the ingress level (as mentioned here: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/263#issuecomment-567169644), support for common ingress controllers (nginx, traefik, etc) would be helpful. (e.g. generate a secret and add the annotation to the ingress)

**Comment by tenmozes** [comment]
this already can be dome by means of k8s, just create secret and use it in ingress, in that case you don't need to specify extra args

**Comment by f41gh7** [comment]
You can mount needed secret with extraVolumes and extraVolumeMounts and use it for basic auth.  Or with you can specify it at envs section. docs section https://github.com/VictoriaMetrics/VictoriaMetrics#environment-variables
