### ISSUE TITLE
metric agent metric_relabel_configs issue

### ISSUE THREAD

**Issue by bruse-peng** [VictoriaMetrics/helm-charts#329]
i install metric agent and i metric_relabel_configs drop the pod start with bff.*   but when i  open vmui i can still find the pod start with bff.* as blow,what is the problem

- bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      job_name: kubernetes-nodes-cadvisor-after
      kubernetes_sd_configs:
      - role: node
      metric_relabel_configs:
      - action: drop
        regex: bff.*
        source_labels:
        - Pod
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true

**Comment by bruse-peng** [comment]
![image](https://user-images.githubusercontent.com/47881861/168864018-01436d47-ffae-40a5-ac5a-085d3154ea9e.png)

**Comment by Haleygo** [comment]
Hello,
```
- action: drop
regex: bff.*
source_labels:
- Pod
```
Looks like you should use "pod" instead of "Pod"
