### ISSUE TITLE
MIssing permission to query endpointslices

### ISSUE THREAD

**Issue by AlexShemeshWix** [VictoriaMetrics/helm-charts#335]
Hi
I can see that victoria-metrics-agent chart includes [endpointslices](https://github.com/VictoriaMetrics/helm-charts/blob/65c53ff80baa254f894aea8ec3e3de01267e1c75/charts/victoria-metrics-agent/values.yaml#L434) as role for kubernetes_sd_config sections in scrape configuration.
But ClusterRole definition in [clusterrole.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/templates/clusterrole.yaml) is lacking permission for endpoinslices resource. 
When i deploy this chart it wont scrape from endpointslices because of lacking permissions. 
Please add endpointslices resource to ClusterRole definition.

**Comment by AlexShemeshWix** [comment]
This is PR that suppose to fix it: [#93](https://github.com/VictoriaMetrics/helm-charts/compare/master...AlexShemeshWix:patch-1)

**Comment by hagen1778** [comment]
Supposed to be fixed at https://github.com/VictoriaMetrics/helm-charts/pull/336
