### ISSUE TITLE
[victoria-metrics-operator] Error: failed to create resource: ValidatingWebhookConfiguration.admissionregistration.k8s.io

### ISSUE THREAD

**Issue by sdomme** [VictoriaMetrics/helm-charts#338]
Hello. I got the following error during the installation of the [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and enabling admissionWebhooks.

`Error: failed to create resource: ValidatingWebhookConfiguration.admissionregistration.k8s.io "victoria-stack-victoria-metrics-operator-admission" is invalid: webhooks[7].name: Duplicate value: "vmuser.victoriametrics.com"`

Looking into the template of the [operator](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-operator/templates/webhook.yaml) it seems to be an copy&paste issue coming from https://github.com/VictoriaMetrics/helm-charts/commit/e05176082b0b6f584ad75283d08661077a13b490  

The name is set to vmuser.victoriametrics.com for the vmrules configuration https://github.com/VictoriaMetrics/helm-charts/blob/95f05d4f0b87497030616858a2b572b33c0e001f/charts/victoria-metrics-operator/templates/webhook.yaml#L180

**Comment by f41gh7** [comment]
It's an issue with code-generator for webhook after adding `VMRule` validation. must be fixed soon.

**Comment by f41gh7** [comment]
must be fixed at the latest version of operator's helm chart.
