### ISSUE TITLE
Kubernetes has deprecated port 10251-10252 for controller manager and scheduler

### ISSUE THREAD

**Issue by maxpain** [VictoriaMetrics/helm-charts#339]
Kubernetes has deprecated port 10251-10252 for controller manager and scheduler.
Now we have port 10257 for the controller manager and 10259 for the scheduler, they both are secure ports and require authentication to fetch the metrics.

`kube-prometheus-stack` has the fix:
https://github.com/kubernetes/kubernetes/pull/85043

Why vm-stack doesn't have it?

**Comment by f41gh7** [comment]
Thanks! will fix it.

**Comment by f41gh7** [comment]
must be fixed at https://github.com/VictoriaMetrics/helm-charts/commit/d79e7a4604d4bbb839418da68014a16e84c6c59e#diff-3e408e9099603d921f81418b12681cf9c21908f6154a8f7f006fa6e0a510620b

**Comment by Haleygo** [comment]
close as completed)

**Comment by rcattin** [comment]
Hello! 

> must be fixed at [d79e7a4#diff-3e408e9099603d921f81418b12681cf9c21908f6154a8f7f006fa6e0a510620b](https://github.com/VictoriaMetrics/helm-charts/commit/d79e7a4604d4bbb839418da68014a16e84c6c59e#diff-3e408e9099603d921f81418b12681cf9c21908f6154a8f7f006fa6e0a510620b)

This fixed the deprecated port only for the controller manager, the default value for the scheduler is still the deprecated one
