### ISSUE TITLE
[victoria-metrics-k8s-stack] Alerting in the multi-cluster setup

### ISSUE THREAD

**Issue by sydorovdmytro** [VictoriaMetrics/helm-charts#342]
Hello all,
 
we have a VMcluster created by [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) and multiple vmagents (created by the same helm chart) in different Kubernetes clusters. The `externalLabels` parameter is set for each cluster:
```
externalLabels:
  cluster: cluster-name
 ```
Everything works fine, except alerting rules. Some default alerting rules need an adjustment to respect custom labels, specified in externalLabels (or maybe an additional parameter for this).

Example of the alert that needs an improvement:
![image](https://user-images.githubusercontent.com/11457338/178515071-da86667b-8f47-4606-9c40-9a024546eded.png)
From this alert (and some others defined [here](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack/templates/rules)), we don't know which cluster is affected and which alerting method to use.

The original discussion was started here: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1657550782983139

**Comment by vaskozl** [comment]
Looks like this was fixed atleast partially (maybe completely) fixed in:
 https://github.com/VictoriaMetrics/helm-charts/commit/5eb1f9c6fc6a55616f56768afa14e88d1871848b#diff-64d1319c0f306489ccc1aa79d97f8fd03c06ec0186af52708ca8734d4fec4ead

**Comment by vaskozl** [comment]
A lot of the alerts still do not group by cluster as an example "KubeCPUOvercommit" does not group by cluster (charts/victoria-metrics-k8s-stack/templates/rules/kubernetes-resources.yaml).

Support was added upstream in kubernetes-mixin when built with "showMultiCluster":
https://github.com/kubernetes-monitoring/kubernetes-mixin/commit/0e1287c95919e144ace5f0ad29c82748acfbac97

So to get multi cluster alert support one can't used the built in alerts in the stack chart.

**Comment by Haleygo** [comment]
@sydorovdmytro @vaskozl 
Hello, looks like https://github.com/prometheus-operator/kube-prometheus/issues/2056 is closed as completed, is there other work need to be done here?

**Comment by vaskozl** [comment]
I think it's still far from possible, running an alertmanager per cluster filtering by cluster label is the only good way to go with a multi-cluster VM.

Happy for you to close as it's mostly up the the upstream here.

**Comment by AndrewChubatiuk** [comment]
[Added to hack script modification](https://github.com/VictoriaMetrics/helm-charts/commit/d45e425b4de0e163ab591add0747356e80252468), which adds (or replaces existing `cluster` labels) to `{{ .Values.global.clusterLabel }}` in all `by` and `on` expressions. by default `global.clusterLabel` is set to `cluster`

**Comment by AndrewChubatiuk** [comment]
all rules are additionally grouped by configurable label starting release [0.25.6](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.25.6)
