### ISSUE TITLE
Failed to inspect image

### ISSUE THREAD

**Issue by 3vaLpwner** [VictoriaMetrics/helm-charts#344]
Hello!

Trying to install VM cluster in k8s.
OS: Rocky Linux 8.5 Obsidian
k8s: v1.24.2
Firewalld: off
Internet: on, no restrictions

Have a problem:
![image](https://user-images.githubusercontent.com/80704041/179425412-6c4443f4-ae30-4720-ae74-fdf1299553ba.png)

Installation process itself is a literally default:
```
helm repo add vm https://victoriametrics.github.io/helm-charts/
helm repo update
helm show values vm/victoria-metrics-k8s-stack > values.yaml
helm install latest vm/victoria-metrics-k8s-stack -f values.yaml -n monitoring
```
Logs in pod are:
```
stream logs failed container "victoria-metrics-operator" in pod "latest-victoria-metrics-operator-59c7dcbbdb-gz2tc" is waiting to start: ImageInspectError for monitoring/latest-victoria-metrics-operator-59c7dcbbdb-gz2tc (victoria-metrics-operator)
```
Describe is:
```
   Warning  InspectFailed  16s (x6 over 74s)  kubelet            Failed to inspect image "victoriametrics/operator:v0.25.1": rpc error: code = Unknown desc = short-name "victoriametrics/operator:v0.25.1" did not resolve to an alias and no unqualified-search registrie │
│ s are defined in "/etc/containers/registries.conf.d/01-unqualified.conf"                                                                                                                                                                                                   │
│   Warning  Failed         16s (x6 over 74s)  kubelet            Error: ImageInspectError
```

How to fix that?
Thanks in advance.

**Comment by denisgolius** [comment]
> are defined in "/etc/containers/registries.conf.d/01-unqualified.conf"

Hi @3vaLpwner !
As a workaround try to set `unqualified-search-registries = ["docker.io", "quay.io"]` in `/etc/containers/registries.conf.d/01-unqualified.conf` and try to deploy victoria-metrics-k8s-stack again. 
BTW: we have updated victoria-metrics-k8s-stack and VictoriaMetrics operator as well as a new version of VictoriaMetrics has been released - see https://docs.victoriametrics.com/CHANGELOG.html#v1800

**Comment by AndrewChubatiuk** [comment]
solution is to pass to k8s-stack helm chart default registry name for all images
```yaml
victoria-metrics-operator:
  env:
    - name: VM_CONTAINERREGISTRY
       value: docker.io
```
