### ISSUE TITLE
Feature: add HPA for Statefulset based VMselect

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/helm-charts#359]
It would be great to have support HPA for Statefulset based VMselect deployments for `victoria-metrics-cluster` helm chart

**Comment by Haleygo** [comment]
@Vladikamira Hello!
Looks like it's already done [here](https://github.com/VictoriaMetrics/operator/commit/9a7ebe905939d1c8342f7f314b78d8231c7dc518)

**Comment by Vladikamira** [comment]
Awesome! Thanks!
