### ISSUE TITLE
How to use snmp_exporter with k8-stack flavor?

### ISSUE THREAD

**Issue by filipdadgar** [VictoriaMetrics/helm-charts#360]
I have been digesting the docs but cannot get my head around this, maybe already answered question, so appreciate any help. :)

I am evaluating the k8-stack charts. Things work as expected. 

My challenge is that I dont really understand how to introduce new additional scrape config. Is it as configmap or secret or something else?

I wish to monitor network appliance with snmp according to [snmp_exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-snmp-exporter):

scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 192.168.1.2  # SNMP device.
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: my-service-name:9116  # The SNMP exporter's Service name and port.

How would such "config" look like for VM? 

snmp_exporter is running on the cluster:

NAME                                                  TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)            AGE
snmpexporter-prometheus-snmp-exporter                 ClusterIP      10.102.0.186     <none>         9116/TCP           24h
victoriametrics-grafana                               LoadBalancer   10.102.62.26     192.168.2.28   80:30915/TCP       5d1h
victoriametrics-kube-state-metrics                    ClusterIP      10.108.38.144    <none>         8080/TCP           5d1h
victoriametrics-prometheus-node-exporter              ClusterIP      10.97.122.224    <none>         9100/TCP           5d1h
victoriametrics-victoria-metrics-operator             ClusterIP      10.100.216.165   <none>         8080/TCP,443/TCP   5d1h
vmagent-victoriametrics-victoria-metrics-k8s-stack    ClusterIP      10.103.102.202   <none>         8429/TCP           17h
vmalert-victoriametrics-victoria-metrics-k8s-stack    ClusterIP      10.109.32.174    <none>         8080/TCP           23h
vmsingle-victoriametrics-victoria-metrics-k8s-stack   ClusterIP      10.107.131.233   <none>         8429/TCP           23h

Bonus question:

vmui isnt included in k8-stack charts?

**Comment by filipdadgar** [comment]
Thank you @denisgolius, quickly tried it:

curl 10.107.131.233:8429/vmui
<a href="/vmui/?">Moved Permanently</a>.

Also:

curl 10.107.131.233:8429/select/
remoteAddr: "10.244.0.0:56933"; requestURI: /select/; unsupported path requested: "/select/"

The documentation doesnt clearly state where to find accountid either. :(

**Comment by denisgolius** [comment]
> Thank you @denisgolius, quickly tried it:
> 
> curl 10.107.131.233:8429/vmui response is: a href="/vmui/?">Moved Permanently.
> 
> Also:
> 
> curl 10.107.131.233:8429/select/ remoteAddr: "10.244.0.0:56933"; requestURI: /select/; unsupported path requested: "/select/"
> 
> The documentation doesnt clearly state where to find accountid either. :(

`vmsingle-victoriametrics-victoria-metrics-k8s-stack ClusterIP 10.107.131.233 8429/TCP 23h` you have installed VictoriaMetrics Single so `vmui` should be accessible on `http://10.107.131.233:8429/vmui/`

**Comment by filipdadgar** [comment]
Thank you @denisgolius!

http://10.107.131.233:8429/vmui/ is indeed correct!

Now to be able to access this "page" i would wish to have a lb address instead of clusterip. But editing the service and change from ClusterIP to LoadBalancer doesnt really bite. Any clues why?

**Comment by filipdadgar** [comment]
Regarding the SNMP poll question, I went the road of using unipoller as the network is based on unifi products.

I also deployed cluster version of VM instead (with fewer replicas).
In the agent values config i appended:

scrape_configs:
    - job_name: unifipoller
      scrape_interval: 30s
      static_configs:
        - targets: ['unifipoller-service.monitoring.svc.cluster.local:9130']
      tlsConfig:
        insecureSkipVerify: true
      metrics_path: /metrics
    - job_name: vmagent
      static_configs:
        - targets: ["localhost:8429"]
    - job_name: "kubernetes-apiservers"
      kubernetes_sd_configs:
        - role: endpoints
        ...

I also skipped vmui completely and use Grafana's explore feature and its good enough.
