### ISSUE TITLE
Add support for multi-level cluster setup in helm charts

### ISSUE THREAD

**Issue by jsanant** [VictoriaMetrics/helm-charts#361]
The [multi-level cluster setup](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#multi-level-cluster-setup) options are present in the vminsert and vmstorage. But they have not been enabled in the helm charts.

**Comment by AndrewChubatiuk** [comment]
hey @jsanant 
can barely imagine how this setup should look like to cover majority of cases
from my point of view it makes sense to deploy multi-level setup to multiple clusters and have single vmselect as an entrypoint either deployed on one of these clusters or separately, which cannot be easily covered by a single deployment of a single chart.
Instead you can deploy `victoria-metrics-cluster`on each k8s cluster you want and then deploy `victoria-metrics-cluster` chart separately with only `vmselect` enabled and point it to previously deployed clusters using `vmselect.extraArgs`
