### ISSUE TITLE
[victoria-metrics-k8s-stack] can't change image for VMAgent, VMalert, VMalertmanager: config-reloader

### ISSUE THREAD

**Issue by avtalabirchuk** [VictoriaMetrics/helm-charts#363]
Hi, VM team

I try to use the victoria-metrics-k8s-stack version [0.11.1 or 0.11.0 or 0.10.3] chart; there is no way to change the original container image:
  1. VMagent: config-reloader. (source image helm chart quay.io/prometheus-operator/prometheus-config-reloader )
  2. VMalert: config-reloader ( source image helm chart jimmidyson/configmap-reload:v0.3.0 )
  3. VMalertmanager: config-reloader ( source image helm chart jimmidyson/configmap-reload:v0.3.0 )

The values.yaml configuration does not provide for replacing the images listed above with alternative ones. This makes it difficult to use vm-stack in infrastructures closed from the Internet.

**Comment by tenmozes** [comment]
@k1rk @f41gh7 could you please take alool?

**Comment by k1rk** [comment]
@avtalabirchuk hi
,.
You can override images for config reloader by specifying them in spec for CRD, as each CRD allows you to override containers definition. See [VMAgent](https://docs.victoriametrics.com/operator/api.html#vmagentspec), [VMAlert](https://docs.victoriametrics.com/operator/api.html#vmalertspec), [VMAlertmanager](https://docs.victoriametrics.com/operator/api.html#vmalertmanagerspec). 
and victoria-metrics-k8s-stack allows you to pass any parameter to spec of the CR Object. For example values.yaml with config reloader override for VMAgent will look like 
```
vmagent:
  spec:
    containers:
      - name: config-reloader
        image: victoriametrics/operator:config-reloader-0.1.0
```

alternative approach would be to specify `VM_CUSTOMCONFIGRELOADERIMAGE` environment variable for Victoria Metrics Operator. More information on available variables here https://github.com/VictoriaMetrics/operator/blob/master/vars.MD

**Comment by avtalabirchuk** [comment]
@k1rk hi,

Perfect, your solution is working.
Thanks

**Comment by parkjeongryul** [comment]
> vmagent:
  spec:
    containers:
      - name: config-reloader
        image: victoriametrics/operator:config-reloader-0.1.0

It started to stop working for vmagent In the latest vm operator.

We should probably set this env variable.

https://github.com/VictoriaMetrics/VictoriaMetrics/blob/3e0236b4a337af736d7e24e8b1f62341f01107c8/docs/operator/vars.md?plain=1#L35C6-L35C6
