### ISSUE TITLE
Do not trigger VMagent pod restart on configuration changes

### ISSUE THREAD

**Issue by Vladikamira** [VictoriaMetrics/helm-charts#366]
Are we certain that we should [trigger](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/templates/statefulset.yaml#L37) `VMagent` pod restart on configuration change? 

IMHO it would be great if can rely on `configmap-reloader` or internal `VMagent` check config

**Comment by Haleygo** [comment]
@Vladikamira Hello! 
What version of victoria-metrics-k8s-stack are you using? I think vmagent contains `config-reloader` now.

**Comment by Vladikamira** [comment]
yep, it's there already, I will close the issue 👍
