### ISSUE TITLE
vmalert not firing alerts

### ISSUE THREAD

**Issue by ajayanaj** [VictoriaMetrics/helm-charts#368]
Hello,

We are testing vmalert for our alerting requirements. After the deployment we noticed that it's not firing any alerts even if it's matching the alerting condition. When checking metrics we saw the alerts are in pending state(not sure why it's staying in pending state). We tried to hit /vmalert/api/v1/alert API and found strange value. 

For example
`alerts": [
      {
        "state": "pending",
        "name": "Fluentd",
        "value": "0",
        "labels": {
          "alertgroup": "Fluentd",
          "alertname": "Fluentd",
          "cluster": "cluster-name",
          "severity": "critical",
          "team": "Integration",
          "type": "flushpubnub"
        },
        "annotations": {},
        "activeAt": "2022-09-05T08:40:11.361565316Z",
        "id": "17867250573882783263",
        "rule_id": "2044009873203773195",
        "group_id": "3492897935012505283",
        "expression": "sum(fluentd_output_status_num_errors{type=~\"mongo.*|.*pub.*\"}) by (type,cluster,region) > 10",
        "restored": false
      },`

When we query the same expression "sum(fluentd_output_status_num_errors{type=~\"mongo.*|.*pub.*\"}) by (type,cluster,region) > 10"  we are getting the below results.

<img width="1362" alt="Screenshot 2022-09-05 at 2 40 05 PM" src="https://user-images.githubusercontent.com/45065725/188413285-103f8c99-e8b0-4755-920c-44bcb6f3a18b.png">

<img width="706" alt="Screenshot 2022-09-05 at 2 40 44 PM" src="https://user-images.githubusercontent.com/45065725/188413321-4cf3b3a2-1c0e-4a63-9968-a77f75a2e79f.png">

it's not throwing any issues/errors in logs.
Version of Vmalert: v1.81.1 (started with v1.69.0 and upgraded to latest thought it will fix the issue)

Could any one can help us here?

**Comment by Haleygo** [comment]
@ajayanaj  Hello! Sorry for the delay.
Is this still bother you? If it is, can you create a new one in https://github.com/VictoriaMetrics/VictoriaMetrics or ask in slack https://slack.victoriametrics.com.

**Comment by ajayanaj** [comment]
@Haleygo It's working now, I will close this issue now.
