### ISSUE TITLE
[Feature][operator] Argocd synchronization annotation

### ISSUE THREAD

**Issue by bkomraz1** [VictoriaMetrics/helm-charts#370]
VictoriaMetrics operator supports adding annotations for converted object for properly comparing and syncing ArgCD objects.

| VM_PROMETHEUSCONVERTERADDARGOCDIGNOREANNOTATIONS | false | false | adds compare-options and sync-options for prometheus objects converted by operator it helps to properly use converter with ArgoCD |

It should be possible to enable it by values

**Comment by bkomraz1** [comment]
@k1rk Technically you are right, but how users will know about this feature? I had to go to code of the operator to find it. I am not sure that all users will do it.

At least readme of helm chart should have list of supported environment variables and values.yaml should reference to vars.MD file

https://github.com/VictoriaMetrics/operator/blob/master/vars.MD

**Comment by Haleygo** [comment]
>but how users will know about this feature? I had to go to code of the operator to find it. I am not sure that all users will do it.

Maybe can be enhanced with this https://github.com/VictoriaMetrics/operator/issues/580

**Comment by AndrewChubatiuk** [comment]
in helm chart it can be enabled using 
```yaml
operator:
  prometheus_converter_add_argocd_ignore_annotations: true   
```
or in victoria-metrics-k8s-stack chart
```yaml
victoria-metrics-operator:
  operator:
    prometheus_converter_add_argocd_ignore_annotations: true   
```
