### ISSUE TITLE
Consider using nginx or vmauth for balancing read load to vmselects for cluster chart

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/helm-charts#376]
Looks like balancing via default k8s service is not always optimal. During the benchmarks I found that vmselects are receving non equal number of queries. Especially, in cases when read queries have different execution time. This may result into excessive resource usage for some vmselects. Would be great to try using nginx for better balancing of the read load. Least-loaded strategy seems like a better fit here.

**Comment by cloud-66** [comment]
at least, Open source nginx can't aware resource consumption by backends. How can this be implemented ?

**Comment by hagen1778** [comment]
@cloud-66 we can try using [vmauth](https://docs.victoriametrics.com/vmauth.html) instead, as it provides [load-balancing feature out-of-box](https://docs.victoriametrics.com/vmauth.html#load-balancing). 

We can try to validate the assumption for vmauth to improve balancing by testing it [on our playground](https://play-grafana.victoriametrics.com/explore?left=%7B%22datasource%22:%22P38648FE0F8C5BEA2%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22victoriametrics-datasource%22,%22uid%22:%22P38648FE0F8C5BEA2%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%28rate%28vm_http_requests_total%7Bjob%3D~%5C%22vmselect-benchmark-vm-cluster%5C%22,%20instance%3D~%5C%22.%2A%5C%22,%20path%3D~%5C%22.%2Aquery%5C%22%7D%5B$__rate_interval%5D%29%29%20by%20%28pod%29%20%3E%200%22,%22format%22:%22time_series%22,%22intervalFactor%22:1,%22range%22:true,%22refId%22:%22A%22,%22interval%22:%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-3h%22,%22to%22:%22now%22%7D%7D&orgId=1).

**Comment by AndrewChubatiuk** [comment]
vmauth was included in release [0.14.1](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.14.1)
