### ISSUE TITLE
[victoria-metrics-k8s-stack] Resources for cleanup hook pod

### ISSUE THREAD

**Issue by alexandrovas** [VictoriaMetrics/helm-charts#385]
Hello!

I use opa-gatekeeper in my k8s cluster and force all pods to have resources (requests and limits) declared.

In file [uninstall_hook.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/uninstall_hook.yaml) there is no way to set resources for job pod.

Can you please add values for this?

**Comment by f41gh7** [comment]
Hello, default resources was added to the chart's webhook.
