### ISSUE TITLE
Update dependencies of victoria-metrics-k8s-stack helm-chart

### ISSUE THREAD

**Issue by hpsawant7887-lacer** [VictoriaMetrics/helm-charts#395]
Hi Team

The `victoria-metrics-k8s-stack` is using older versionc(4.13.*) of `kube-state-metrics`

https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/Chart.yaml#L15-L18

Can we update to `4.21.*` -> https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/Chart.yaml#L10

We really need `volumes` and `volumeMounts` in deployment chart that was added only 3 months ago
https://github.com/prometheus-community/helm-charts/commit/b48194cb4e47a1b6f32794724eda7a4c40a2bb7a

**Comment by f41gh7** [comment]
Hello, dependency was updated at the lastest chart release.
