### ISSUE TITLE
k8s-stack: Referenced old version of prometheus-node-exporter breaks compatibility with kubernetes >=1.25

### ISSUE THREAD

**Issue by micw** [VictoriaMetrics/helm-charts#409]
The k8s-stack references prometheus-node-exporter in version 3.x. The latest changed for 1.25 compatibility are available with version 4.4.x (PodSecurityPolicy deprecation):

https://github.com/prometheus-community/helm-charts/blob/prometheus-node-exporter-4.4.0/charts/prometheus-node-exporter/templates/psp.yaml

**Comment by Haleygo** [comment]
I think prometheus-node-exporter was upgraded to 4.7.* after https://github.com/VictoriaMetrics/helm-charts/commit/6d9c49d6c6492697713ad8a358d60c68d8a96dcf.
Close as completed.
