### ISSUE TITLE
provide pod security policies (optional) for clusters with psp enabled

### ISSUE THREAD

**Issue by avthart** [VictoriaMetrics/helm-charts#42]
Victoria Metrics can not run in clusters where pod security policies are required.

**Comment by tenmozes** [comment]
Hi @avthart thank you for report, could you please provide more details 
the best way is to attach configuration which doesn't work

**Comment by avthart** [comment]
In most clusters today, by default, all resources (e.g. Deployments and StatefulSets) have permissions to create pods. Kubernetes however provides a more fine-grained authorization policy called [Pod Security Policy (PSP)](https://kubernetes.io/docs/concepts/policy/pod-security-policy/).

PSP allows the cluster owner to define the permission of each object, for example creating a pod. If you have PSP enabled on the cluster, and you deploy VictoriaMetrics, you will need to provide the Deployment or StatefulSet with the permissions to create pods.

Before applying any objects you first need to apply the PSP permissions (what permissions are needed to run VictoriaMetrics, vmalert, vmagent, etc). 

Many helm charts (prometheus-operator, nginx-ingress, etc) already have a flag to enable PSP.

**Comment by tenmozes** [comment]
sorry for confuse, i meant could you please provide yaml which doesn't work or preconditions how to reproduce error, why am i asking:
- psp is enabled by default  in cluster (https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/values.yaml#L12)
- psp for cluster is created if enabled - https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/podsecuritypolicy.yaml
- cluster role and cluster role binding are also created by default 
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/clusterrolebinding.yaml and https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/clusterrole.yaml

**Comment by avthart** [comment]
We have tested that PSP is working for `victoria-metrics-single` and `victoria-metrics-cluster`. For `vm-agent` and `vm-alert` there is currently no flag to enable psp. Are there any plans to implement this?

**Comment by tenmozes** [comment]
@avthart  i will add it this week

**Comment by tenmozes** [comment]
@avthart sorry for delay could you please review https://github.com/VictoriaMetrics/helm-charts/pull/54

**Comment by tenmozes** [comment]
@avthart please you can find psp for agent in 0.5.0 for alert - 0.2.0
feel free to reopen an issue

**Comment by nickvth** [comment]
> @avthart you can find psp for agent in 0.5.0 for alert - 0.2.0
> feel free to reopen an issue if any functionality doesn't work

@tenmozes @avthart is on holiday, i will test this today

**Comment by nickvth** [comment]
> > @avthart you can find psp for agent in 0.5.0 for alert - 0.2.0
> > feel free to reopen an issue if any functionality doesn't work
> 
> @tenmozes @avthart is on holiday, i will test this today

@tenmozes tested and looks good, thanks for the fix!

**Comment by avthart** [comment]
Just found out that the `serviceAccountName` is not configured for vm alert deployement.
