### ISSUE TITLE
k8s-stack: duplicate ConfigMap resource identifier

### ISSUE THREAD

**Issue by mbrancato** [VictoriaMetrics/helm-charts#427]
I'm using the `k8s-stack` helm chart with the [helm-controller](https://github.com/fluxcd/helm-controller), which is using [kustomize](https://github.com/kubernetes-sigs/kustomize/) to apply some resources. I'm getting the following error, generated by this [code](https://github.com/kubernetes-sigs/kustomize/blob/8a869f6045df922959f675a9f0903b567de4bbbe/api/resmap/reswrangler.go#L76-L84).  

```
Helm install failed: error while running post render on files: may not add resource with an already registered id: 
~G_v1_ConfigMap|monitoring|victoria-metrics-victoria-metrics-k8s-stack-k8s-resources-workl
```

The issue appears to be that the resource names are just too long. My release name is `victoria-metrics`, but that makes the resources in question be too long.

The ConfigMaps in question here are:
- `k8s-resources-workloads-namespace`
- `k8s-resources-workload`

The `k8s-stack` chart is truncating the final name of these to 63 characters, which is causing them to have duplicate names.

https://github.com/VictoriaMetrics/helm-charts/blob/070162fc0a2ed1daffb6bc0b298397dd9f73fd26/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workload.yaml#L11

https://github.com/VictoriaMetrics/helm-charts/blob/070162fc0a2ed1daffb6bc0b298397dd9f73fd26/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/k8s-resources-workloads-namespace.yaml#L11

So with a release name of `victoria-metrics`, both of these ConfigMaps have a name of `victoria-metrics-victoria-metrics-k8s-stack-k8s-resources-workl` after being truncated.

**Comment by mbrancato** [comment]
Note that using helm to directly apply this chart, I get a similar error:

```shell
% helm install victoria-metrics vm/victoria-metrics-k8s-stack -f vm-values.yaml -n monitoring --version 0.12.13
W1207 15:32:50.100386   87362 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1207 15:32:54.030156   87362 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
Error: INSTALLATION FAILED: configmaps "victoria-metrics-victoria-metrics-k8s-stack-k8s-resources-workl" already exists
```

**Comment by Haleygo** [comment]
Close as completed, feel free to reopen if there is further question.
