### ISSUE TITLE
k8s-stack: Allow uninstall hook to terminate in istio environments

### ISSUE THREAD

**Issue by m-wynn** [VictoriaMetrics/helm-charts#428]
A common issue istio users encounter with Jobs is that the Istio sidecar will not quit when the other pods have finished, leaving the job in Running status forever (https://github.com/istio/istio/issues/6324).  Right now, the [uninstall hook](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/uninstall_hook.yaml) is susceptible to this.

There are two ways to fix this:

1. Modify the command so that the container calls something like `curl -X POST http://localhost:15020/quitquitquit` at the end.
2. Add a label to the job's container like `sidecar.istio.io/inject: “false”`

I'm not sure either of these options should be present in the default install.  However, in the current template, they don't appear to be customizable by the user either.

The current workaround is to port-forward into the job and manually run the quitquitquit command.

**Comment by Haleygo** [comment]
Hello!
Which chart and job are we talking about?

>Add a label to the job's container like sidecar.istio.io/inject: “false”

Maybe we can add something like extraLabels. But if I understand you correctly, adding this label will disable istio sidecar injection, is that what you want? 
What if we need the sidecar then, it doesn't seems to solve the problem.

**Comment by AndrewChubatiuk** [comment]
this issue was fixed in istio 1.19+
