### ISSUE TITLE
Add custom rules for victoria-metrics-k8s-stack installation

### ISSUE THREAD

**Issue by ep4sh** [VictoriaMetrics/helm-charts#447]
Dear team,

could you please suggest the best way to add custom rules to the [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)?

Some additional info: we have a huge amount of custom rules, like:
<img width="489" alt="Screenshot 2023-01-17 at 12 44 39" src="https://user-images.githubusercontent.com/19505042/212876605-54a519ba-aafb-4103-b0ba-f70677588b8b.png">

If I even add 10% of these rules to the [additionalVictoriaMetricsMap](
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/values.yaml#L82) the helm installation fails due to the helm release size in bytes (k8s secret restriction). So I need a way to split my rules set on different files.

As far as I see, there is a directory in the chart:
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack/templates/rules

But in that case I need to clone the repository locally and manage it. That's a bit pointless scenario (I just want to have easy-upgrade installation).

So is there any interface for me as for user to apply a large amount of custom rules with some kind of hierarchy? Like
```
custom_rules/
     teamA_dir/
         elastic/
           rule1.yaml
           rule2.yaml
         postgresql
           rule1.yaml
           rule2.yaml
         ....
       teamB_dir/
                elastic/
           rule1.yaml
           rule2.yaml
         postgresql
           rule1.yaml
           rule2.yaml
```

Best regards,
Pasha

**Comment by zekker6** [comment]
Hi @ep4sh 
I can suggest you to include `victoria-metrics-k8s-stack` Chart as dependency to your own chart and use templates there to store all required rules in a manner you will need to.
So the structure will be similar to:
```
.
├── Chart.lock
├── Chart.yaml
├── templates
│   └── myrules.yaml
└── values.yaml
```

Chart.yaml:
```yaml
apiVersion: v2
name: victoria-metrics-k8s-stack
version: 0.0.0

dependencies:
- name: victoria-metrics-k8s-stack
  version: "0.14.4"
  repository: "https://victoriametrics.github.io/helm-charts/"
```

So you will be able to define your own values and templates to create necessary resources.

**Comment by ep4sh** [comment]
Hi @zekker6, thank you for prompt reply!

As far as I understood, I shall manage Alertmanager resource via creation `VMRule`/`VMServiceScrape`/etc CRDs in my parent chart - that's a correct way, isn't it?

**Comment by ep4sh** [comment]
This does make sense, everything is a trade-off :)

Really appreciate your time and your help, 
cheers!
