### ISSUE TITLE
HA modes for VMAgent/VMAlert in victoria-metrics-k8s-stack installation

### ISSUE THREAD

**Issue by ep4sh** [VictoriaMetrics/helm-charts#449]
Dear team,

as far I got per docs, HA modes for VMAgent and VMAlerts are being set via increasing the amount of these entities (agent and alert). Is there a way to scale up replicas for VMAgent/VMAlert in [victoria-metrics-k8s-stack installation](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)?

Or even more general question: how to set up HA in that kind of installation for VMAlert/VMAgent?

Thank you in advance,
Pasha.

**Comment by AndrewChubatiuk** [comment]
you can increase amount of replicas of both VMAgent and VMAlert by changing `vmagent.spec.replicaCount` and `vmalert.spec.replicaCount` respectively, but you should also keep in mind, that:
 - VMAlertmanager should be scaled to multiple instances as well `alertmanager.spec.replicaCount`
 - multiple VMAgent replicas with identical scrape configurations will produce duplicated samples in a storage, so [deduplication](https://docs.victoriametrics.com/cluster-victoriametrics/#deduplication) is required
