### ISSUE TITLE
add variable to supress output of NOTES.txt

### ISSUE THREAD

**Issue by fsperling** [VictoriaMetrics/helm-charts#46]
When running / upgrading helm the output of NOTES.txt might be helpful at first. But once you have your setup running it isn't needed and obfuscates the important messages of wether the helm run was successful.

I would suggest another helm variable to disable this output.

https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/NOTES.txt

**Comment by tenmozes** [comment]
the `printNotes` option has been added to `values.yaml` file for cluster version of VM in 0.6.3
