### ISSUE TITLE
vmalert to support notifier config

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/helm-charts#468]
Support of https://docs.victoriametrics.com/vmalert.html#notifier-configuration-file is supposed to simplify notifiers configuration process. There will be no need to backport flag values anymore, since all of them can be configured via file.

**Comment by hakuno** [comment]
It's even needed for setting up `dns_sd_configs`.
The current Helm Chart can't support that.

**Comment by hakuno** [comment]
@hagen1778 I'm sure it solves https://github.com/VictoriaMetrics/helm-charts/pull/572

**Comment by Haleygo** [comment]
Now users can use `-notifier.config=</path/file>` in following steps:
1. use [extraObjects](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-alert/values.yaml#L371) to create extra configmap or secret;
2. mount configmap/secret to `/path` using [extraVolumes](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-alert/values.yaml#L162).

**Comment by Haleygo** [comment]
Close as completed.
