### ISSUE TITLE
How to use external configmap as vmauth config

### ISSUE THREAD

**Issue by sushovan23** [VictoriaMetrics/helm-charts#480]
In vmauth helm chart I see following:
``` 
-- Use existing configmap if specified otherwise .config values will be used. Ref: https://victoriametrics.github.io/vmauth.html
configMap: ""
```
however in documentation it doesn't tell me in anyway what that configMap needs to be like? Is there an example which I can refer on how to have pre-existing configmap?

Use case if to be able to update the configmap when new tenant in onboarded and reload vmauth without deploying the POD

**Comment by Haleygo** [comment]
Hello!
>In vmauth helm chart I see following:

I don't see such comment under victoria-metrics-auth chart, but in [victoria-metrics-gateway](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-gateway/values.yaml#L161) and [victoria-metrics-single](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-single/values.yaml#L359). Pardon me if I missed.
But if there is, it means:
1. if you already have a configmap created somewhere else, you can specify name in here;
2. if you don't provide this configmap name, it will create a new one using `.config`

**Comment by Haleygo** [comment]
Close as inactive, feel free to reopen if there is further question.
