### ISSUE TITLE
victoria-metrics-single service manifest is wrong

### ISSUE THREAD

**Issue by rootik** [VictoriaMetrics/helm-charts#491]
After struggling a couple of weeks with adoption VM as a backend for linkerd-viz I've found out that victoria-metrics service manifest is being incorrectly configured in helm chart code.

k8s Service manifest spec `targetPort` must match [Deployment manifest's hardcoded value](https://github.com/VictoriaMetrics/helm-charts/blob/78320ab53df0ca3442fe8e5cfd17711a8a381212/charts/victoria-metrics-single/templates/server-deployment.yaml#L72) `containerPort: 3428`

https://github.com/VictoriaMetrics/helm-charts/blob/78320ab53df0ca3442fe8e5cfd17711a8a381212/charts/victoria-metrics-single/templates/server-service.yaml#L37

Thanks

**Comment by Haleygo** [comment]
Hello! @rootik 
https://github.com/VictoriaMetrics/helm-charts/blob/78320ab53df0ca3442fe8e5cfd17711a8a381212/charts/victoria-metrics-single/templates/server-service.yaml#L37
This `targetPort` looks good to me, service `targetPort` do support using port name.

What do you mean by `containerPort: 3428`?

**Comment by Haleygo** [comment]
Close as inactive, feel free to reopen if there is further question.
