### ISSUE TITLE
VMagent helm is unable to connect  and scrape data from kube-state-metrics and node-exporter and send to prometheus master instance on other cluster

### ISSUE THREAD

**Issue by Muhammad-Shawaiz** [VictoriaMetrics/helm-charts#499]
I am trying to collect metrics   from all prometheus instances running in different clusters to a single prometheus  instance. I am using kube-prometheus-stack helm on each cluster. 

For that purpose, i want to just run vmagent using vmagent helm on each cluster which will scrape data from kube-state-metrics and node-exporter to vmagent and then send those metrics to prometheus master instance.

Please help me in configuration.

**Comment by zekker6** [comment]
@Muhammad-Shawaiz Please, check out default vmagent configuration here - https://github.com/VictoriaMetrics/helm-charts/blob/3311e775cc946449b9698bfdba4ed352daf7635c/charts/victoria-metrics-agent/values.yaml#L246

Default setup of vmagent will scrape pods with `prometheus.io/scrape: true`, so if you will set this label and configure scrape via `prometheus.io/port` and `prometheus.io/path` it will scrape targets you need to scrape.

You can use [`.Values.remoteWriteUrls`](https://github.com/VictoriaMetrics/helm-charts/blob/3311e775cc946449b9698bfdba4ed352daf7635c/charts/victoria-metrics-agent/values.yaml#LL68-L68C20) to configure targets to `remoteWrite` scraped data.

**Comment by Muhammad-Shawaiz** [comment]
@zekker6  how to would i be change it because i have tried to change and then write the remotewriteURL but it is still not working.

**Comment by zekker6** [comment]
@Muhammad-Shawaiz You need to point `remoteWriteUrl` to the master prometheus instance, not to vmagent.

I can suggest you to give a read to our [key concepts](https://docs.victoriametrics.com/keyConcepts.html) doc to get better understanding about this setup overall.

**Comment by Haleygo** [comment]
Close as inactive, feel free to reopen if there is further question.
