### ISSUE TITLE
[victoria-metrics-k8s-stack]  empty vmalert.spec.notifier creates bogus configuration.

### ISSUE THREAD

**Issue by b-a-t** [VictoriaMetrics/helm-charts#502]
I'm using ArgoCD ApplicationSet to deploy VM to the clusters. Due to the way templating works, it's easier for me to specify an empty resource line, rather than skip the parameter entirely.

So, for certain clusters I got:

```yaml
vmalert:
  spec:
    externalLabels:
       cluster: 'dev'
    notifier: { }
  ingress:
     enabled: true
...
```
The resulting command line is quite unexpected:
```
... -notifier.url=http://vmalertmanager-vm-stack.monitoring.svc:9093, -remoteRead.url=http://vmselect-vm-stack.monitoring.svc:8481/select/0/prometheus ...
```
Please note the comma after the first(default implicit) notifier. So, an empty map is creating an empty invisible URL, which is already not good.

But based on the following error message in the logs:
```json
{"ts":"2023-03-22T01:58:13.861Z","level":"error","caller":"VictoriaMetrics/app/vmalert/group.go:318","msg":"group \"vm-health\": errors(1): rule \"TooManyLogs\": failed to send alerts to addr \"/api/v2/alerts\": Post \"/api/v2/alerts\": unsupported protocol scheme \"\""}
```
that empty non-existing URL is still taken into account as URL and an attempt to write to it is performed.

So to me, there are two errors in the processing of the empty `notifier` field:

1. it is taken into account as a normal URL by YAML parsing code.
2. comma in the list of `-notifier.url` parameters also happily generates empty URL configuration.

So, IMHO in both places we need an additional sanity checks.

**Comment by b-a-t** [comment]
It seems I missed that there are both `notifier:` and `notifiers:` options for VMAlertSpec. But the behavior of `notifiers:` is also broken or non-intuitive...

Looking onto #431 I tried to use `notifiers:` instead and, from one side, I didn't get the same error, supplying `[]` as parameter to `notifiers:` worked OK:

```
vmalert:
  spec:
    notifiers: {{ hasPrefix "admin-" .name | ternary "[]" (regexReplaceAll "^(.+)$" .metadata.labels.environment "[ { url: https://alertmanager.admin-${1}.example.com } ]") }}
```
for admin cluster gave nice:
```
... -loggerFormat=json -notifier.url=http://vmalertmanager-vm-stack.monitoring.svc:9093 -remoteRead.url=http://vmselect-vm-stack.monitoring.svc:8481/select/0/prometheus ...
```
I.e. just left default vmalertmanager from the k8s-stack as notifier.

But, for the opposite case I got:
```
... -loggerFormat=json -notifier.url=https://alertmanager.admin-dev.example.com -remoteRead.url=http://vmsingle-vm-stack.monitoring.svc:8429/ ...
```
So, the local vmalertmanager was removed from the list of URLs. Possibly, it's intended behavior, but confusing at least, based on the description:

> Notifiers prometheus alertmanager endpoints. Required at least one of notifier or notifiers. e.g. http://127.0.0.1:9093 If specified both notifier and notifiers, notifier will be added as last element to notifiers. only one of notifier options could be chosen: notifierConfigRef or notifiers + notifier

So for the moment, I'm reverting to the use of `notifier:` as it gives me the behavior I expect(with caution).

**Comment by tenmozes** [comment]
@k1rk @f41gh7 @zekker6 @Amper could you please take a look?

**Comment by f41gh7** [comment]
I believe it's an issue at operator side. It must produce an error with empty value for `notifier: {}` setting.

**Comment by Haleygo** [comment]
Hello!

>Notifiers prometheus alertmanager endpoints. Required at least one of notifier or notifiers. e.g. http://127.0.0.1:9093/ If specified both notifier and notifiers, notifier will be added as last element to notifiers. only one of notifier options could be chosen: notifierConfigRef or notifiers + notifier

This description is for VMAlert CRD and it will work if you have both `notifier` and `notifiers` under .Values.vmalert.spec. 

But the default notifier `vmalertmanager-vm-stack.monitoring.svc:9093` you used is provided by this buildin template
https://github.com/VictoriaMetrics/helm-charts/blob/9e7356a142202a679cf84cb92bd9f48dd5cf1ef8/charts/victoria-metrics-k8s-stack/templates/_helpers.tpl#L124-L126
And it wil be overridden by `.Values.vmalert.spec.notifiers`.

>So to me, there are two errors in the processing of the empty notifier field:
it is taken into account as a normal URL by YAML parsing code.
comma in the list of -notifier.url parameters also happily generates empty URL configuration.

Yeah, p1 should be checked by vm-operator, and now [this check](https://github.com/VictoriaMetrics/operator/blob/master/api/v1beta1/vmalert_webhook.go#L35) is only supported by [validation admission webhook ](https://docs.victoriametrics.com/operator/configuration.html#crd-validation) now.

**Comment by AndrewChubatiuk** [comment]
to disable default `notifier.url` you need to set `alertmanager.enabled` to false otherwise notifiers will be appended to a default one. Also [this PR](https://github.com/VictoriaMetrics/helm-charts/pull/1272) will enable validation webhook (which is now disabled by default), so deployment will fail if `notifier` is empty.
