### ISSUE TITLE
kubernetes-mixin dashboard missing in recent releases of victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#511]
What happened to them?

**Comment by Amper** [comment]
Hi @brokenjacobs.
You can find answer in [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/484#issuecomment-1457194347)

**Comment by brokenjacobs** [comment]
Is the number reduced to zero? Because that is the behavior I am seeing now.

**Comment by brokenjacobs** [comment]
Older Deployment (20 dashboards, 15 from the mixin):
![image](https://user-images.githubusercontent.com/3159463/230984035-991847b5-052d-424e-9eb1-8d2f60de52f9.png)

Newer Deployment (3 dashboards....):
![image](https://user-images.githubusercontent.com/3159463/230983998-09601b16-db8d-4e0f-8291-92fe5b212b17.png)

**Comment by Amper** [comment]
@brokenjacobs you can see deleted dashboards in this commit: https://github.com/VictoriaMetrics/helm-charts/commit/128d2a7fa23c717e780655f03df83b03e3d637ac#diff-db5363d3b4e6885d694fef9d708a1a8373c928511d2508eef4d9b1b6959f37ef

**Comment by maxpain** [comment]
https://github.com/VictoriaMetrics/helm-charts/commit/128d2a7fa23c717e780655f03df83b03e3d637ac#diff-db5363d3b4e6885d694fef9d708a1a8373c928511d2508eef4d9b1b6959f37ef

@f41gh7 Why are these dashboards "useless"?
Is monitoring kubelet/apiserver/scheduler/controller-manager useless thing?
