### ISSUE TITLE
[victoriametrics-k8s-stack] Add option defaultRules.disabled for disabling rulse by name

### ISSUE THREAD

**Issue by Shm013** [VictoriaMetrics/helm-charts#517]
I want to disable some standard rules (`etcdHighNumberOfFailedGRPCRequests`) and replace it by my own rules with tweaks from: https://github.com/rancher/rancher/issues/29939

Is it good to add `defaultRules.disabled` parameter the same as in [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) chart? If it is I can create MR for this.

**Comment by zekker6** [comment]
Hi @Shm013 

You can disable all default rules by using: `.Values.defaultRules.create: false`, or disable only etcd rules with: `.Values.defaultRules.rules.etcd: false`.
Take a look at values here https://github.com/VictoriaMetrics/helm-charts/blob/7fad9529bb76d865f7e2dfd1c2b789a0380dded4/charts/victoria-metrics-k8s-stack/values.yaml#L36-L60

**Comment by Shm013** [comment]
@zekker6 I don't want to disable all alerts from etcd, I just want to disable only `etcdHighNumberOfFailedGRPCRequests`

**Comment by zekker6** [comment]
@Shm013 Ah, ok, understood. In this case could you please elaborate a bit more on this?

> Is it good to add defaultRules.disabled parameter the same as in [kube-prometheus-stack](https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack) chart? If it is I can create MR for this.

I'm not sure if I've understood what you would like to add to allow disabling a specific rule from the set.

**Comment by zekker6** [comment]
@Shm013 Thanks for the details, seems like a good improvement to me.

Rules in our repository are managed by a script which sync those to prometheus rules(you can find it [here](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack/hack)). 
Scripts in our repo were originally copied from Prometheus ones but lack support of creating conditions for specific alerts.
As far as I can see Prometheus has it implemented [here](
https://github.com/prometheus-community/helm-charts/blob/dd013b1ecc651491a778ae75c430345965657c18/charts/kube-prometheus-stack/hack/sync_prometheus_rules.py#L210-L247). 

Considering this, will you be interested in contributing, or it would be better if we will implement this?

**Comment by Shm013** [comment]
@zekker6 I think I can try implement this in next weekend. After that I want to figure out why exactly `etcdHighNumberOfFailedGRPCRequests` triggers on my system. Seems it something wrong with original alerts in Prometheus chart when using RKE2. Thank you for detailed tips!

**Comment by zekker6** [comment]
@Shm013 Thank you for the interest in fixing this!
If you find that this alert is not accurate feedback is much appreciated.
Also, if you will any help with implementing this feel free to join our public slack [here](https://slack.victoriametrics.com/) and ask for help there, we will be happy to assist.

**Comment by D3luxee** [comment]
I think i fixed this one with https://github.com/VictoriaMetrics/helm-charts/pull/678
It adds the option to disable individual default alert rules.

**Comment by Haleygo** [comment]
As @D3luxee mentioned, the fix is already included in [victoria-metrics-k8s-stack-0.18.6](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.18.6).
Close as completed.

**Comment by crazygit** [comment]
This not work in the latest versions

**Comment by AndrewChubatiuk** [comment]
@crazygit what exactly?

**Comment by AndrewChubatiuk** [comment]
there's no `defaultRules.disabled` property, you need to set `defaultRules.create: false`

**Comment by crazygit** [comment]
> there's no `defaultRules.disabled` property, you need to set `defaultRules.create: false`

Yes, how should I disabling rules by name now

**Comment by AndrewChubatiuk** [comment]
if you want to disable exact rule it should look like this `defaultRules.rules.<RuleName>.create: false`
if you want to disable a whole group: `defaultRules.groups.<groupName>.create: false`

**Comment by crazygit** [comment]
> defaultRules.rules.<RuleName>.create: false


Thank you very much for your patient response. I've tried all the methods you mentioned before, but only using `defaultRules.groups.<groupName>.create: false` to disable the entire group works effectively. Using `defaultRules.rules.<RuleName>.create: false` to disable a single rule doesn't work.

**Comment by crazygit** [comment]
> which rule have you tried to disable?

for examples

- `apiserver_request:burnrate3d`
- `apiserver_request:burnrate1d`
- `cluster_verb_scope:apiserver_request_sli_duration_seconds_count:increase30d`
- `cluster_verb_scope_le:apiserver_request_sli_duration_seconds_bucket:increase30d`

because these rules cause error like below

```
rule "apiserver_request:burnrate1d": failed to execute: original metric {[{cluster tra-dev}] [1730967045] [1.0084498008815868e-06]}; resulting labels "__name__=apiserver_request:burnrate1d,cluster=tra-dev,verb=read": result contains metrics with the same labelset during evaluation. See https://docs.victoriametrics.com/vmalert/#series-with-the-same-labelset for details
```

**Comment by crazygit** [comment]
> thanks for reporting this, it will be fixed in the next release, as now it impacts only alerts without touching recording rules

That's great! Looking forward to the changes being made soon. Thank you very much for your response.

**Comment by AndrewChubatiuk** [comment]
hey @crazygit 
0.28.3 should contain a fix, which allows to disable recording rules

**Comment by crazygit** [comment]
> hey @crazygit 0.28.3 should contain a fix, which allows to disable recording rules

Thank you very much!
