### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by tenmozes** [VictoriaMetrics/helm-charts#526]
We need to add 
- general information about every chart
- explanation of concepts, especially `extraArgs`
- more links between documentation helm charts <> VM docs <> operator docs

**Comment by Amper** [comment]
@tenmozes 

> general information about every chart
We have documentation on charts in the form of [README in repo](https://github.com/VictoriaMetrics/helm-charts/#readme) / [static website](https://victoriametrics.github.io/helm-charts/) and [pages on artifacthub](https://artifacthub.io/packages/search?repo=victoriametrics&sort=relevance&page=1) and we have links to it from our docs. It seems to me that this approach to helm charts documentation is generally accepted. Are you suggesting we start a separate section in [the documentation](https://docs.victoriametrics.com/) for helm charts?

> explanation of concepts, especially extraArgs
we already have this explanations, i.e.:
- https://docs.victoriametrics.com/operator/resources/#extra-arguments
- https://docs.victoriametrics.com/operator/resources/#managing-versions-of-vm
- https://docs.victoriametrics.com/operator/resources/#high-availability
- https://docs.victoriametrics.com/operator/resources/#basic-concepts
- https://docs.victoriametrics.com/operator/migration.html#objects-conversion
- https://docs.victoriametrics.com/operator/auth.html

a description of what concepts are missing?

> more links between documentation helm charts <> VM docs <> operator docs

I think we should start with adding links from VM docs to operator docs, it will be really useful.

FYI: @Haleygo

**Comment by hagen1778** [comment]
Looks like we can try consolidating docs for helm charts at https://docs.victoriametrics.com/ 
In the same fashion as we did for operator here https://github.com/VictoriaMetrics/operator/pull/724
