### ISSUE TITLE
TLS support in `victoria-metrics-auth` chart

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/helm-charts#528]
At the moment health check scheme for vmauth is hardcoded in chart templates, and if a user has enabled TLS, the health check does not work.

More details: https://victoriametrics.slack.com/archives/CGZF1H6L9/p1683041088067339

**Comment by AndrewChubatiuk** [comment]
now protocol for all httpGet probes depends on extraArgs tls flag value
