### ISSUE TITLE
Unable to configure maxTime property in Vm storage as we want to load future data in to metrics

### ISSUE THREAD

**Issue by pavanmallepudi** [VictoriaMetrics/helm-charts#539]
Tried passing maxTime like below in values.yaml but its not working .

vm-storage:
 maxTime:XXXXXXXXXXXXXXXX(epoch value)

and we are getting below exception while inserting future dates in metric 
{"ts":"2023-05-17T18:41:05.159Z","level":"warn","caller":"VictoriaMetrics/lib/storage/storage.go:1995","msg":"warn occurred during rows addition: cannot insert row with too big timestamp 1685914800000 exceeding the current time; maximum allowed timestamp is 1684521664000

**Comment by zekker6** [comment]
@pavanmallepudi There is no such parameter as `maxTime` in VM components.
Inserting in data in future might cause issues with data rotation, please give a read to the following issue: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/827

**Comment by Haleygo** [comment]
Close as inactive, feel free to reopen if there is further question.
