### ISSUE TITLE
The release artifact is rebuilt with different content

### ISSUE THREAD

**Issue by farcop** [VictoriaMetrics/helm-charts#547]
It is not possible to use the latest release artifact in hermetic builds because it is rebuilt with the same number but different archive content.

For example https://github.com/VictoriaMetrics/helm-charts/raw/master/packages/victoria-metrics-alert-0.6.1.tgz

`ERROR: /home/jenkins/agent/bazel-build/kublr-feature-monitoring/BUILD.bazel:4:11: //kublr-feature-monitoring:helm-chart depends on @victoria-metrics-alert.tgz//file:file in repository @victoria-metrics-alert.tgz which failed to fetch. no such package '@victoria-metrics-alert.tgz//file': java.io.IOException: Error downloading [https://github.com/VictoriaMetrics/helm-charts/raw/master/packages/victoria-metrics-alert-0.6.1.tgz] to /home/jenkins/agent/bazel-build@tmp/bazel-cache-user-root/kublr-workspace-output-base/external/victoria-metrics-alert.tgz/file/downloaded: Checksum was e41ebf40f8607233ef48e0345a5c1b9000a2c19a838da4b319fd24d18762824d but wanted 0f6b53111d6aff59d048c07d6a08f3bda4f8d6101f670ec8be81593fcf46d69f`

**Comment by tenmozes** [comment]
@farcop we changed the logic of the generation of a new version of packages and bumped all versions of charts. The problem should be fixed

feel free to reopen an issue if problem still exists on your side
