### ISSUE TITLE
Can I mount prometheus.yml on victoria-metrics-single?

### ISSUE THREAD

**Issue by ledmonster** [VictoriaMetrics/helm-charts#56]
I found `extraConfigmapMounts` parameter is used in [server-deployment.yaml](https://github.com/VictoriaMetrics/helm-charts/blob/d2ace6c/charts/victoria-metrics-single/templates/server-deployment.yaml), but volumes are not configured there. Should I modify chart to use prometheus.yml with victoria-metrics-single?

**Comment by tenmozes** [comment]
VictoriaMetrics doesn't support yaml configuration as for now (now several part of it for scrapping and relabling)
please check https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-single/values.yaml all configuration can be found there.

**Comment by belm0** [comment]
I'd like the VM chart to support `serverFiles` / `prometheus.yml` similar to the Prometheus chart.

**Comment by ledmonster** [comment]
@tenmozes I see. Now, I copied `prometheus.yml` to storage directly, and it works.
