### ISSUE TITLE
Invalid value: "victoria-metrics-victoria-metrics-k8s-stack-kube-controller-manager": must be no more than 63 characters

### ISSUE THREAD

**Issue by jtpham-zai** [VictoriaMetrics/helm-charts#564]
For some reason, this name is not truncated. I installed using the k8s-stack helm chart.

**Comment by joshua-baron** [comment]
Did you install using Argocd?

**Comment by sibuthomasmathew** [comment]
> Did you install using Argocd?

I fit the same issue and yes when deploying using ArgoCD.

**Comment by sibuthomasmathew** [comment]
For reference, here's the full error message
` 
Message:      one or more objects failed to apply, reason: ConfigMap "victoria-metrics-victoria-metrics-k8s-stack-victoriametrics-clu" is invalid: metadata.annotations: Too long: must have at most 262144 bytes,Service "victoria-metrics-victoria-metrics-k8s-stack-kube-controller-man" is invalid: metadata.labels: Invalid value: "victoria-metrics-victoria-metrics-k8s-stack-kube-controller-manager": must be no more than 63 characters (retried 5 times).
`

**Comment by Haleygo** [comment]
@sibuthomasmathew Sorry, I'm not familiar with ArgoCD. I see some [issues](https://github.com/argoproj/argo-cd/issues/10843) in their community maybe releated, and there is a [fix](https://github.com/argoproj/argo-cd/issues/4045).

**Comment by sibuthomasmathew** [comment]
It turns out the issue with `configmap` is related to ArgoCD while the issue with `service` is present when deploying manually too:
```bash
$ sudo helm install victoria-metrics vm/victoria-metrics-k8s-stack -f values.yaml -n monitoring --create-namespace
Error: INSTALLATION FAILED: 1 error occurred:
	* Service "victoria-metrics-victoria-metrics-k8s-stack-kube-controller-man" is invalid: metadata.labels: Invalid value: "victoria-metrics-victoria-metrics-k8s-stack-kube-controller-manager": must be no more than 63 characters


$
```

The issue above was worked around by either using a smaller `release-name` or adding `nameOverride` in the values file.

Anyway, thanks a lot @Haleygo !

**Comment by sibuthomasmathew** [comment]
Here's the error thrown when deploying one of the `configmap` using ArgoCD:

`reason: ConfigMap "victoria-metrics-victoria-metrics-k8s-stack-victoriametrics-clu" is invalid: metadata.annotations: Too long: must have at most 262144 bytes`

This can be resolved by instructing ArgoCD to use "Server Side Apply"; thanks to [this](https://www.arthurkoziel.com/fixing-argocd-crd-too-long-error/) blog post
