### ISSUE TITLE
Feature request: CRD installation option in the vmsingle chart

### ISSUE THREAD

**Issue by djfinnoy** [VictoriaMetrics/helm-charts#565]
I prefer helm installations over operators. I also prefer to use the individual helm charts instead of the k8s-stack chart because it gives me a minimal, streamlined installation.

I want to use the VMAlert CRD, but there are no straightforward ways for me to install them using only Helm (I would have to use kustomize instead).

Could we please add an option to install user specified CRDs via the vmsingle helm chart?

**Comment by zekker6** [comment]
@djfinnoy Did you consider using vm-operator [helm chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator) to install operator without kustomize?

**Comment by djfinnoy** [comment]
I considered it briefly, but I think it would be a bit fiddly to limit the operator to only installing CRD's and no other resources. I would prefer to use kustomize than constricting the operator to CRDs to be honest.

**Comment by Haleygo** [comment]
>Could we please add an option to install user specified CRDs via the vmsingle helm chart?

@djfinnoy Sorry, I don't see why should CRD be contained in vmsingle helm chart, since it has nothing to do with it.
If you want to use vmalert cr, it must has vm operator in your cluster, so why don't you want to use vm-operator [helm chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator) to install it? Can you elaborate the case?

**Comment by djfinnoy** [comment]
Sure. So our use case is that we have a Victoria Metrics installation that is *as minimal as possible*. We install the following Helm charts via ArgoCD:
- vmsingle
- vmagent
- vmalert
- vmauth

We strongly prefer this approach, because we find the operator too bloated; 90% of what it installs is not something we intend to use, and it is so big it has performance implications on ArgoCD. Our approach gives us exactly what we need, and we get a nice, slim installation that is easy for engineers to understand within the ArgoCD UI.

The only downside to this approach is that we don't get any of the CRDs, so we are limited to defining our alert rules through the `vmalert` helm values. What we originally wanted to do was to define alert rules in the same places we write application configuration. For example, if `app-a` needs to have a unique alert, this alert now has to live under the `vmalert` config dir, instead of under the `app-a` config directory. If we were able to use a CRD to define an alert rule, this limitation would go away.

If I understand you correctly, the alert CRD won't work without an operator installation. If that is the case then I'm happy to close this issue, and perhaps replace it with a feature request for a CRD intended to work with `vmalert` without requiring an operator installation.

**Comment by Haleygo** [comment]
>If I understand you correctly, the alert CRD won't work without an operator installation.

Yes, that's what operator do, they are bundled.
See more info [here](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/).
