### ISSUE TITLE
How to automatic reload config for alertmanager in victoria-metrics-alert chart?

### ISSUE THREAD

**Issue by unitrade** [VictoriaMetrics/helm-charts#570]
Hi, I am newer for using victoriametrics
I am using victoria-metrics-alert chart in my k8s cluster.
I setup my config through configMap for alertmanager, but if update config - I don't see any updates
vmalert server reloads fine (it has configCheckInterval) but alertmanager does not have.
How to automatic reload config for alertmanager in this chart?
Thank you

**Comment by Haleygo** [comment]
Hello! @unitrade 
victoria-metrics-alert chart doesn't attach reloader container or support adding extra container for alertmanager now.
Can you try [victoria-metrics-k8s-stack ](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack), it uses `vmalertmanager` which can generate statefulset[for alertmanager cluster] for alertmanager, config-reloader included.

**Comment by Haleygo** [comment]
Close as inactive, feel free to reopen if there is further question.
