### ISSUE TITLE
Victoria Metrics Single Server remoteWrite?

### ISSUE THREAD

**Issue by ericsheris-rumble** [VictoriaMetrics/helm-charts#571]
Hello,
In a few different places on the victoria metrics site, it mentions that the single binary server can be a drop in replacement for prometheus. I have set up VM distributed on its own cluster, and i was hoping to replace my prometheus installs on other clusters with the VM single binary helm chart. I currently use prometheus and keda to manage scaling based on custom metrics, so I need something in cluster for keda to query for scaling and it seemed that VM was a good answer. As far as i know the agent itself can not be queried like a standard prometheus server and I would prefer to not have keda reaching out across the internet (and find it self victim of some outage) so I would like to keep the scaling queries in cluster.

After all that, i'm trying to figure out how to set a remote write url for VM single binary to write to my vm distributed cluster. I don't see anything in the chart values and haven't found anything in docs or in the open/closed issues here.

Thanks!

For reference, i'm trying to use this chart:
https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-single
and I created the values file i'm using by following the instructions on that page issuing the `helm show values vm/victoria-metrics-single > values.yaml` command

**Comment by Haleygo** [comment]
> As far as i know the agent itself can not be queried like a standard prometheus server

Yeah, vmagent is a tiny agent which helps you collect metrics from various sources, [relabel and filter the collected metrics](https://docs.victoriametrics.com/vmagent.html#relabeling) and store them in [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics) or any other storage systems via Prometheus remote_write protocol. 

>After all that, i'm trying to figure out how to set a remote write url for VM single binary to write to my vm distributed cluster. I don't see anything in the chart values and haven't found anything in docs or in the open/closed issues here.

vmsingle doesn't support remote write to other storage for now. 
I think you can deploy both vmagent and vmsingle on your cluster, [victoria-metrics-k8s-stack chart](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack) can manage that. Using vmagent to write data to local vmsingle and distributed vmcluster[you will find that they are still smaller than prometheus resource)]

**Comment by hagen1778** [comment]
Closing this issue as answered [here](https://github.com/VictoriaMetrics/helm-charts/issues/571#issuecomment-1641206207).
