### ISSUE TITLE
Stack doesn't allow customising operator VMServiceScrape

### ISSUE THREAD

**Issue by holmesb** [VictoriaMetrics/helm-charts#588]
Hi,

Unlike the victoria-metrics-operator [chart](https://github.com/VictoriaMetrics/helm-charts/blob/82b09f658fbd6fe03b067fb28a6836b4cfd8927b/charts/victoria-metrics-operator/templates/service_scrape.yaml#L23), the victoria-metrics-k8s-stack one doesn't allow customising the operator vmServiceScrape [resource](https://github.com/VictoriaMetrics/helm-charts/blob/82b09f658fbd6fe03b067fb28a6836b4cfd8927b/charts/victoria-metrics-k8s-stack/templates/victoria-metrics-operator/servicescrape.yaml#L13). Eg cannot add relabelings. 

Also neither allow adding metricRelabelings.

Cheers.

**Comment by Haleygo** [comment]
@holmesb Thanks for reporting this, feel free to pull a request if you like)

**Comment by AndrewChubatiuk** [comment]
hey @holmesb 
victoria-metrics-k8s-stack chart embeds victoria-metrics-operator, so all its properties are available in victoria-metrics-k8s-chart under `victoria-metrics-operator`. serviceScrape configs are available at `victoria-metrics-operator.serviceMonitor`. Added PR with updates to service scrape and to show more information in README
