### ISSUE TITLE
helm chart size optimization

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/helm-charts#590]
So far, helm charts for k8s stack could exceed allowed size limit. This prevents us from adding default dashboards that users might need. Would be great if we find a workaround for this. For example, to create a sub-charts for dashboards. 

This issue requires a proper research to check if proposed solution is efficient.

**Comment by Haleygo** [comment]
Helm v3 stores chart state in a kubernetes secret by default and secret are limited to 1M based on etcd’s configuration. Helm has this issue from the very beginning[like [8281](https://github.com/helm/helm/issues/8281), [1413](https://github.com/helm/helm/issues/1413)] and there is some proposal like [split release data into multiple secrets](https://github.com/helm/helm/issues/10986), but never got merged or solved.
The data in release secret is compressed and decoded, means that chart itself can be bigger then 1M as long as the secret of deployed release is less than 1M. 
I deployed the latest 0.17.3 using default values.yaml. The vm-k8s-stack-chart size is 4.4M, and the secret created by helm is 966K[vm-stack-release.json]. [Helm will compress the data by gzip and base64-encode once](https://github.com/helm/helm/blob/main/pkg/storage/driver/util.go#L35-L51) and secrets API will base64-encode again, so we can get the real data stored in etcd by `cat vm-stack-release.json｜ jq .data.release | tr -d '"' | base64 -d`, which size is 724k[vm-stack-raw-data-in-etcd.json], means we still got some buffer under default installation)
![image 2 3 4](https://github.com/VictoriaMetrics/helm-charts/assets/39937150/1960a5d0-148d-48ca-a632-63313c73f4fa)
To gain the full raw data of the helm release, decode the vm-stack-release.json by `cat vm-stack-release.json｜ jq .data.release | tr -d '"' | base64 -d | base64 -d | gzip -d`, using some json analyser and get below data:
![image 2 2](https://github.com/VictoriaMetrics/helm-charts/assets/39937150/84a28572-abcd-4267-905f-7e24dd952573)
![image 2 3 2](https://github.com/VictoriaMetrics/helm-charts/assets/39937150/3d098951-e431-4f14-a950-bcc92c88aed6)
The top two size eater are “templates” and “manifest”:
1. “templates” stores all the resources under `charts/victoria-metrics-k8s-stack/templates`, field `data` is the content of each resource yaml after base64
2. “manifest” stores resources created by release in cluster, like deployment, configmap. So some resources defined in chart won’t be created by using default values.yaml, but the worst scenario will be users enable all the available resources, that will increase the “manifest” size up to about “templates” size, which could exceed 1M.

There are several available solutions:
1. Helm [supports](https://helm.sh/docs/topics/advanced/#sql-storage-backend) alternative storage schemes such as a SQL backend, that can bypasses this limit as long as that backend doesn’t have size limit[But no one will use]
2. Split the chart[to decrease the size of “templates” and “manifest”]: 
   1. Into total different chart and install separately, that will decrease both “templates” and “manifest” size of vm-k8s-stack,but make installation complicated.
   2. Into subchart, this will only decrease the “templates” size. 
      For examples, if we split the crd yaml under `charts/victoria-metrics-k8s-stack/crds`and grafana dashboards yaml under `charts/victoria-metrics-k8s-stack/templates/grafana` to independent charts like crd-charts, dashboard-charts.
![image 2 3 4 5 6](https://github.com/VictoriaMetrics/helm-charts/assets/39937150/b2cf2c0e-ee2e-4449-98c8-22806217d2a5)
      And the results looks good[split creates more dashboard cause I deleted all the creation check conditions]
<img width="1350" alt="image 2 3 4 5" src="https://github.com/VictoriaMetrics/helm-charts/assets/39937150/13d63c5d-2f09-4648-900c-a7777d6df8e3">

cc @hagen1778 @f41gh7 @Amper

**Comment by Haleygo** [comment]
> That's a great investigation! Thank you @Haleygo ! Do I understand it right, that we should proceed with subcharts approach? If yes, what drawbacks we and users should expect?

Yes, I'm testing with the move.
AFAIK, there is no drawback for spliting subchart, helm will only honor rendered resources files under manifests when `upgrade/rollback/uninstall`, there is no warning in their subchart [docs](https://helm.sh/docs/chart_template_guide/subcharts_and_globals) and I checked the [code](https://github.com/helm/helm/blob/master/pkg/chart/chart.go#L35), `Templates` `Files` are used for `helm show` `helm package`, thus redundant for release secrets.
To us, there are some values need to be rewrite cause subchart can't use global values, [tpl](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#sharing-templates-with-subcharts) can be share though.

**Comment by hagen1778** [comment]
@f41gh7 @Amper you have more expertise on this, wdyt?

**Comment by Haleygo** [comment]
Attach the compared data above.
[after-split.zip](https://github.com/VictoriaMetrics/helm-charts/files/12238670/after-split.zip)
[before split.zip](https://github.com/VictoriaMetrics/helm-charts/files/12238673/before.split.zip)

**Comment by f41gh7** [comment]
> @f41gh7 @Amper you have more expertise on this than me, wdyt?

Have no objections. Solution with subchart looks really good to me. 

 But, I think, we have to keep crd at the main chart. Since, it's really painful to manage and upgrade via helm.

**Comment by Haleygo** [comment]
The fix is included in victoria-metrics-k8s-stack 0.17.5, close as complete.
