### ISSUE TITLE
incorrect removal of components due to incorrect work of finalizers

### ISSUE THREAD

**Issue by Nello-Angelo** [VictoriaMetrics/helm-charts#591]
Always when i try to delete chart the finalizers cant finish correct and because of that i cant delete namespace with victoria metrics components

To Reproduce
install chart and delete release and you will see that kubernetes delete correct only dependencies charts

Version
the latest

Logs
No response

Screenshots
![254707929-dccb5f55-fe56-4803-aa9a-51cdf6c4fc79](https://github.com/VictoriaMetrics/helm-charts/assets/82488489/28170ef0-6905-4bd9-9505-dc6edcecb0e7)

Used command-line flags
i delete via helm and lens

Additional information
i use [victoria-metrics-k8s-stack](https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-k8s-stack)
if you want i can show the problem in discord

**Comment by Haleygo** [comment]
Hello, I still don't understand what's the resource refered in your screenshot.
>install chart and delete release
Delete release means "helm uninstall", right? 
Does the release uninstalled successfully? You should see a clean up job during the uninstall process, and you can check the log for more info.

**Comment by Nello-Angelo** [comment]
statefulset and i cant delete a resource and edit because of Loading resource failed: {"error":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404},"messages":["the server could not find the requested resource"],"isUsedForNotification":false}

**Comment by Nello-Angelo** [comment]
i resolved my problem with kubectl edit
