### ISSUE TITLE
Kubernetes compatibility version

### ISSUE THREAD

**Issue by antoinedeschenes** [VictoriaMetrics/helm-charts#594]
Hi, I assume this information isn't accurate in the README.md file?
> helm charts tested at kubernetes versions from 1.13 to 1.22.

**Comment by zekker6** [comment]
Hi @antoinedeschenes 
Yes, that's true. We are testing charts in CI here - https://github.com/VictoriaMetrics/helm-charts/blob/master/.github/workflows/run-testing.yaml, CI is using k8s 1.24-1.27 versions to run tests.

**Comment by Haleygo** [comment]
Updated in https://github.com/VictoriaMetrics/helm-charts/commit/d1ab3bd6d6117a37afa1d3f0d2b893d6661b6651, close as completed
