### ISSUE TITLE
Can't install chart version 0.3.0

### ISSUE THREAD

**Issue by ThePants999** [VictoriaMetrics/helm-charts#6]
helm install my-release vm/victoria-metrics-cluster --dry-run
Error: YAML parse error on victoria-metrics-cluster/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key

This was with Helm 3, but I do get the same error with Helm 2. (Not during dry run - Helm 2 happily does a dry run but gives the error above when you attempt a real install. Helm 3 gives the error either way.)

**Comment by kostyaplis** [comment]
Same error installing cluster with terraform helm provider.
```
Error: rpc error: code = Unknown desc = YAML parse error on victoria-metrics-cluster/templates/clusterrole.yaml: error converting YAML to JSON: yaml: line 7: did not find expected key
```

**Comment by tenmozes** [comment]
hello thanks for a report will fix ASAP

**Comment by tenmozes** [comment]
fixed, please update repo

**Comment by kostyaplis** [comment]
Confirm. Works now. Thanks!

**Comment by tenmozes** [comment]
@kostyaplis thank you, closing an issue, feel free to reopen
