### ISSUE TITLE
Changing vmstorage.persistentVolume.size has no effect

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/helm-charts#60]
Hey,

I am deploying the cluster version helm charts, in aws on ec2.
When trying to increase storage for vmstorage in configuration vmstorage.persistentVolume.size, it has no effect.
At the moment it has the value of `size: 8Gi` and I can see there are 2 EBS with capacity of 8GiB (I have 2 replicas for vmstorage), when increasing it to `size: 16Gi`and running helm upgrade it upgrades successfully but nothing is changed in the EBS and the nodes still have connected ebs with only 8 GiB.

Am I doing something wrong?
Thanks! 

UPDATE:
After playing with it a bit more I am now getting this error when trying to update the size paramter:
`Error: UPGRADE FAILED: cannot patch "victoria-victoria-metrics-cluster-vmstorage" with kind StatefulSet: StatefulSet.apps "victoria-victoria-metrics-cluster-vmstorage" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden`

How can I increase the size of the EBS?

**Comment by f41gh7** [comment]
Hello, it's a kubernetes issue, changing size of `volumeClaimTemplates` is not supported for statefulsets. 

https://github.com/kubernetes/kubernetes/issues/68737

 There are few workarounds:

https://github.com/kubernetes/kubernetes/issues/68737#issuecomment-498470138

**Comment by Alon-Katz** [comment]
Thanks! I will try those workaround.
I will close the issue because its not VictoriaMetrics problem.
