### ISSUE TITLE
[victoria-metrics-k8s-stack] Update VMRule in node-exporter

### ISSUE THREAD

**Issue by Denissa89** [VictoriaMetrics/helm-charts#605]
I noticed that the [rules](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/rules/node-exporter.yaml) generate from kube-prometheus [repo](https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/manifests/nodeExporter-prometheusRule.yaml).
At the moment, these rules are behind prometheus-operator.
Please synchronize rules them on the chart

**Comment by Amper** [comment]
Released at [0.18.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.18.0)
