### ISSUE TITLE
Consider to add minReadySeconds parameter for vmstorage StatefulSet

### ISSUE THREAD

**Issue by darthcorsair** [VictoriaMetrics/helm-charts#608]
it would be nice to have [minReadySeconds parameter](https://kubernetes.io/blog/2021/08/27/minreadyseconds-statefulsets/) for more graceful vmstorage redeploys on updates

**Comment by Amper** [comment]
Implemented in operator [v0.40.0](https://github.com/VictoriaMetrics/operator/releases/tag/v0.40.0)
