### ISSUE TITLE
cadvisor: set `honor_timestamps` to false by default

### ISSUE THREAD

**Issue by hagen1778** [VictoriaMetrics/helm-charts#612]
The issue is a follow-up after https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1656550287

The motivation to set `honor_timestamps` to false by default is explained [here](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/4697#issuecomment-1656540535).

**Comment by hagen1778** [comment]
cc @f41gh7

**Comment by BongoEADGC6** [comment]
honorTimestamps throws an error with victoria-metrics-agent chart version 0.9.5. I believe this expects honor_timestamps in its place.

**Comment by Haleygo** [comment]
> disable honorTimestamps for cadvisor by default #617

@BongoEADGC6 Thanks, should be fixed in https://github.com/VictoriaMetrics/helm-charts/pull/626.

**Comment by hagen1778** [comment]
Thanks @Haleygo !
The change is available starting from https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/CHANGELOG.md#096
