### ISSUE TITLE
Duplicate Scrape Target Error on Kube-DNS

### ISSUE THREAD

**Issue by silverbp** [VictoriaMetrics/helm-charts#65]
We're getting this error with the default configuration in helm when installing in k8s in AWS (EKS).

error	VictoriaMetrics/lib/promscrape/scraper.go:269	skipping duplicate scrape target with identical labels; endpoint=http://10.100.30.94:9153/metrics, labels={eks_amazonaws_com_component="kube-dns", instance="10.100.30.94:9153", job="kubernetes-service-endpoints", k8s_app="kube-dns", k8s_cluster_name="k8s-devops", kubernetes_io_cluster_service="true", kubernetes_io_name="CoreDNS", kubernetes_name="kube-dns", kubernetes_namespace="kube-system", kubernetes_node="ip-10-100-30-216.us-east-2.compute.internal"}; make sure service discovery and relabeling is set up properly

I haven't figured how how to fix this one yet as the documentation has suggestions for fixing this issue when it comes up on a pod. However, it would be great if the default config worked with core k8s components out of the box without logging errors.

**Comment by tenmozes** [comment]
hello @silverbp please check the https://github.com/VictoriaMetrics/VictoriaMetrics/tree/master/app/vmagent#troubleshooting 

section:
```
If you see skipping duplicate scrape target with identical labels errors when scraping Kubernetes pods, then it is likely these pods listen multiple ports or they use init container.
```

**Comment by silverbp** [comment]
@tenmozes this error is coming up in the kubernetes-service-endpoints job, not the pod job.

**Comment by silverbp** [comment]
we're using the default config that's in helm.

**Comment by tenmozes** [comment]
@valyala could you pleas take a look?

**Comment by silverbp** [comment]
for context, this is the kube-dns service definition in k8s.

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9153","prometheus.io/scrape":"true"},"labels":{"eks.amazonaws.com/component":"kube-dns","k8s-app":"kube-dns","kubernetes.io/cluster-service":"true","kubernetes.io/name":"CoreDNS"},"name":"kube-dns","namespace":"kube-system"},"spec":{"clusterIP":"172.20.0.10","ports":[{"name":"dns","port":53,"protocol":"UDP"},{"name":"dns-tcp","port":53,"protocol":"TCP"}],"selector":{"k8s-app":"kube-dns"}}}
    prometheus.io/port: "9153"
    prometheus.io/scrape: "true"
  creationTimestamp: "2020-05-01T20:23:46Z"
  labels:
    eks.amazonaws.com/component: kube-dns
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "173"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: b7fb0c9a-5e7c-4f90-ad8b-03d2567fbe1d
spec:
  clusterIP: 172.20.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

**Comment by silverbp** [comment]
if you add the following to the endpoint it gets rid of the issue as there are multiple ports without a label identifying that, but maybe we don't want to pull these targets regardless. not sure..

        - source_labels: [__meta_kubernetes_endpoint_port_name]
          action: replace
          target_label: kubernetes_endpoint_port_name

there's essentially a tcp and udp port on that service which is why it logs the error

**Comment by silverbp** [comment]
actually, I think it's just returning two and you really only want one, but you don't really have a way to say only take this one, you're logic you're applying in the MR I think will get rid of both of them..

**Comment by silverbp** [comment]
```
eks_amazonaws_com_component="kube-dns"
exported_kubernetes_namespace="kube-system"
instance="10.100.30.94:9153"
job="kubernetes-service-endpoints"
k8s_app="kube-dns"
k8s_cluster_name="k8s-devops"
kubernetes_endpoint_address_target_kind="Pod"
kubernetes_endpoint_address_target_name="coredns-bd44f767b-crsr4"
kubernetes_endpoint_node_name="ip-10-100-30-216.us-east-2.compute.internal"
kubernetes_endpoint_port_name="dns"
kubernetes_endpoint_port_protocol="UDP"
kubernetes_endpoint_ready="true"
kubernetes_endpoints_name="kube-dns"
kubernetes_io_cluster_service="true"
kubernetes_io_name="CoreDNS"
kubernetes_name="kube-dns"
kubernetes_namespace="kube-system"
kubernetes_node="ip-10-100-30-216.us-east-2.compute.internal"
kubernetes_pod_annotation_eks_amazonaws_com_compute_type="ec2"
kubernetes_pod_annotation_kubernetes_io_psp="eks.privileged"
kubernetes_pod_annotationpresent_eks_amazonaws_com_compute_type="true"
kubernetes_pod_annotationpresent_kubernetes_io_psp="true"
kubernetes_pod_container_name="coredns"
kubernetes_pod_container_port_name="dns"
kubernetes_pod_container_port_number="53"
kubernetes_pod_container_port_protocol="UDP"
kubernetes_pod_controller_kind="ReplicaSet"
kubernetes_pod_controller_name="coredns-bd44f767b"
kubernetes_pod_host_ip="10.100.30.216"
```

**Comment by silverbp** [comment]
```
eks_amazonaws_com_component="kube-dns"
exported_kubernetes_namespace="kube-system"
instance="10.100.30.94:9153"
job="kubernetes-service-endpoints"
k8s_app="kube-dns"
k8s_cluster_name="k8s-devops"
kubernetes_endpoint_address_target_kind="Pod"
kubernetes_endpoint_address_target_name="coredns-bd44f767b-crsr4"
kubernetes_endpoint_node_name="ip-10-100-30-216.us-east-2.compute.internal"
kubernetes_endpoint_port_name="dns-tcp"
kubernetes_endpoint_port_protocol="TCP"
kubernetes_endpoint_ready="true"
kubernetes_endpoints_name="kube-dns"
kubernetes_io_cluster_service="true"
kubernetes_io_name="CoreDNS"
kubernetes_name="kube-dns"
kubernetes_namespace="kube-system"
kubernetes_node="ip-10-100-30-216.us-east-2.compute.internal"
kubernetes_pod_annotation_eks_amazonaws_com_compute_type="ec2"
kubernetes_pod_annotation_kubernetes_io_psp="eks.privileged"
kubernetes_pod_annotationpresent_eks_amazonaws_com_compute_type="true"
kubernetes_pod_annotationpresent_kubernetes_io_psp="true"
kubernetes_pod_container_name="coredns"
kubernetes_pod_container_port_name="dns"
kubernetes_pod_container_port_number="53"
kubernetes_pod_container_port_protocol="UDP"
kubernetes_pod_controller_kind="ReplicaSet"
kubernetes_pod_controller_name="coredns-bd44f767b"
kubernetes_pod_host_ip="10.100.30.216"
```

**Comment by silverbp** [comment]
the only diff between those two is this

```
kubernetes_endpoint_port_name="dns-tcp"
kubernetes_endpoint_port_protocol="TCP"
```

**Comment by silverbp** [comment]
I guess I could explicitly drop it if it's kube-dns and has that second name..

**Comment by silverbp** [comment]
It seems like the application is doing what it should and dropping duplicate errors and instead they shouldn't be logged as errors.

**Comment by f41gh7** [comment]
Basically, Kubernetes service discovery configuration produces as many target, as unique combination of port you have.

 For instance, lets image you have 1 service, backed by 1 pod with 2 ports. Also, this pod has initContainer with 1 port.

 You added two annotations to this service: `prometheus.io/port:` and `prometheus.io/scrape: `.

 After service discovery you will have 3 targets (2 container ports and 1 init container port).

 With improper relabelConfig ( something like labelmap __meta__(.+), replace: $1), you will get x3 metrics per pod. In this case all three targets will have unique labels combinations and the same scraping address.

**Comment by silverbp** [comment]
yup, I was able to get it the issue resolved or eliminate the error by having it drop one of the kube-dns ports. I just think it would be ideal to have a configuration option that allowed you to ignore those errors. Then you wouldn't have to worry about making it so that you only got one target. You could just set your labels up so you only got one and the duplicates would be eliminated by victoria without having to do anything else.

**Comment by silverbp** [comment]
by ignore those errors, I mean, don't log them as an error or probably even at all or the logs would get pretty verbose..

**Comment by valyala** [comment]
> I just think it would be ideal to have a configuration option that allowed you to ignore those errors. Then you wouldn't have to worry about making it so that you only got one target. You could just set your labels up so you only got one and the duplicates would be eliminated by victoria without having to do anything else.

VictoriaMetrics already leaves only a single target if it sees duplicate targets with identical set of labels. I don't think it is good idea to suppress such errors, since they point to improper configuration for relabeling, which must be investigated and fixed instead of silently ignored.

**Comment by f41gh7** [comment]
`-promscrape.suppressDuplicateScrapeTargetErrors` flag must fix it.
