### ISSUE TITLE
[victoria-metrics-k8s-stack] upgrade kube-state-metrics to newer version

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#658]
There is support for monitoring CustomResourceDefinition objects that is used by flux now:
https://fluxcd.io/flux/monitoring/custom-metrics/

The version of the chart used by victoria-metrics-k8s-stack is too old for this support

Thanks!

**Comment by Amper** [comment]
Released at [0.18.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.18.0)
