### ISSUE TITLE
no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"

### ISSUE THREAD

**Issue by mdesouky** [VictoriaMetrics/helm-charts#660]
Trying to deploy victoria-metric-single helm chart via terraform to our K8s 1.25 cluster and getting this error:
```
helm_release.victoria_metrics: Modifying... [id=victoria-metrics]
╷
│ Error: current release manifest contains removed kubernetes api(s) for this kubernetes version and it is therefore unable to build the kubernetes objects for performing the diff. error from kubernetes: unable to recognize "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
│ 
│   with helm_release.victoria_metrics,
│   on victoria-metrics.tf line 1, in resource "helm_release" "victoria_metrics":
│    1: resource "helm_release" "victoria_metrics" {
```

I think because the PodSecurityPolicy is no longer served in 1.25 as per the [docs](https://github.com/VictoriaMetrics/helm-charts/blob/victoria-metrics-single-0.9.6/charts/victoria-metrics-single/templates/podsecuritypolicy.yaml#L2)

**Comment by Haleygo** [comment]
Hello! Did you use the latest chart here? 
We got the api check from https://github.com/VictoriaMetrics/helm-charts/pull/393/commits/82bb750c660e2f0bff5473c63e9d03c3820ef5ae, and enhanced the compatiblity for ArgoCD in https://github.com/VictoriaMetrics/helm-charts/pull/506/commits/1b1873506d51f6520fbafc481fdb9fddb91b13fa, maybe terraform need to be treated differently too.

**Comment by hemstreet** [comment]
hey @mdesouky, I have run into the same issue. After some research, it looks like this is due to upgrading the cluster where that CRD gets deprecated and helm no longer knows how to handle it. This looks to be a relevant issue.

https://github.com/kubecost/cost-analyzer-helm-chart/issues/2225#issuecomment-1536424647

The short answer is you have to use [this ](https://github.com/helm/helm-mapkubeapis) to map the old CRD to something helm knows about so it can upgrade past this issue.

**Comment by Haleygo** [comment]
@mdesouky Have you tried the solution @hemstreet mentioned above?
It's not a bug from any place, you might have install the chart when your kubernetes<1.25 and then you upgrade the version. Now there are three ways to get pass:
1. downgrade Kubernetes back to a older version and do helm upgrade 
2. delete the release secret(s) and re-install your helm chart
3. using this [tool](https://github.com/helm/helm-mapkubeapis) to upgrade the Helm release metadata, then you can upgrade directly.

**Comment by mdesouky** [comment]
@hemstreet I tried your solution but in my case I got `No supported API equivalent`
```helm mapkubeapis --dry-run victoria-metrics
2024/03/12 16:31:38 NOTE: This is in dry-run mode, the following actions will not be executed.
2024/03/12 16:31:38 Run without --dry-run to take the actions described below:
2024/03/12 16:31:38 
2024/03/12 16:31:38 Release 'victoria-metrics' will be checked for deprecated or removed Kubernetes APIs and will be updated if necessary to supported API versions.
2024/03/12 16:31:38 Get release 'victoria-metrics' latest version.
2024/03/12 16:31:39 Check release 'victoria-metrics' for deprecated or removed APIs...
2024/03/12 16:31:39 Found 1 instances of deprecated or removed Kubernetes API:
"apiVersion: policy/v1beta1
kind: PodSecurityPolicy
"
No supported API equivalent
2024/03/12 16:31:39 Finished checking release 'victoria-metrics' for deprecated or removed APIs.
2024/03/12 16:31:39 Deprecated or removed APIs exist, for release: victoria-metrics.
2024/03/12 16:31:39 Map of release 'victoria-metrics' deprecated or removed APIs to supported versions, completed successfully.```

**Comment by mdesouky** [comment]
@Haleygo just tried solution 2️⃣ and re-installed the chart using terraform but it ended up in a `failed` state although terraform finished successfully.
When I tried another terraform apply I got these errors:
```
Error: cannot patch "victoria-metrics-victoria-metrics-single-server" with kind StatefulSet: StatefulSet.apps "victoria-metrics-victoria-metrics-single-server" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

**Comment by AndrewChubatiuk** [comment]
policy/v1beta1/PodSecurityPolicy was remove from all charts in the latest releases

**Comment by haseeb-aziz** [comment]
I am also have the same issue. Please me which solution is good.
