### ISSUE TITLE
Can I set search.maxStalenessInterval on a single node or cluster via Helm charts?

### ISSUE THREAD

**Issue by mnachmia31** [VictoriaMetrics/helm-charts#68]
We are looking into migrating from Influx to VictoriaMetrics but need to be able to suppress staleness calculations. Would I be able to set these configuration flags outlined here in the Helm chart as I do not see them referenced:

https://hub.docker.com/r/victoriametrics/victoria-metrics

**Comment by f41gh7** [comment]
Hello,  for Single version you can set it with flags:
```helm upgrade -i -set server.extraArgs.search\.maxStalenessInterval=1m vms vm/victoria-metrics-single```

For cluster version:
```helm upgrade -i  -set vmselect.extraArgs.search\.maxStalenessInterval=1m vms vm/victoria-metrics-cluster```

**Comment by mnachmia31** [comment]
@f41gh7 thanks for the prompt response. Out of curiosity is it possible to accomplish it via env variables as well?

**Comment by f41gh7** [comment]
It's not possible with helm, unfortunately.
