### ISSUE TITLE
victoria-metrics-cluster: add configmap support

### ISSUE THREAD

**Issue by aloababa** [VictoriaMetrics/helm-charts#686]
Hello, i'm using the victoria-metrics-cluster chart to deploy a victoria metrics cluster on k8s with my own proxy as a sidecar of vmselect and vminsert.

For now i'm using a secret to store the proxy config and i would like to store it into a configmap since i have no sensitive data.

So the idea is to add a extra-configmap.yaml to the victoria-metrics-cluster templates in order to deploy config map and so we can use it as extraVolumes (like secrets).

I can make a PR for it.

Thanks.

**Comment by Haleygo** [comment]
Hello, @aloababa 
We would love to add this if it's useful for you, feel free to make a pull request.

**Comment by f41gh7** [comment]
I think, we have to add `extraObjects` to all our charts.

An example for it https://github.com/VictoriaMetrics/helm-charts/commit/e8c84246fb53065ab7f2744eef912d0258ad95ed

**Comment by aloababa** [comment]
I can't see it in the victoria-metrics-cluster chart.
I can make a PR that replace extraSecrets for extraObjects in the victoria-metrics-cluster chart.
It can be useful for secret since secret type is hardcoded to Opaque in the extra-secrets.yaml template.

**Comment by Amper** [comment]
Hey, @aloababa.
We added extraObject in [victoria-metrics-cluster 0.11.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.11.0)

**Comment by aloababa** [comment]
Thank you !
