### ISSUE TITLE
remove chart version related labels from pod labels

### ISSUE THREAD

**Issue by f41gh7** [VictoriaMetrics/helm-charts#695]
Currently there are chart version related labels at the spec.podMetadata.Labels section.

 It causes pod restarts if chart version was changed. But it's no necessary.

 At first, fix victoria-metrics-cluster helm chart. 

 Also, make sure, that we do not include any dymanic labels into podMetadata.

**Comment by Amper** [comment]
There's one problem - removing those labels will still result in a restart once :)
