### ISSUE TITLE
vminsert service doesn't give a way to expose UDP 2003

### ISSUE THREAD

**Issue by mattparkes** [VictoriaMetrics/helm-charts#7]
I enabled the Graphite receiver with:

```
vminsert:
  extraArgs:
    graphiteListenAddr: ":2003"
```

However, there's no way in `vminsert-service.yaml` to add **UDP/2003** to the `vminsert` _Service_, so that it can be forwarded to the `vminsert` _Pods_.

**Comment by tenmozes** [comment]
@mattparkes will provide solution today

**Comment by tenmozes** [comment]
@mattparkes please check 0.4.0 it supports all port on service, deployment and ingress level

**Comment by mattparkes** [comment]
That looks _perfect_! Thanks for the prompt fix!
