### ISSUE TITLE
Setting up scraping with victoria metrics cluster

### ISSUE THREAD

**Issue by Alon-Katz** [VictoriaMetrics/helm-charts#73]
Hey,

I wanted to setup monitoring of VM-cluster with another instance of VM-cluster, I saw that VM-single has this option:

> VictoriaMetrics can be used as drop-in replacement for Prometheus for scraping targets configured in prometheus.yml config file according to the specification. Just set -promscrape.config command-line flag to the path to prometheus.yml config

How can I do this with the helm chart for VM-cluster? Or is this only supported in VM-single?

Thanks!

**Comment by tenmozes** [comment]
Hello, you can do it with cluster, let me a bit describe the ecosystem 
Single version is like a swiss knife, can scrape and store inside itself. But when you have a load or need some distribution you want to split the components. For that we have:
- vm-cluster - distributed metric storage
- vmagent - scraper
- vmalert - which evaluates the rules (alerting and recording)

so the full setup of the solution is
Vmagent scrape the tagres in prometheus format and write the metrics into the cluster, vmalert evaluates the rules by reading them from cluster and sends the alerts to alertmanager (or evalutes the recording rules and stores back to the cluster).

Helm charts give you an option to setup each component

**Comment by Alon-Katz** [comment]
Thanks for such a quick response!

If I understood it correctly, to be able to scrape targets (another vm instance for example) with VM-Cluster I would need to deploy vmagent and do remote write to VM-cluster? 

If thats true and I wanted to do it with minimal dependencies, then I should use the single version VM which can scrape other targets without vmagent? if thats also true then deploying single vm with helm charts I can specify the -promscrape.config with the extraArgs in the values.yaml?

Thanks!

**Comment by f41gh7** [comment]
> If thats true and I wanted to do it with minimal dependencies, then I should use the single version VM which can scrape other targets without vmagent? if thats also true then deploying single vm with helm charts I can specify the -promscrape.config with the extraArgs in the values.yaml?

 Yep, single version of vm can scrape targets with promscrape.config arg.  You have to mount config somehow,  unfortunately chart doesnt support it. Probably operator version is more flexible in this case https://github.com/VictoriaMetrics/operator/blob/master/docs/api.MD#vmsinglespec

**Comment by f41gh7** [comment]
At master branch you can specify additional mounts with extraVolumes and extraVolumeMounts. It should be enough to add scrape config into victoria-metrics-single chart.
