### ISSUE TITLE
vmagent use env from secret for remoteWrite.basicAuth

### ISSUE THREAD

**Issue by AzSiAz** [VictoriaMetrics/helm-charts#74]
I use FluxCD & Sealed secret to protect kubernetes secret stored in private git and the doc [here](https://github.com/VictoriaMetrics/VictoriaMetrics#environment-variables) say it's possible to provide env variable instead of cli flag.
So it should possible to use this [technique](https://kubernetes.io/fr/docs/concepts/configuration/secret/#utilisation-de-secrets-comme-variables-d-environnement) to provide basic auth information to VMAgent to avoid storing it in clear in git

**Comment by tenmozes** [comment]
hello @AzSiAz the option will be added in https://github.com/VictoriaMetrics/helm-charts/pull/75
