### ISSUE TITLE
.server.config.alerts.groups Not Recognized 

### ISSUE THREAD

**Issue by shy221** [VictoriaMetrics/helm-charts#768]
Installing vmalert with my customized recording rules written in section `.server.config.alerts.groups`, and yet it's unable to recognize the rules. 
I used the same set of recording rules in the past to deploy vmalert with, and it worked. 

`❯ helm upgrade --install vector-metrics-agent ./chart
Helm 3.x found; proceeding
Error: UPGRADE FAILED: execution error at (vector-metrics-agent/charts/victoria-metrics-alert/templates/server-deployment.yaml:4:4): at least one item in `.server.config.alerts.groups` or `.server.extraArgs.rule` must be set
`

**Comment by Haleygo** [comment]
Hello, what version did you use?
As i see, there is no relevant change on alert chart recently and I can't reproduce the problem.
Can you paste your `.server.config.alerts.groups` section?

**Comment by shy221** [comment]
Hi, sadly I can't paste my .server.config.alerts.groups section but I can share a look of it. I have a handful of recording rules under this section. Now with the same set of rules, I got the above error. 
My vmalert version is 0.8.3 and my vmagent version is 0.9.11. 

The section looks like below with many more recording rules of the same verified format: 
  server:
    config:
      alerts:
        groups: 
          - name: it-is-a-metric
            interval: 1m
            rules:
              - record: it_is_a_metric:rate1m
                expr: sum by (numA) (rate(it_is_a_metric[1m])) default 0

**Comment by shy221** [comment]
pasting my helm lint output here in case it helps, I can confirm all the below fields are specified. 

```
❯ helm lint .
engine.go:189: [INFO] Fail: at least one item in `.server.config.alerts.groups` or `.server.extraArgs.rule` must be set
engine.go:189: [INFO] Fail: alert manager URL must be specified. Please fill server.notifier.alertmanager.url or enable Alertmanager in values file
engine.go:189: [INFO] Fail: server.datasource.url datasource URL must be specified
==> Linting .
[INFO] Chart.yaml: icon is recommended

1 chart(s) linted, 0 chart(s) failed
```

**Comment by shy221** [comment]
The issue is resolved by running `helm dependency build` in chart repo, and updating dependencies as suggested. Thanks for jumping in on the issue.
