### ISSUE TITLE
Install CRDs using the helm crd directory

### ISSUE THREAD

**Issue by bh-tt** [VictoriaMetrics/helm-charts#770]
Today I moved our vm operator from ansible to argocd-managed. Imagine my surprise when the `helm uninstall` command also deleted all the crd's, and our metric system was down until I got the new operator running, which then promptly deleted alle CRs related to victoriaMetrics.

Helm provides special handling for CRDs using the `crds` directory: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/. One major usecase is that helm does not delete the CRDs if the release is uninstalled.

**Comment by Haleygo** [comment]
Thanks for the report!
But I don't think we should change victoria-metrics-operator chart to use /crds now:
1. moving the crds from /templates to /crds is a breaking change and will delete all the CRDs during upgrade.
2. helm hasn't provided a way to update CRDs if they're under /crds, see https://github.com/helm/helm/issues/7735. So having crd.yaml under /templates can help users to keep update with the latest CRDs.
So I think we should fix this by adding annotation `helm.sh/resource-policy: keep` for CRD resources.

**Comment by Haleygo** [comment]
Should be fixed since [victoria-metrics-operator-0.27.7](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-operator-0.27.7), close as completed.
