### ISSUE TITLE
how to insert secret into VMInsert?

### ISSUE THREAD

**Issue by lucker7777** [VictoriaMetrics/helm-charts#775]
Hello,

I am struggling with setting up TLS between Prometheus and VMInsert. I have a secret I would like to insert into VMInsert, but in _charts/victoria-metrics-cluster/values.yaml_ I see only extraVolumes. There, I tried to add secret this way:
extraVolumes:
    - name: crt
      secret:
        secretName: tls-cert

but it just fails on parsing yaml.

I see there is _extraSecretMounts_, but present only for VMStorage. And when I add it into vminsert, it does nothing.

It is possible to set TLS using configmaps, but I would like to use secrets.
It is doable, or is it somehow included only in Enterprise version?

Thank you

**EDIT**: I was able to get secret into extraVolume when I removed following line (n. 168) from _charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml_ :
{{- include "chart.license.volume" . | nindent 8 }}
This does not feel official, so I guess my question remains.

**Comment by zekker6** [comment]
Chart [v0.11.7](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.11.7) with the fix mentioned above have been released. @lucker7777  Could you please verify if that fixes an issue with `extraVolumes` for you?

**Comment by lucker7777** [comment]
@zekker6 I can confirm it works now. Thanks for fast response.

Thank you.
