### ISSUE TITLE
Deduplication of data

### ISSUE THREAD

**Issue by Yalafeg** [VictoriaMetrics/helm-charts#78]
Hello,

I deployed Victoria-Metrics Cluster and I need to make sure that the data collected and stored on the storage level is not duplicated. How can I verify this? For example if we created 4 replicas for the storage pods, the data should not be stored 4 times. What I mean is that the metrics from prometheus should not be duplicated on the storage level.

Can you please explain the behavior of the below attributes? 
- replicationFactor (vminsert)
- dedup.minScrapeInterval (vmselect)

Why I am unable to add VicotriaMetrics as prometheus datasource for Grafana once the dedup attribute is added?

In case we enabled the persistentVolumeClaim for vmselect, we will have a pvc for each replica created? We will face any impact on Grafana dashboard in case of a pod failure?

Thank you.

**Comment by Yalafeg** [comment]
What I did is that I installed kube-prometheus-stack with a remote_write to victoriametrics using the appropriate URL. What I am afraid of is that the metrics collected with Prometheus will be deduplicated several times at the storage level which will decrease the available capacity. Can you clarify the idea of metrics' collection using Prometheus and saving it to the storage?

And a question about data retention on the storage level, can we do the retention based on the number of GBs occupied and not based on time retention?

Thanks a lot

**Comment by tenmozes** [comment]
hello @Yalafeg 
be default data is not replicated and each pod contains own unique dataset
- replicationFactor > 1 defines how many times you want to duplicate data across nodes. E.g. for replicationFactor=3 vminsert writes data to 3 storage nodes
- dedup.minScrapeInterval, sometime you need to write duplicated data from outside to cluster (e.g. vmagent HA setup) for that you can remove duplication by using dedup.minScrapeInterval. Please take into account - if you set replicationFactor > 1 you need to specify dedup.minScrapeInterval =1ms (https://victoriametrics.github.io/Cluster-VictoriaMetrics.html#replication-and-data-safety)

**Comment by tenmozes** [comment]
@Yalafeg retention is in Months https://victoriametrics.github.io/#retention

**Comment by Yalafeg** [comment]
Thank you  a lot for the details
