### ISSUE TITLE
Use VictoriaMetrics as datasource in Grafana

### ISSUE THREAD

**Issue by Yalafeg** [VictoriaMetrics/helm-charts#80]
Hello,

Based on VictoriaMetrics documentation we can use VictoriaMetrics as Prometheus Datasource in Grafana. I am trying to do it with no luck; I am not sure if I am adding the values correctly. Please can you advise?

From VictoriaMetrics documentation: 
"Grafana setup
Create Prometheus datasource in Grafana with the following url:

http://<victoriametrics-addr>:8428
Substitute <victoriametrics-addr> with the hostname or IP address of VictoriaMetrics.

Then build graphs with the created datasource using PromQL or MetricsQL. VictoriaMetrics supports Prometheus querying API, which is used by Grafana."

Configuration of Grafana section on Kube-prometheus-stack values.yaml:

additionalDataSources:
    - name: prometheus-Victoria-metrics
      type: prometheus
      url: http://IP:Port/select/0/prometheus/
      editable: true
      orgId: 1
      version: 1

Kindly note that I deployed victoria-metrics-cluster chart.

Kindly can you advise also the type of datasources that can be used for Grafana Dashboards?

Thank you.

**Comment by f41gh7** [comment]
Hello, your configuration looks valid, but which port do you use?

 For cluster version you need to specify 8481 port of vmselect.

https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/values.yaml#L121

**Comment by Yalafeg** [comment]
Hello, thank you for your reply.
What I noticed is that the "Bad gateway" error appears when I add the replicationFactor=2 and dedup.minScrapeInterval=1ms to the vminsert and vmselect respectively. Any advise?
What can I do to replicate the data and use grafana dashboard at the same time ?

Thank you,

**Comment by PritomAhmed** [comment]
@Yalafeg what was the solution ? I am facing the same issue.

**Comment by lav-kush** [comment]
@Yalafeg what was the solution ?

**Comment by PritomAhmed** [comment]
@lav-kush Here is what I have done.
In Grafana, I have been using `https://<vmselect:8481>/select/0:0/prometheus` as URL and `Browser` in Access.
