### ISSUE TITLE
How to configure Victoria Metrics as datasource in Grafana Cloud?

### ISSUE THREAD

**Issue by evertonspader-tomtom** [VictoriaMetrics/helm-charts#828]
Since Victoria Metrics data source plugin for Grafana is not signed and Grafana Cloud doesn't accept unsigned plugins to be connected, I have to connect the VM datasource via Prometheus type.

I am, therefore, struggling to get the configuration right. I've seen [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/80) but it didn't help me much.

I have already tried:
```
https://<vmselect-endpoint>:8481
https://<vmselect-endpoint>:8481/select/0/prometheus
```

But the error is always the same:

```
Post "https://<vmselect-endpoint>:8481/select/0:0/prometheus/api/v1/query": dial tcp <IP>:8481: i/o timeout - There was an error returned querying the Prometheus API.
```

I can visit https://<vmselect-endpoint> in a browser and I see and HTML page like the one below so I know the URL is valid:
```
vmselect - a component of VictoriaMetrics cluster
[docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html)
```

What is the correct URL or configuration that I should use?

**Comment by Haleygo** [comment]
Close as dup with https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5624.
