### ISSUE TITLE
`vmauth` missing from `victoria-metrics-k8s-stack` helm chart

### ISSUE THREAD

**Issue by kbweave** [VictoriaMetrics/helm-charts#829]
Is there a particular reason technical or otherwise that `vmauth` isn't exposed and configurable in the `victoria-metrics-k8s-stack` helm chart?

**Comment by Haleygo** [comment]
Thanks for notice!
I think there is no particular reason, we just don't have too many usercases where vmauth is needed for load balancing or authorization in single vmcluster before.
We might add it to `victoria-metrics-k8s-stack` chart after we [create multi-AZ chart](https://github.com/VictoriaMetrics/helm-charts/issues/789).

**Comment by AndrewChubatiuk** [comment]
vmauth is available in k8s-stack 0.25.17
