### ISSUE TITLE
Upgrade Grafana in victoria-metrics-k8s-stack

### ISSUE THREAD

**Issue by yunasc** [VictoriaMetrics/helm-charts#834]
Currently the stack chart depends on 6.59.* version of Grafana chart:
https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/Chart.yaml#L48

Current grafana chart version is 7.2.5:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/Chart.yaml#L3

The 7.x version was released more than 3 months ago.
Is there a reason why the stack chart still relies on previous major version of the grafana chart?

**Comment by Haleygo** [comment]
Grafana has been upgrade to 7.3.x since [victoria-metrics-k8s-stack-0.19.0](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.19.0), close as completed.
