### ISSUE TITLE
Invalid `schema` parameter for VM cluster chart

### ISSUE THREAD

**Issue by MisguidedEmails** [VictoriaMetrics/helm-charts#843]
Added in this PR - https://github.com/VictoriaMetrics/helm-charts/pull/826 - the `tcpSocket` changes are invalid. The `tcpSocket` does not have a `scheme`, as it's purely a TCP socket check, it has no concept of application layer protocols. This can be verified by viewing the schema for the latest k8s version [TCPSocketAction v1 core](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#tcpsocketaction-v1-core).

Due to this, the chart currently fails to deploy for me.

Fix in PR - https://github.com/VictoriaMetrics/helm-charts/pull/844

Note: May be worth having some sort of schema validation (or dry/actual run against a kind cluster or something) to catch oversights like this.

**Comment by Haleygo** [comment]
Hi @MisguidedEmails ,
Thanks for the fix!
>Note: May be worth having some sort of schema validation (or dry/actual run against a kind cluster or something) to catch oversights like this.

Indeed, there is a chart [installation test](https://github.com/VictoriaMetrics/helm-charts/actions/runs/7772142083/job/21211213097?pr=844) on several k8s versions, to ensure each chart can be installed successfully with default values, but this was missing because it's triggered by specific value(

**Comment by MisguidedEmails** [comment]
> Indeed, there is a chart [installation test](https://github.com/VictoriaMetrics/helm-charts/actions/runs/7772142083/job/21211213097?pr=844) on several k8s versions, to ensure each chart can be installed successfully with default values, but this was missing because it's triggered by specific value

Hrm, but it's rendered by default? No specific values are required to present this problem (since it's an if/else). It seems like the pipeline might not be catching those type of errors. If I do a `helm template .` on the pre-fix code, it outputs the invalid `tcpSocket` with no additional values presented.

**Comment by MisguidedEmails** [comment]
Interesting, a helm install doesn't appear to care? But it _is_ invalid. `helm install vm-test .` installs fine, ignoring that invalid part, but `helm install vm-test --dry-run` shows that the `scheme:` is there.

**Comment by MisguidedEmails** [comment]
@Haleygo - I've raised https://github.com/VictoriaMetrics/helm-charts/pull/852 as a fix for the problem. Since helm doesn't appear to error on invalid manifests, and neither do the chart testing or `helm lint` tools. Using `kubectl` appears to be the only option.

I'll close this issue, since the original problem is fixed.
