### ISSUE TITLE
vmalert: please allow to add sidecar in helm chart

### ISSUE THREAD

**Issue by sagor999** [VictoriaMetrics/helm-charts#85]
Would it be possible to add support for specifying sidecar for vmalert?
Would like to add configmap-reload sidecar, that would automatically call `reload` when configmap was updated.

**Comment by f41gh7** [comment]
Added at master branch.

**Comment by sagor999** [comment]
Hi @f41gh7 ,
you bumped the version of the chart, but I it doesn't seem like that chart was released.
At least helm is failing to find it: 
`chart unavailable: chart "victoria-metrics-alert" version "0.3.17" not found in https://victoriametrics.github.io/helm-charts/ repository`

**Comment by f41gh7** [comment]
My bad, didn't bump repo version. Must be ok now.
