### ISSUE TITLE
Disabling vmalertmanager in default values.yaml leads vmalert crashloop (k8s-stack)

### ISSUE THREAD

**Issue by Amper** [VictoriaMetrics/helm-charts#857]
At the moment it is not obvious how to use vmalert only for recording rules (without notifier) in k8s-stack chart.
I think that disabling of vmalertmanager (without adding notifiers) should lead adding `-notifier.blackhole` flag.
In addition i think we should describe scenarios in the docs.

**Comment by Amper** [comment]
@Haleygo @f41gh7 wdyt?

**Comment by f41gh7** [comment]
Looks good to me.

**Comment by AndrewChubatiuk** [comment]
@f41gh7 @Amper Is it still an issue?

**Comment by AndrewChubatiuk** [comment]
by default alertmanager is not starting with `-notifier.blackhole`
