### ISSUE TITLE
Usage of the vm_concurrent_insert_capacity Metric on "VictoriaMetrics - cluster" Dashboard?

### ISSUE THREAD

**Issue by bdschaap** [VictoriaMetrics/helm-charts#859]
The vm_concurrent_insert_capacity metric is referenced in two sections of the "VictoriaMetrics - cluster" dashboard.  One reference is in the vmstorage section and the other is referenced in the vminsert section.  However, neither of the sections filter the vm_concurrent_insert_capacity metric by a label value that's appropriate for that section of the dashboard.  For instance, I would think the vminsert section should filter by `app_kubernetes_io_name` label for the `vminsert` value.  Likewise the vmstorage section should filter for the `vmstorage` value.  There is a job filter that filters by either $job_insert or $job_storage but I'm only using a single scrape job.  Am I scraping metrics incorrectly or does the dashboard need to filter for vminsert and vmstorage differently?

Dashboard references -
- https://github.com/VictoriaMetrics/helm-charts/blob/f3373a0706327eef7885dbc328aabed6c771a528/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml#L5537
- https://github.com/VictoriaMetrics/helm-charts/blob/f3373a0706327eef7885dbc328aabed6c771a528/charts/victoria-metrics-k8s-stack/templates/grafana/dashboards/victoriametrics-cluster.yaml#L7876

**Comment by zekker6** [comment]
Hello @bdschaap, expressions that you've references are using `job` label to filter metrics for vminsert and vmstorage. You need to update scraping configuration to use separate jobs in order to make filters working as expected.

**Comment by bdschaap** [comment]
Thanks for the explanation!
