### ISSUE TITLE
Pushing charts in a public repository?

### ISSUE THREAD

**Issue by julien-sobczak** [VictoriaMetrics/helm-charts#86]
Hi,

Do you plan to publish charts in a public repository like https://artifacthub.io/ or to use Git tags for versioning? 

Regards,

**Comment by tenmozes** [comment]
@f41gh7 what do use think about that?

**Comment by f41gh7** [comment]
will take a look.

**Comment by f41gh7** [comment]
https://artifacthub.io/packages/search?page=1&repo=victoriametrics 

must be accessible.

**Comment by julien-sobczak** [comment]
Thanks 👍
