### ISSUE TITLE
Add optional datasource UID

### ISSUE THREAD

**Issue by ben-nelson-nbcuni** [VictoriaMetrics/helm-charts#860]
Using a datasource UID is best practice for provisioned dashboards that will get deployed across multiple Grafana instances / versions. Please add the option to add UID to https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-k8s-stack/templates/grafana/datasource.yaml#L21-L27

Normally I'd get around this by disabling your defaults and creating my own ConfigMap, however there isn't a helm option to include the grafana datasources sidecar but not include your default values. You should consider using another flag besides `.Values.grafana.sidecar.datasources.enabled` to determine whether this ConfigMap gets created.

**Comment by evandam** [comment]
:+1: for this - I was playing with adding Tempo on top of victoria-metrics-k8s-stack, but not having a static datasource UID makes it impossible to reference declaratively. It's needed for things like Tempo's service map feature and "traces to metrics"

**Comment by AndrewChubatiuk** [comment]
starting next release there'll be `grafana.sidecar.datasources.default` parameter, which contains a slice of default datasources, which can be updated, in a case of this issue it'll be possible to set uid using
```
grafana:
  sidecar:
    datasources:
      default:
        - name: VictoriaMetrics
          isDefault: true
          uid: anyvalue
```

**Comment by AndrewChubatiuk** [comment]
release in [0.25.11](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-k8s-stack-0.25.11)
