### ISSUE TITLE
Bug: templates for retention period fail to render values smaller than one month

### ISSUE THREAD

**Issue by weisdd** [VictoriaMetrics/helm-charts#88]
Starting from v1.45.0, VM allows to have retention periods smaller than one month (https://github.com/VictoriaMetrics/VictoriaMetrics/issues/173).

The issue is that the current template fails to render non-numerical values like `5d`, `1w` - they produce  `--retentionPeriod=0`

**Comment by tenmozes** [comment]
thank you for bug report, the fix will be available in next release (today)
