### ISSUE TITLE
Send InfluxDB data to Victoriametrics cluster

### ISSUE THREAD

**Issue by alesanmed** [VictoriaMetrics/helm-charts#90]
Hi all,

I reviewed the charts available in the repo and I can see that in single mode the port `8428` is exposed as well as other ways of writing influx data. But I can't find that same thing with the cluster mode. How can I achieve that using the cluster?

Thanks!!

**Comment by tenmozes** [comment]
hello, yes you can do it, you  need to specify `influxListenAddr` in extraArgs section
```
vmisert:
 extraArgs: 
    influxListenAddr: ":port"

```

**Comment by alesanmed** [comment]
Thanks for the answer, it worked!! It would be nice to add that variable to the cluster documentation. Thanks again, closing the issue :)
