### ISSUE TITLE
victoria-metrics-k8s-stack - VMServiceScripe for the operator is created twice

### ISSUE THREAD

**Issue by h4wkmoon** [VictoriaMetrics/helm-charts#915]
Hi, 

In the chart victoria-metrics-k8s-stack, the vmservicescrape for the operator is created twice. One by the chart itself, one by the operator subchart.

Metrics are collected twice, and send twice to the remotewrite targets.

I think the one from the chart victoria-metrics-k8s-stack should be removed.

**Comment by Haleygo** [comment]
Hello,
the [VMServiceScrape](https://github.com/VictoriaMetrics/helm-charts/blob/72ae97b4cfb27797928952d2bb0a3f3ecc146cee/charts/victoria-metrics-operator/templates/service_scrape.yaml#L1) inside victoria-metrics-operator is controlled by `.Values.victoria-metrics-operator.serviceMonitor.enabled` and it's false by default, so you won't get two VMServiceScrape if not set `.Values.victoria-metrics-operator.serviceMonitor.enabled=true` specificly.

**Comment by Haleygo** [comment]
Close as not planned, feel free to reopen if you have further question.
