### ISSUE TITLE
Expose streaming aggregation config in vmagent chart

### ISSUE THREAD

**Issue by spoofedpacket** [VictoriaMetrics/helm-charts#930]
Streaming aggregation looks like a great alternative to recording rules and I'd like to try it out:
https://docs.victoriametrics.com/stream-aggregation/

However the `-remoteWrite.streamAggr.config` setting is not available through the vmagent helm chart, requiring some manual intervention to configure. Would it be possible to expose it and a method for defining streaming aggregation rules?

Thanks!

**Comment by Haleygo** [comment]
Hello!
Now you can add `-remoteWrite.streamAggr.config` under [.Values.extraArgs](https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-agent/values.yaml#L78) and mount the config file using extra configmap defined in `extraObjects`
https://github.com/VictoriaMetrics/helm-charts/blob/7b517bea56798e405e13f4934f1a527e5f3a293b/charts/victoria-metrics-agent/values.yaml#L588-L589

Do you have better idea on how to expose this?

**Comment by nemobis** [comment]
In the latest version of the helm chart, which I use in terraform, I do something like

```tf

resource "helm_release" "victoriametrics" {
  name       = "victoriametrics"
  chart      = var.vmcluster_chart_name
  version    = var.vmcluster_chart_version
  repository = var.chart_repository
  namespace  = kubernetes_namespace.victoriametrics.metadata[0].name
  timeout    = 1200

  values = [local.vmcluster_helm_chart_values]
}

resource "kubernetes_config_map" "victoriametrics_relabel_configs" {
  metadata {
    name      = "victoriametrics-agent-vmagent-relabel-configs"
    namespace = kubernetes_namespace.victoriametrics.metadata[0].name
  }

  data = {
    "remotewrite_relabelconfig.yml"     = "${file("${path.module}/manifests/remotewrite_relabelconfig.yaml")}"
    "remotewrite_streamAggr_config.yml" = "${file("${path.module}/manifests/remotewrite_streamAggr_config.yaml")}"
  }
}
```

and then I just use it in extraArgs like

```yaml

extraArgs:
  remoteWrite.relabelConfig: /config/extra/remotewrite_relabelconfig.yml
  remoteWrite.streamAggr.config: /config/extra/remotewrite_streamAggr_config.yml
```

I prefer it this way because I can keep a real YAML file in my terraform repository and use all the usual YAML tools on it.

**Comment by spoofedpacket** [comment]
Thanks for the suggestions, I'll take a look

**Comment by Haleygo** [comment]
Close as answered, feel free to re-open if there is further question.
