### ISSUE TITLE
Add a `vmstorage.vmbackup.enabled` value to the `victoria-metrics-cluster` chart

### ISSUE THREAD

**Issue by jmleddy** [VictoriaMetrics/helm-charts#940]
I know it's unnecessary since we already have `enable` here, but every other component uses `enabled` so we should at least have the option to use this for the inevitable case where users think to use it without checking the default values.

**Comment by Haleygo** [comment]
Hello @jmleddy ,
I don't see `vmstorage.vmbackup` been used in victoria-metrics-cluster, but only `vmstorage.vmbackupmanager`. 
Could you please elaborate the case here or create a pull request?

**Comment by AndrewChubatiuk** [comment]
now all released charts consistently using `enabled`
