### ISSUE TITLE
Custom container port name is not supported.

### ISSUE THREAD

**Issue by hanumanhuda** [VictoriaMetrics/helm-charts#972]
I'm attempting to set up a single Network Load Balancer (NLB) to route traffic to both vminsert and vmselect based on the target port. To achieve this, I need to ensure that each container exposes a unique port name, which will be used to configure the NLB.

I found a helpful approach outlined in this article: [How to Expose Multiple Applications on Amazon EKS using a Single Load Balancer](https://chattirakeshkumar.medium.com/how-to-expose-multiple-applications-on-amazon-eks-using-a-single-load-balancer-d5ca9ee8a4b3).

However, in the current configuration for vminsert and vmselect services, the container port names are hardcoded directly, which doesn't allow for easy templating as per the approach mentioned in the article: https://github.com/VictoriaMetrics/helm-charts/blob/master/charts/victoria-metrics-cluster/templates/vminsert-deployment.yaml#L82

**Comment by Haleygo** [comment]
Added in [victoria-metrics-cluster-0.11.16](https://github.com/VictoriaMetrics/helm-charts/releases/tag/victoria-metrics-cluster-0.11.16), close as completed, feel free to reopen if there is further question.

**Comment by hanumanhuda** [comment]
Thank @Haleygo for the quick response.

**Comment by hanumanhuda** [comment]
this needs to update the port name for liveness and readyness probe because it is using http as defualt.

Error as following
 Readiness probe errored: strconv.Atoi: parsing "http": invalid syntax
