### ISSUE TITLE
Outdated CRD on victoria-metrics-k8s-stack chart

### ISSUE THREAD

**Issue by christian-vdz** [VictoriaMetrics/helm-charts#978]
Hello,

#### Helm chart version:
- victoria-metrics-k8s-stack - 0.20.1

#### Operator version:
- 0.42.3

##### VMAgent reconcile log
<code>{"level":"error","ts":"2024-04-18T16:15:32Z","logger":"manager","msg":"Reconciler error","controller":"vmagent","controllerGroup":"operator.victoriametrics.com","controllerKind":"VMAgent","VMAgent":{"name":"victoria-metrics-k8s-stack","namespace":"monitoring"},"namespace":"monitoring","name":"victoria-metrics-k8s-stack","reconcileID":"0724086f-4a99-4da9-b013-ee8b51aa7d0e","error":"failed to update object status: failed to update object status to=\"expanding\": VMAgent.operator.victoriametrics.com \"victoria-metrics-k8s-stack\" is invalid: [status.availableReplicas: Required value, status.selector: Required value, status.shards: Required value, status.unavailableReplicas: Required value, status.updatedReplicas: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\tsigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:329\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).proce
ssNextWorkItem\n\tsigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\tsigs.k8s.io/controller-runtime@v0.17.2/pkg/internal/controller/
controller.go:227"}</code>

The operator to crash and although it creates VMAgent deployment successfully, it does not create the related service resource and makes it unusable if `vmalert.ingress.enabled` is set to true in the chart's values.  
This is caused by outdated CRDs and updated CRDs manually solves the problem.

Please update the CRDs of this chart, as mentioned in issue https://github.com/VictoriaMetrics/operator/issues/903.

**Comment by f41gh7** [comment]
Thanks for pointing, new version of chart `0.21.0` was recently released.

 Unfortunately, it may require manual update, since helm do not allow CRD updates.

 It could be achieved with command - `kubectl apply -f https://raw.githubusercontent.com/VictoriaMetrics/helm-charts/master/charts/victoria-metrics-k8s-stack/charts/crds/crds/crd.yaml`.

**Comment by matrix-root** [comment]
Hi! Is it possible that issue exists again?
