### ISSUE TITLE
config-reloader liveness checks failing in victoria-metrics-k8s-stack 0.21.0

### ISSUE THREAD

**Issue by brokenjacobs** [VictoriaMetrics/helm-charts#982]
Constant restart loop for vmalertmanager and vmagent:
  Warning  Unhealthy  2m44s (x7 over 3m34s)  kubelet                                Readiness probe failed: Get "http://10.209.98.164:8435/health": dial tcp 10.209.98.164:8435: connect: connection refused
  Warning  Unhealthy  2m44s (x6 over 3m34s)  kubelet                                Liveness probe failed: Get "http://10.209.98.164:8435/health": dial tcp 10.209.98.164:8435: connect: connection refused
  Normal   Killing    2m44s (x2 over 3m13s)  kubelet                                Container config-reloader failed liveness probe, will be restarted

**Comment by h4wkmoon** [comment]
container listens on port 9533 instead.

**Comment by f41gh7** [comment]
Must be fixed at `v0.21.1` chart version.

**Comment by brokenjacobs** [comment]
Thanks for the quick fix!
